### ISSUE TITLE
Multiple TV's

### ISSUE THREAD

**Issue by peezy45** [AntonioMeireles/homebridge-vieramatic#11]
Hi together,

I'm currently facing the issue that if I add a second TV to the home app both of them appear as turned on if only one is turned on.. sometimes the icon just bounces back and forth between on and off for both tv's 

Kind regards

**Comment by AntonioMeireles** [comment]
Hi @peezy45 

(and welcome to GitHub - as this seems your first issue ever! 😄)

regarding your issue, this is going to be hard to reproduce on my side as i only have **one** Panasonic TV so, lets try to gather as much data as possible in order to try to get around this...
so, 
- with what plugin version, homebridge version and node version did you experienced this ? On top of which OS and HW ?
- could you please provide the homebridge logs ? your homebridge `config.json` and the contents of `accessories/vieramatic.json` (under same dir as `config.json`) ?
- if i understood your issue **if** you have only one TV setup at a time everything behaves, right ? 

Thanks for your patience!

**Comment by peezy45** [comment]
HI, first off thanks for your quick answer (didn't expect that 😅)

So regarding the versions 
The plugin version is the latest, NodeJS is v12.16.0, npm v6.13.7, Homebridge 0.45.0.

I'm running all of this on a Raspberry Pi 3b+.

You're right, if it's only one TV everything works like a charm but as soon as the second is being added it's jumping around.


[vieramatic.txt](https://github.com/AntonioMeireles/homebridge-vieramatic/files/4226794/vieramatic.txt)
[config.txt](https://github.com/AntonioMeireles/homebridge-vieramatic/files/4226811/config.txt)

**Comment by AntonioMeireles** [comment]
oh, well ... 

i'm not sure how things worked that far ... you were invoking the plugin twice, one for each TV . (need to make things a bit more obvious in the docs) 
can you try please with the `config.json` along ...
```json
     "platform": "PanasonicVieraTV",
    	    "tvs": [
        	{
            	    "ipAddress": "10.0.1.150",
                    "appId": "Aaw1QrgnXXXXg==",
                    "encKey": "XXXXXXPARb1HCbxDn0oQFg==",
                    "hdmiInputs": []
                },
                {
                    "ipAddress": "10.0.1.151",
                    "appId": "AScri7gn6XXXXg==",
                    "encKey": "XXXXXX9/N1tryuKBaGdDEQ==",
                    "hdmiInputs": []
                }
    	     ]
	
```

All the best, 

António

**Comment by peezy45** [comment]
I already tried it your way as well. But had the same issue 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AntonioMeireles** [comment]
humm... puzzled. contents of `accessories/vieramatic.json` similar both ways, btw ? 

need to think a bit about this... will get back to you later tomorrow. 

thanks again for your patience!

**Comment by peezy45** [comment]
I've tested a little more and just figured out that the first TV (IP : 10.0.1.150) isn't responding anymore so even when I toggle that one on or off it controls the second one (IP: 10.0.1.151).

**Comment by AntonioMeireles** [comment]
@peezy45 

Hi again! (i _think_ i'm making progress, fwiw)

could you please email me directly (address is in git commit logs) to find a way to solve/test fix this soonish (afaict we're in close timezones :-) )

**Comment by AntonioMeireles** [comment]
closing, as this is, afaict, working in the last few versions, per @peezy45 feedback.
