### ISSUE TITLE
TV On Status Within Home App Doesn't Remain Constant

### ISSUE THREAD

**Issue by ValoV83** [AntonioMeireles/homebridge-vieramatic#112]
When I switch the TV on from within the Home app it's On status doesn't remain constant and it automatically switches back to the Off position even though the TV remains physically switched On.

I've tried quitting and restarting the Home app to see if the change of status is noticed at opening the, which it isn't it's reported as Off when the TV is actually on and restarting all my HomeHubs.

To switch off the TV I have to switch the TV On from with the Home app, the TV then switches it Off and the Home app status reads correctly as Off.

I'm using homebridge-vieramatic v4.0.48 on iOS/iPadOS 16.2

**Comment by AntonioMeireles** [comment]
(sorry lag)

Hi @ValoV83 

can you check to see if the just release `homebridge-vieramatic@4.0.49` fixes this ?

thanks for your patience and a great weekend!

**Comment by ValoV83** [comment]
The new release homebridge-vieramatic@4.0.49 has fixed the issue. 

Thanks very much and have a great weekend yourself!

Thanks also for the great plugin as well as the regular updates to it.

**Comment by AntonioMeireles** [comment]
closing as fixed per @ValoV83 's feedback. 

Thanks!
