### ISSUE TITLE
input change via siri - how 

### ISSUE THREAD

**Issue by AntonioMeireles** [AntonioMeireles/homebridge-vieramatic#12]
> hi folks!
> 
> FWIW - i recently got a GX830 (2019 model) which didn't work out of the box due to the lack of encryption support. So, at the lack of a better options, i implemented it :-) https://github.com/AntonioMeireles/homebridge-vieramatic / https://www.npmjs.com/package/homebridge-vieramatic.
> 
> it mostly works already (it's a work in progress) and i just made it public - feedback is welcome!
> 
> A great weekend for all!

@AntonioMeireles nice work, I've got it working on a FZ952B. I can turn it on and off and change the volume all by Siri, but what commands do i use to change inputs with Siri?

_Originally posted by @Peterjohnwood in https://github.com/g30r93g/homebridge-panasonic/issues/14#issuecomment-592986602_

**Comment by AntonioMeireles** [comment]
@Peterjohnwood

Glad to hear that things are working to you too :-) It's great to hear from yet another happy user! (just spread the word :-) ) 

regarding your question, and to the best of my knowledge, sadly currently the Homekit TV integration spec from Apple does not allow to switch inputs with Siri directly (would love to be proved wrong). The workaround is to make shortcuts that do the the input change and invoke those from siri.

All the best, 

António

**Comment by Peterjohnwood** [comment]
> @Peterjohnwood
> 
> Glad to hear that things are working to you too :-) It's great to hear from yet another happy user! (just spread the word :-) )
> 
> regarding your question, and to the best of my knowledge, sadly currently the Homekit TV integration spec from Apple does not allow to switch inputs with Siri directly (would love to be proved wrong). The workaround is to make shortcuts that do the the input change and invoke those from siri.
> 
> All the best,
> 
> António

@AntonioMeireles 

thanks for that. I tried the Siri chortcuts.....but then worked out you can create a scene in the home app its self. Which I think is much slicker. 

nice work and thanks for the replies

**Comment by AntonioMeireles** [comment]
@Peterjohnwood 

just added a note in the docs making things a bit more obvious. Thanks for raising this. 

All the best, 

António
