### ISSUE TITLE
Can not add TV to Apple Home app

### ISSUE THREAD

**Issue by chrastik17** [AntonioMeireles/homebridge-vieramatic#16]
Hello,

I installed Your plug-in. After restart homebridge i have got this:

[2020-4-17 22:56:11] [PanasonicVieraTV] found a Panasonic VIErA TV (TX-49FX780E) at 10.0.0.2 (requires crypto for comunication).

[2020-4-17 22:56:13] [PanasonicVieraTV] Error: An unexpected error happened while adding Viera TV (at '10.0.0.2') as an homebridge Accessory.

TypeError: Cannot read property 'hiden' of undefined
    at VieramaticPlatform.init (/usr/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:479:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

TV is wireless connected, ip address is static.

**Comment by AntonioMeireles** [comment]
Hi! 

thanks for reporting and **welcome** to **GitHub** as this seems to be your first issue ever! 

a quick question - what do you have _exactly_ in your homebridge's `config.json` regarding this plugin ?

thanks in advance! and a great weekend

**Comment by chrastik17** [comment]
Hi, 

yes, it was my first issue ever ;)

here is the code of config.json

{
            "platform": "PanasonicVieraTV",
            "tvs": [
                {
                    "ipAddress": "10.0.0.2",
                    "appId": "AZhbebgn60+v1A==",
                    "encKey": "hc78dfAl3D3l4eNmR9dF4Q==",
                    "hdmiInputs": [
                        {
                            "id": "2",
                            "name": "Denon"
                        }
                    ]
                }
            ]
        }

**Comment by AntonioMeireles** [comment]
another interesting corner case .. can you mail me please (address is in git commit logs) so that we can debug this offline ? (will then mail you a test/debug version in order to sort this out ...) 

Thanks!

**Comment by AntonioMeireles** [comment]
sorted offline. fix went in v0.9.9

@chrastik17  thanks *again* for your patience helping sorting this one out!

**Comment by chrastik17** [comment]
It was my pleasure to help you ;)
