### ISSUE TITLE
pre-flight setup script On a raspberry Pi on LibreELEC Docker oznu 

### ISSUE THREAD

**Issue by Berlinologe86** [AntonioMeireles/homebridge-vieramatic#19]
Hello I have the same problem with the pairing I have the Docker image (oznu) on libreELEC with homebridge-config-ui-x and do not know where I should now hear the pairing command (console in Configui-X / or terminal on the mac) maybe someone can help me :)

**Comment by AntonioMeireles** [comment]
Hi, 

on your mac install node (if using [homebrew](https://brew.sh) as easy as `brew install node@12` and then the plugin  (`npm i homebridge-vieramatic -g`).

after that run the pairing helper (per the stock docs ...)   `$ viera-pair YOUR_TV_IP_ADDRESS_HERE` and then follow the docs editing the homebridge's config and appending the output from above on the `homebridge-config-ui-x interface`

*if* for some reason  this is not enough feel free to bug me again !


have a great weekend and thanxs for your patience!

**Comment by AntonioMeireles** [comment]
@Berlinologe86 

Hi, did you made progress on this ? or do you need extra pointers/help ?

All the Best,

**Comment by Berlinologe86** [comment]
No you heard me believe I heard wrong. I have a Raspberry Pi4B with Libreelec (Kodi) on it as well. In Kodi Lkin Docker and In Docker the oznu homebridge dies with Config ui x. and I can neither execute the pairing command in the Config ui-x terminal nor in the terminal via ssh from my mac.

**Comment by AntonioMeireles** [comment]
humm... can you provide a stack trace ? what exact error are you getting ? 

thanks in advance for your patience!

**Comment by AntonioMeireles** [comment]
@Berlinologe86 

closing, as `2.0.0` should has this solved, since it has native support for full setup from within homebridge's UI. 

please reopen if somehow that isn't enough for your use case.
