### ISSUE TITLE
Issue: Volume and Inputs

### ISSUE THREAD

**Issue by Marfre888** [AntonioMeireles/homebridge-vieramatic#20]
Hi,

Thank you for this plugin. It works perfectly and turns on my TV/HDMI Inputs perfectly.

I have a minor issue with changing volume. I have a Panasonic soundbar connected to the TV's HDMI2, and every time I lower the volume I get the error message; ' The volume operation is not available because sound does not output from TV speaker.', is there any way to fix this. It works fine when I use the Panasonic TV app.

Is it possible to add other input devices such as Netflix and Amazon Video? Would be a great addition along with my HDMI inputs.

**Comment by AntonioMeireles** [comment]
> Hi,
> 
> Thank you for this plugin. It works perfectly and turns on my TV/HDMI Inputs perfectly.
> 

Thanks for your kind words! 

> I have a minor issue with changing volume. I have a Panasonic soundbar connected to the TV's HDMI2, and every time I lower the volume I get the error message; ' The volume operation is not available because sound does not output from TV speaker.', is there any way to fix this. It works fine when I use the Panasonic TV app.
> 

It should be trivial to fix but i have no way to debug this as i don't have a soundbar hooked to my Panasonic TV :( [If someone from Panasonic is reading this please just get back to me with pointers / docs ;-)] and as far as i know the trick isn't documented anywhere

> Is it possible to add other input devices such as Netflix and Amazon Video? Would be a great addition along with my HDMI inputs.

Sure it is, and should work out of the box. it's just that there are so many Apps that they are hidden by default to avoid clutter.  You just need to check the ones you care for them to appear **together** with your hdmi inputs... ( see screenshot below) 
<img width="320" alt="image" src="https://user-images.githubusercontent.com/743527/80311344-16e44b00-87d7-11ea-95df-106db4738ff6.png">

If for some reason this is not working for you then we'd have a bug. Please report back.

Thanks again and a great weekend!

**Comment by Marfre888** [comment]
Regarding; Volume with soundbar, I'm happy to help debug. This soundbar uses Panasonic's Viera link, in case that's helpful.

Regarding; Inputs, that's amazing, I didn't realize they would be hidden inside the TV tile as I have the fan and tv grouped. I missed that in the readme if that's in there.. but this is awesome..

**Comment by Marfre888** [comment]
Hi,

I saw you pushed an update yesterday, I'm not sure if 0.9.9 was meant to address this problem, but I'm sad to report that the issue remains the same.

Also fyi; the new homebridge update 1.0.0 has broken the plugin (I've rolled back to the old version, and it's working fine again)

**Comment by AntonioMeireles** [comment]
@Marfre888, 

can you confirm that `0.9.10` (just pushed) fixes compatibility with `homebridge-1.0.0` ?

**Comment by AntonioMeireles** [comment]
@Marfre888, 

on the sound bar front... some questions: 
- which TV model do you have ?
- which platform (OS/hardware) are you running homebridge on ?
- setting sound via plugin fails for everything or only for content coming from devices attached to the TV via the sound bar ?

Thanks in advance

**Comment by Marfre888** [comment]
1. Panasonic TX 47as650e
2. Homebridge on Raspbian
3. I'm not sure what you mean. The soundbar uses Viera Link, ie: The TV sound output goes into the soundbar and it doesn't use the TV speakers at all. So it's all content, all HDMI and Apps, as long as the soundbar is turned on. If the soundbar is turned off it works correctly.

**Comment by bkchaw** [comment]
![IMG_1927](https://user-images.githubusercontent.com/6147902/80400236-1938c900-88ed-11ea-90fb-bec8d75d501c.jpg)

**Comment by AntonioMeireles** [comment]
@Marfre888 
> * I'm not sure what you mean. The soundbar uses Viera Link, ie: The TV sound output goes into the soundbar and it doesn't use the TV speakers at all. So it's all content, all HDMI and Apps, as long as the soundbar is turned on. If the soundbar is turned off it works correctly.

FWIW **Viera Link** is just the _artistic_ name that Panasonic gives to plain HDMI-CEC. what i wanted to know was if the issue was a general one or restrained to the sound coming from gear plugged to the soundnbar's  own hdmi ports. from your reply seems  it's a general one. (assuming that the soundbar is connected to the HDMI port with ARC)

@bkchaw,  what's  you model ?   

and now the tricky parts ... any kinda soul, with a soundbar attached,  willing to sniff the communications from a phone running the Panasonic TV app to the TV when changing the volume of TV? (preferably someone with a TV more than 2 yrs old as comms are unencrypted and ence way simpler to follow)...


Thanks in advance!

**Comment by Marfre888** [comment]
@AntonioMeireles I understand how you can control devices using HDMI-CEC, but with Viera Link, it also disables your TV's speakers, and sets the soundbar as default. Traditionally you would control the TV speaker + soundbar. You are right in saying the soundbar has an HDMI passthrough, however, the issue seems a general one as long as the soundbar is switched on.

I also confirm that the Panasonic remote app controls the soundbar sound fine.

I've willing to sniff communications between app and tv, and my TV is more than 2 years ago. I'm just not sure how to go about doing it though

**Comment by AntonioMeireles** [comment]
long story shortned - you'd need to setup an http (wireless) proxy, have your fone go through it when communicating and filtering the comms from/to the TV IP address...

**Comment by Marfre888** [comment]
I'll look into it, and see if I manage to get it going.. Will report back soon..

**Comment by AntonioMeireles** [comment]
bah - sorry - closed wrong issue.

**Comment by Marfre888** [comment]
Let me know if this is what you are after..


[wifi dumps.zip](https://github.com/AntonioMeireles/homebridge-vieramatic/files/4542036/wifi.dumps.zip)

**Comment by bkchaw** [comment]
@AntonioMeireles my tv model is TH-55GZ1000 , av receiver is onkyo tx-rz740

**Comment by AntonioMeireles** [comment]
@Marfre888 

**XXL** thanks for your captures. very helpful. 

Now i suspect i know what's going on ...

**Unless** i'm missing the obvious in the captures that @Marfre888 send i think that both @Marfre888 and @bkchaw are attempting to change volume using the 'fan' slider that i ship as an extra accessory (which is what gives us the dreaded error message on-screen) **but** never tried to change the volume the way Apple actually intended people to - by jumping the TV remote app, selecting the desired Panasonic TV there  and **then** change volume using the iphone's physical    volume keys... 
<img width="320" alt="image" src="https://user-images.githubusercontent.com/743527/80466522-976c8e00-8934-11ea-8a3f-1519e421eb37.png">

So, at sight, and again **unless** i'm missing the obvious, **if** volume is changed via the builtin IOS TV remote app using the hardware keys things will just work in current iteration of my plugin (well - they should as i'm using exact same scheme as Panasonic's IOS app - sending to the TV `NRC_VOLUP-ONOFF` and `NRC_VOLDOWN-ONOFF` events)

The core issue is that with the fan slider i'm not using those, at all - i'm telling the TV exactly the value i want for the volume **and** hardcoding the audio channel to where the volume goes... (same thing happens with mute machinery). So the question is to find out a way to have the TV tell us programatically from where it is actually  outputing sound...

Meanwhile, @Marfre888 and just to confirm findings above could you do a capture of the traffic from your rPI to the TV and vice-versa when attempting to change volume via Homekit ? (and **both** by using the fan slider and the hw volume keys inside the ios tv remote app) 

Thanks in advance!

**Comment by Marfre888** [comment]
@AntonioMeireles You've nailed it. My issue is when I change the fan slider. As soon as I went on the remote app, which I didn't even know was a feature. It worked perfectly.

Let me see if I can figure out how to capture traffic on the Pi..

**Comment by AntonioMeireles** [comment]
:-) 

@Marfre888, 


**Thanks**!!!! while on it **if** you ever find a way (via the Pana app, or whatever) to spot/fetch from the TV  the current input source (either App, over-air channel or hdmi input) i'd like the captures. with that data the plugin would be close(r) to feature completeness (bar  bugs) ;-) 

all the best, 

António

**Comment by Marfre888** [comment]
@AntonioMeireles I'm struggling to find a way to capture traffic from the Pi, what do you suggest I use?

I'll read up on the Pana app, but I don't know much about Panasonic TVs.. so I'm not sure exactly where to start from. I'll try and dedicate some time to it, and see if I can figure something out for you.

Sidenote; Something I've noticed that's quite annoying is, when I restart homebridge, the TV status changes to unresponsive, unless the TV is turned on. Sometimes I also need to open the TV remote app before I will connect, and it also won't connect if I turn it on and try to connect to it after homebridge has been restarted. Is there a way you can make the plugin rediscover a TV is connected to without having to restart homebridge?

**Comment by AntonioMeireles** [comment]
> @AntonioMeireles I'm struggling to find a way to capture traffic from the Pi, what do you suggest I use?
> 
probably setting up wireshark on your pi and capturing only traffic to/from your TV
...   
> I'll read up on the Pana app, but I don't know much about Panasonic TVs.. so I'm not sure exactly where to start from. I'll try and dedicate some time to it, and see if I can figure something out for you.
> 
Pana app is... cumbersome at minimum, yes :( 

> Sidenote; Something I've noticed that's quite annoying is, when I restart homebridge, the TV status changes to unresponsive, unless the TV is turned on. Sometimes I also need to open the TV remote app before I will connect, and it also won't connect if I turn it on and try to connect to it after homebridge has been restarted. Is there a way you can make the plugin rediscover a TV is connected to without having to restart homebridge?

Humm...  plugin should behave nicely on homebridge (re)start if TV is ON and if TV is in standby. OTOH if TV is powered OFF (i.e. unreachable at all in the network) it will simply ignore it. (at time i 'd expect that most people would have their TVs on standby when not watching TV).

So, what  you want is that if someone has a defined TV that is unreachable (but was previously paired) at time of homebridge startup then homebridge will keep trying forever in background for that TV to come back ?

Thanks again for your time and effort!

**Comment by AntonioMeireles** [comment]
@Marfre888 , closing this per inactivity. please reopen if this is still not to your liking in `2.0.0` or later.
