### ISSUE TITLE
Unable to connect to FZ950 OLED TV

### ISSUE THREAD

**Issue by borez** [AntonioMeireles/homebridge-vieramatic#21]
Hi,

Tried pairing to my TV using the "viera-pair <IP address>" command. The plugin found my device, but I get an error message as follows:

```
Panasonic VIErA TV (TH-55FZ950STH-55FZ950S) at 192.x.x.x (requires crypto for communication).

An error occurred while attempting to request a pin code from the TV.
Ensure that the TV is powered ON (and NOT in standby).
```

My TV is on another VLAN, while my Raspberry Pi is on the main network. Running a Unifi network with mdns repeater on. Not sure if you could assist?

**Comment by AntonioMeireles** [comment]
sorry lag (strange times) . 

some questions: 
- what exact homebridge version are you running ?
- what exact vieramatic plugin version ?
- The TV is powered ON and no pin appeared on the TV bottom, right ?
- could you check if you have any firewall rules implemented by chance filtering traffick to/from your TV's vlan ?
- do you have any other homebridge plugins working (i.e. is homebridge binding on all interfaces on your rPI (so including the TV's VLAN )? ) 

Thanks again for your patience!

**Comment by borez** [comment]
Hi,

Sorry for the late reply. 

I'm running HB 1.02 (downgraded due to recent mDNS issues with latest version), and v0.9.12 plugin. 

To highlight, I can conclude that the issue came from my HB Pi being on a VLAN vs the TV (on IOT VLAN). Managed to get my TV to pair when I connected it to the main network. Strange as I believe my firewall rules are properly configured to allow network-initiated traffic to pass into IOT VLAN (and for return traffic to pass).

I tried moving the TV back to the IOT network after pairing. The plugin sees the TV but get this error message:

`  port: 55000,
  log: [Function: bound info] {
    info: [Function: info],
    warn: [Function: warn],
    error: [Function: error],
    debug: [Function: debug],
    log: [Function: log],
    prefix: 'PanasonicVieraTV'
  },
  _appId: '<masked>',
  _encKey: '<masked>',
  baseURL: 'http://192.168.3.x:55000',
  specs: {
    friendlyName: '55FZ950',
    modelName: 'Panasonic VIErA',
    modelNumber: 'TH-55FZ950S',
    manufacturer: 'Panasonic',
    serialNumber: '<masked>',
    requiresEncryption: true
  }
}
[6/1/2020, 19:50:29] [PanasonicVieraTV] Error: Request failed with status code 403
    at createError (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  config: {
    url: 'http://192.168.3.x:55000/nrc/control_0',
    method: 'post',
    data: '<?xml version="1.0" encoding="utf-8"?> <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <s:Body> <u:X_GetEncryptSessionId xmlns:u="urn:panasonic-com:service:p00NetworkControl:1"> <X_ApplicationId>AZPB97gn67Tj6w==</X_ApplicationId> <X_EncInfo>aul7IqTZ8wOqOiPcl4/lUhljjd4K6n1UrNVWThX8J9uwqDJL58NYhghxbKuG7r78Jk+4E8qBVkA6Kr68nSzuZndDEgSq1BsD4ewsohLX3EjfOLj/sWj5F6C8S5S56vREgA27u53pNO1PiiOtKYGc/g==</X_EncInfo> </u:X_GetEncryptSessionId> </s:Body> </s:Envelope>',
    headers: {
      Accept: 'text/xml',
      'Content-Type': 'text/xml; charset="utf-8"',
      Host: '192.168.3.x:55000',
      SOAPACTION: '"urn:panasonic-com:service:p00NetworkControl:1#X_GetEncryptSessionId"',
      'Cache-Control': 'no-cache',
      Pragma: 'no-cache',
      'User-Agent': 'axios/0.19.2',
      'Content-Length': 533
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'text',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function],
      abort: [Function],
      aborted: [Function],
      error: [Function],
      timeout: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 9,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular],
      write: [Function: writeAfterFIN],
      [Symbol(asyncId)]: 126,
      [Symbol(kHandle)]: null,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 45,
      [Symbol(kBytesWritten)]: 843
    },
    connection: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 9,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular],
      write: [Function: writeAfterFIN],
      [Symbol(asyncId)]: 126,
      [Symbol(kHandle)]: null,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 45,
      [Symbol(kBytesWritten)]: 843
    },
    _header: 'POST /nrc/control_0 HTTP/1.1\r\n' +
      'Accept: text/xml\r\n' +
      'Content-Type: text/xml; charset="utf-8"\r\n' +
      'Host: 192.168.3.x:55000\r\n' +
      'SOAPACTION: "urn:panasonic-com:service:p00NetworkControl:1#X_GetEncryptSessionId"\r\n' +
      'Cache-Control: no-cache\r\n' +
      'Pragma: no-cache\r\n' +
      'User-Agent: axios/0.19.2\r\n' +
      'Content-Length: 533\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    insecureHTTPParser: undefined,
    path: '/nrc/control_0',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [Socket],
      connection: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 403,
      statusMessage: 'Forbidden',
      client: [Socket],
      _consuming: true,
      _dumped: false,
      req: [Circular],
      responseUrl: 'http://192.168.3.x:55000/nrc/control_0',
      redirects: [],
      [Symbol(kCapture)]: false
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 533,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function],
      _currentRequest: [Circular],
      _currentUrl: 'http://192.168.3.x:55000/nrc/control_0',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      host: [Array],
      soapaction: [Array],
      'cache-control': [Array],
      pragma: [Array],
      'user-agent': [Array],
      'content-length': [Array]
    }
  },
  response: {
    status: 403,
    statusText: 'Forbidden',
    headers: { connection: 'close' },
    config: {
      url: 'http://192.168.3.x:55000/nrc/control_0',
      method: 'post',
      data: '<?xml version="1.0" encoding="utf-8"?> <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <s:Body> <u:X_GetEncryptSessionId xmlns:u="urn:panasonic-com:service:p00NetworkControl:1"> <X_ApplicationId>AZPB97gn67Tj6w==</X_ApplicationId> <X_EncInfo>aul7IqTZ8wOqOiPcl4/lUhljjd4K6n1UrNVWThX8J9uwqDJL58NYhghxbKuG7r78Jk+4E8qBVkA6Kr68nSzuZndDEgSq1BsD4ewsohLX3EjfOLj/sWj5F6C8S5S56vREgA27u53pNO1PiiOtKYGc/g==</X_EncInfo> </u:X_GetEncryptSessionId> </s:Body> </s:Envelope>',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      responseType: 'text',
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'POST /nrc/control_0 HTTP/1.1\r\n' +
        'Accept: text/xml\r\n' +
        'Content-Type: text/xml; charset="utf-8"\r\n' +
        'Host: 192.168.3.x:55000\r\n' +
        'SOAPACTION: "urn:panasonic-com:service:p00NetworkControl:1#X_GetEncryptSessionId"\r\n' +
        'Cache-Control: no-cache\r\n' +
        'Pragma: no-cache\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Content-Length: 533\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      insecureHTTPParser: undefined,
      path: '/nrc/control_0',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: ''
  },
  isAxiosError: true,
  toJSON: [Function]
}
[6/1/2020, 19:50:29] [PanasonicVieraTV] DidFinishLaunching
`

**Comment by AntonioMeireles** [comment]
thanks for your reply - a quick question - do you have already port 55000 fully open (accepting traffic unconditionally in both directions) ? if not please do and try again please.

**Comment by borez** [comment]
Thanks. For some reason the issues persist even if create a firewall rule. Putting this issue aside, I tried again with the TV connected to the same VLAN as the Pi. Error message as follows:

`[6/6/2020, 10:12:17] [PanasonicVieraTV] Error: An unexpected error happened while adding Viera TV (at '192.168.1.106') as an homebridge Accessory.


Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at VieramaticPlatform.init (/usr/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:485:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by AntonioMeireles** [comment]
(sorry lag :( ) this is so strange (the error). could you please reach me by email (address is in git commit logs) in order to try to sort a more expedite way of debugging this ?

thanks again for your patience

**Comment by ris2** [comment]
As a data point, and potential helpful tidbit - I argued with my TV for hours yesterday. Similar setup. TV on IoT VLAN, homebridge on main LAN.

I was testing using postman and curl, and as soon as I put my laptop on the IoT network, the commands work. When I moved the TV to the main LAN, the commands also worked.

It appears the TV will not accept traffic (returns 403 error) when it comes from a different subnet. Looks like Panasonic implemented a 403 (unauthorized) error to block traffic from a different subnet. 

Since this is likely baked into the TV firmware, you will need the TV on your LAN to control it (or implement some sort of proxy on your IoT network to get the traffic to the TV and back.

**Comment by borez** [comment]
Hi,

My sincere apologies for not following up - life’s other priorities took over!

I’ve tried 2.07 and everything works perfectly, even when my TV is on another subnet. 
Not sure if there was new changes, but I incorporated the following changes:

1) I’ve bridged my Homebridge install to connect to my IOT network (via WiFi connection).
2) I’ve enabled mdns repeater on my network. Was previously using mdns reflector but repeater worked better for me.

Thank you very much!

**Comment by AntonioMeireles** [comment]
@borez 

(hi!) is this still an issue with current plugin version ?

**Comment by borez** [comment]
> @borez
> 
> (hi!) is this still an issue with current plugin version ?

Hi,

So sorry for the late reply - life’s other priorities took over! Unfortunately I’m unable to test this anymore, as I’ve migrated to a Home Assistant setup. Sadly the HA plug-in isn’t as well featured as yours.

Many thanks for following up on this, and appreciate it.

**Comment by AntonioMeireles** [comment]
@borez, 

thanks for the feedback and the kind words. have a great weekend. closing.
