### ISSUE TITLE
Possibility to disable sound control

### ISSUE THREAD

**Issue by Seexelas** [AntonioMeireles/homebridge-vieramatic#22]
Hello, 

I just want to know if a future version it is possible to add a line in the config.json to disable volume control. 

I'm using an Audio/Video receiver, and even with the Arc on, the volume reported is not right, and when i move it, the tv tells me that the volume can be controlled. 

If i try with the Tv remote, amp is doing his job.

Thanks a lot ;) take care

**Comment by AntonioMeireles** [comment]
@Seexelas 

not sure if i'm following, so some quick questions - 

a) you are stating that *if* you have your TV attached to an AV receiver the volume is just wrong ? b) or also that when you raise/lower it it doesn't work ? 
c) if b) that happens *both* when you  use the 'fan' slider to change volume or *also* happens when you use your iphone's hardware volume buttons when inside the integrated IOS TV remote (with your TV selected) ?

Thanks in advance ?

**Comment by Seexelas** [comment]
Hi Antonio,

Here are my answers :


a) you are stating that if you have your TV attached to an AV receiver the volume is just wrong ? b) or also that when you raise/lower it it doesn't work ?

I’m using shortcuts which launch an Harmony activity combine with the use of the Home : 

Per example, my Netflix shortcuts :

- Start the Netflix activity which power on tv + avr 
- then the Avr is set to output Tv Audio + volume at 47
-  and finally via your plugin, the tv go to Netflix.

In today case, as you can see on the attached screens, avr is set at 45% and the tv plugin reports 29%.

When I lower or raise via the tv plugin, the tv tells me it can’t as the sound is not coming from the tv.

c) if b) that happens both when you use the 'fan' slider to change volume or also happens when you use your iphone's hardware volume buttons when inside the integrated IOS TV remote (with your TV selected) ?

When I’m using the iOS tu remote,if I select the avr or harmony, I have no trouble, but on the tv it doesn’t work

Thanks a lot for your help,

Best regards

![image](https://user-images.githubusercontent.com/64669806/83878260-29d62d80-a73c-11ea-8178-ff5d02c34d10.png)

![image](https://user-images.githubusercontent.com/64669806/83878283-335f9580-a73c-11ea-8387-be1daeb32727.png)

**Comment by stijndevries** [comment]
Hi there Antonio,

I have a HomeKit fan now so when I ask Siri to turn off the fan it also turns off my TV volume 😬
I would really love it if I could disable the volume slider all together because I always use the remote volume buttons. 

All the best,
Stijn

**Comment by AntonioMeireles** [comment]
> Hi there Antonio,
> 
> I have a HomeKit fan now so when I ask Siri to turn off the fan it also turns off my TV volume 😬
> I would really love it if I could disable the volume slider all together because I always use the remote volume buttons.
> 
> All the best,
> Stijn

Hi, 

just come back from vacation. the ability to disable the custom volume slider should be be available in a new release to be out later today. :-) 

thanks for your patience!

**Comment by AntonioMeireles** [comment]
@stijndevries , @Seexelas 

From the 0.9.90 (out now) updated README...

> 6. disable the custom volume slider (optional)
> 
>    By default each TV will appear on HomeKit with an additional volume slider (of Fan type) in order to provide a visual way to > control the volume (in addition to the hardware volume controls) In order to disable this feature, for each defined TV, just add
> 
 >    ```json 
>         "customVolumeSlider": false,
>     ```

Could you both give it a try and report back ?

Thanks!

**Comment by stijndevries** [comment]
Works great, thank you for you amazing work!
