### ISSUE TITLE
iOS 14: default HomeKit icon is used instead of the TV icon.

### ISSUE THREAD

**Issue by stijndevries** [AntonioMeireles/homebridge-vieramatic#25]
In the first iOS 14 beta the TV is shown as the standard home icon instead of the TV icon ![image](https://user-images.githubusercontent.com/25649105/85862666-5f61ba00-b7c2-11ea-964b-2fcf1465bdf2.jpeg)

I'm not sure if this is an issue with the home app or with vieramatic as I don't have any other TVs. All other functionally still works correctly.

**Comment by AntonioMeireles** [comment]
@stijndevries 

Hi, at sight this is due to homebridge / HAP-NodeJS not yet being fully IOS14 aware (work is in progress there [already](https://github.com/homebridge/HAP-NodeJS/releases/tag/v0.7.5)). 

We'll keep this open tp check / watch developments. 

All the best and a great weekend!
