### ISSUE TITLE
Plug-in ignores to display HDMI inputs

### ISSUE THREAD

**Issue by 1rado1** [AntonioMeireles/homebridge-vieramatic#28]
Hi Antonio,
viera-pair doesn't recognize inputs. These are not reflected in home app even if added manually. 
Any ideas?

`{
    "platform": "PanasonicVieraTV",
    "tvs": [
        {
            "ipAddress": "10.*.*.*",
            "hdmiInputs": []
        }
    ]
}`

**Comment by AntonioMeireles** [comment]
hi, 
(first things first -  hoping you’re doing fine is this pandemic times!) 

fwiw, i have as `beta` a brand new release that should be less error prone.  just follow the steps here - https://github.com/AntonioMeireles/homebridge-vieramatic/tree/typescript-rewrite and give feedback :slightly_smiling_face:
for now, this beta plugin instalable via `npm i homebridge-vieramatic@beta`

It should _just_ work. what TV model do you have btw ?

All the best and a great weekend!

**Comment by 1rado1** [comment]
Im fine, thanks for asking. Hope you're fine as well. 

I can confirm that under beta all works fine. 

I have older model TX-55DX603E. 
All worked just fine 2 updates back if I remember right. 

Now I am dealing with other issue/homebridge related - as I have changed the config and TV stopped responding - now I am not able to add it back to the home app. 
I assume I need to go through the reset circle and re-add all the accessories again which is frustrating. On the other hand your suggestion to go by beta way is just fine for me at the moment. 

Thansk and have a nice weekend!

**Comment by AntonioMeireles** [comment]
> Im fine, thanks for asking. Hope you're fine as well.
> 
> I can confirm that under beta all works fine.
> 
> I have older model TX-55DX603E.
> All worked just fine 2 updates back if I remember right.
> 
> Now I am dealing with other issue/homebridge related - as I have changed the config and TV stopped responding - now I am not able to add it back to the home app.
> I assume I need to go through the reset circle and re-add all the accessories again which is frustrating. On the other hand your suggestion to go by beta way is just fine for me at the moment.
> 
> Thansk and have a nice weekend!

btw, THANKS for the quick feedback! did you try the new web config btw ?

**Comment by 1rado1** [comment]
> > Im fine, thanks for asking. Hope you're fine as well.
> 
> > 
> 
> > I can confirm that under beta all works fine.
> 
> > 
> 
> > I have older model TX-55DX603E.
> 
> > All worked just fine 2 updates back if I remember right.
> 
> > 
> 
> > Now I am dealing with other issue/homebridge related - as I have changed the config and TV stopped responding - now I am not able to add it back to the home app.
> 
> > I assume I need to go through the reset circle and re-add all the accessories again which is frustrating. On the other hand your suggestion to go by beta way is just fine for me at the moment.
> 
> > 
> 
> > Thansk and have a nice weekend!
> 
> 
> 
> btw, THANKS for the quick feedback! did you try the new web config btw ? 

Yes I did and works perfectly!
Thank you for your support
