### ISSUE TITLE
Re-Install - causing issues installing Vieramatic

### ISSUE THREAD

**Issue by Peterjohnwood** [AntonioMeireles/homebridge-vieramatic#29]
Hi Antonio, 

Me again, sorry. after a recent re-install the plugin stopped working. I've pasted the logs below, any help would be appreciated:

[9/7/2020, 16:50:48] Registering platform 'homebridge-vieramatic.PanasonicVieraTV'
[9/7/2020, 16:50:48] [PanasonicVieraTV] Initializing PanasonicVieraTV platform...
[9/7/2020, 16:50:48] [PanasonicVieraTV] Vieramatic Init
[9/7/2020, 16:50:48] [PanasonicVieraTV] found a Panasonic VIErA TV (TX-65FZ950B) at 192.168.1.91 (requires crypto for comunication).

**[9/7/2020, 16:50:48] [PanasonicVieraTV] Error: An unexpected error happened while adding Viera TV (at '192.168.1.91') as an homebridge Accessory.
TypeError: Cannot read property 'hiden' of undefined
    at VieramaticPlatform.init (/usr/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:498:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)**

[9/7/2020, 16:50:48] [PanasonicVieraTV] DidFinishLaunching

**Comment by AntonioMeireles** [comment]
hi,
(first things first - hoping you’re doing fine is this pandemic times!)

humm, what version you migrated from ?

under your homebridge data dir you have an  `accessories/vieramatic.json` file right ? could you paste its contents please ?


Thanks in advance!

**Comment by Peterjohnwood** [comment]
Thanks mate all good thx. So i didnt migrate, i had an issue with my network and had to change the ipaddress...that initally cause the error. I fixed my network issue and changed the ip back, re-paired and still had the issue.

accessories/vieramatic.json Contents below:

{"4D454930-0200-1000-8001-80C75564E47C":{"data":{"inputs":{"hdmi":[{"id":"1","name":"SkyQ","hiden":0},{"id":"2","name":"PS4","hiden":0},{"id":"3","name":"Firestick","hiden":0},{"id":"4","name":"AppleTv","hiden":0}],"applications":{"0":{"name":"Apps Market","id":"0387878700000102","hiden":1},"1":{"name":"Netflix","id":"0010000200000001","hiden":0},"2":{"name":"Freeview Play","id":"0387878700000145","hiden":1},"3":{"name":"VIERA Link","id":"0387878700000016","hiden":1},"4":{"name":"YouTube","id":"0070000200180001","hiden":0},"5":{"name":"Browser","id":"0077777700160002","hiden":1},"6":{"name":"Amazon Prime Video","id":"0010000100180001","hiden":0},"7":{"name":"AccuWeather.com","id":"0070000C00000001","hiden":1},"8":{"name":"Audio Link","id":"0387878700000141","hiden":1},"9":{"name":"Recorded TV","id":"0387878700000013","hiden":1},"10":{"name":"Multi Window","id":"0387878700000050","hiden":1},"11":{"name":"Notification Center","id":"0387878700000140","hiden":1},"12":{"name":"Calendar","id":"0387878700150020","hiden":1},"13":{"name":"Smart Speaker Settings","id":"0387878700000146","hiden":1},"14":{"name":"Cinema","id":"0020002400180001","hiden":1},"15":{"name":"BBC iPlayer","id":"0020000A00170010","hiden":1},"16":{"name":"Plex","id":"0076010507000001","hiden":1},"17":{"name":"BritBox UK","id":"0020013200000001","hiden":1}},"TUNER":{"hiden":0}},"specs":{"friendlyName":"Viera65","modelName":"Panasonic VIErA","modelNumber":"TX-65FZ950B","manufacturer":"Panasonic","serialNumber":"4D454930-0200-1000-8001-80C75564E47C","requiresEncryption":true}}}}

**Comment by AntonioMeireles** [comment]
rename please `accessories/vieramatic.json` to smething else and restart homebridge. would then issue go away ?

**Comment by Peterjohnwood** [comment]
Thanks - now a different error (thx for fast response btw)

[9/7/2020, 17:25:32] [PanasonicVieraTV] Initializing 'Viera65' for the first time.
[9/7/2020, 17:25:32] [PanasonicVieraTV] Error: An unexpected error happened while adding Viera TV (at '192.168.1.91') as an homebridge Accessory.


**TypeError: Cannot read property 'hdmi' of undefined
    at VieramaticPlatform.init (/usr/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:498:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)**

**Comment by AntonioMeireles** [comment]
a) force exit from Home.app and get back to it makes it reappear ?
b) if not, could you provide full homebridge boot logs and your homebridge's  `config.json` ?

Thanks for your patience

**Comment by AntonioMeireles** [comment]
> Thanks i did a few restarts and it all cleared, nice work

closing then 😄 (&& thanks!)
