### ISSUE TITLE
Another pair.js issue

### ISSUE THREAD

**Issue by chrismaurer** [AntonioMeireles/homebridge-vieramatic#3]
Hello,

Please allow me to echo the gratitude of others as this is a long overdue plugin.

I seem, however, to be having a pair.js issue; different from the one in the Closed Issues list. I definitely have the latest version including the require path fix. I get this after entering the PINC code:

found Panasonic VIErA TV (TH-49FX750) requires crypto for comunication.
Enter the displayed pin code: 2248
readline.js:1029
            throw err;
            ^

TypeError: this.authorizePinCode(...).then(...).finally is not a function
    at rl.question (/usr/lib/node_modules/homebridge-vieramatic/lib/viera.coffee:59:13)
    at Interface._onLine (readline.js:283:5)
    at Interface._line (readline.js:638:8)
    at Interface._ttyWrite (readline.js:919:14)
    at ReadStream.onkeypress (readline.js:163:10)
    at ReadStream.emit (events.js:125:13)
    at emitKeys (internal/readline.js:420:14)
    at emitKeys.next (<anonymous>:null:null)
    at ReadStream.onData (readline.js:1019:36)
    at ReadStream.emit (events.js:125:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at ReadStream.Readable.push (_stream_readable.js:213:10)
    at TTY.onread (net.js:590:20)

**Comment by AntonioMeireles** [comment]
@chrismaurer 

hi - thanks for trying this :-) 

I just pushed a newer rev which (hopefully) has better error handling and behaves more deterministically . could you please give it a try when you have time ?


(FWIW i'm aware that the way i'm handling Apps is way suboptimal as if homebridge restarts with the TV in standby App list returned from the TV is empty and things may get wrong fast - working on a long term fix)

All the Best (and thanks for your patience!)

**Comment by chrismaurer** [comment]
Hello, and thanks very much for your prompt response!

I did try again yesterday after updating the module and I got another error that was pretty much identical to the original. Today I tried again since I noticed that you merged in some new commits. This is what happened today:

```
$ viera-pair 192.168.21.123
supplied IP (192.168.21.123) doesn't seem to be from a Panasonic Viera TV (SyntaxError: Invalid regular expression: /<friendlyName>(?<found>...*)</friendlyName>/: Invalid group)
```

I found this one a bit odd since the first few attempts before today all identified my TV correctly (as seen in my opening comment). Not sure if maybe it's just a regex error and nothing more...

**Comment by AntonioMeireles** [comment]
humm. this one is interesting.  will get back to you when i'll get at home later today ... 

meanwhile 
a) this happened with the TV powered ON right (and not in standby), right  ?
b)  could you please paste here the output of `curl http://192.168.21.123:55000/dmr/ddd.xml` (with bot the TV ON and in standby (if they differ) plz ? 

**THANKS** for  your patience!

**Comment by chrismaurer** [comment]
Thanks for your continued support!
There is no output when the TV is in standby. I was kind of surprised-- I though there would be _something_,

[powered_on.txt](https://github.com/AntonioMeireles/homebridge-vieramatic/files/4101985/powered_on.txt)

**Comment by AntonioMeireles** [comment]
OK. much thanks for your reply - **very** helpful!

One additional question : when you say there is no output in standby ... 
it's an empty response (but 200) or not ?
can you plz provide the exact output of `curl -I http://192.168.21.123:55000/dmr/ddd.xml` and `curl http://192.168.21.123:55000/dmr/ddd.xml` with the TV in *standby*?
(FWIW if i'm not missing something - we have here a subtle change of behaviour between 2018 and 2019 models that i need to take care of. also, i expect to have a new version out at the end of the day :-) ).

**Comment by AntonioMeireles** [comment]
could you also  give a try to 0.5.8 that i just pushed, and give please feedback ?

Thnxs!

**Comment by chrismaurer** [comment]
Hello.
Again, thanks for your support!
I updated to 0.5.8 but I had the same problem as yesterday.

I think this should contain all of the output you seek:

[ddd_xml_payload.txt](https://github.com/AntonioMeireles/homebridge-vieramatic/files/4108626/ddd_xml_payload.txt)

**Comment by AntonioMeireles** [comment]
OK. **thanks!**.

So behaviour is really different in that regard between 2018 and 2019 models (dunno about previous ones). Will try to take that into account in next version :-) . (should be out in 6/7 hrs when i'll be at home again :-) )   

All the best, and a great weekend!

**Comment by AntonioMeireles** [comment]
@chrismaurer 

can you give a try to latest tip please and report back? ... (`npm i homebridge-vieramatic@latest` as i've not yet pushed a new version yet)

thanks!

**Comment by chrismaurer** [comment]
Hello!

OK here is what happened:

$ npm i homebridge-vieramatic@latest
+ homebridge-vieramatic@0.5.8
added 23 packages from 68 contributors in 11.884s
[+] no known vulnerabilities found [24 packages audited]

$ viera-pair 192.168.21.123
/usr/local/lib/node_modules/homebridge-vieramatic/lib/cli.coffee:13
      return new Viera(ip[0]).setup();
             ^

TypeError: Viera is not a constructor
    at Object.run (/usr/local/lib/node_modules/homebridge-vieramatic/lib/cli.coffee:9:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-vieramatic/bin/pair.js:11:25)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:665:3

**Comment by AntonioMeireles** [comment]
@chrismaurer 

Hi. 

just pushed 0.5.9 . (try it out please - plain `npm i homebridge-vieramatic`). Btw when upgrading plugin versions no need to re-run `viera-pair ...` at all. the encryption tuple you get previously will be still valid.  

Thanks for your patience and have a great weekend!

**Comment by chrismaurer** [comment]
Hello . Thank you again for your hard work on this Antonio.

The reason why I keep re-running pair is because I haven't been able to complete the pairing process yet, and so I don't yet have an encryption tuple.

Here is what happened this time:

$ viera-pair 192.168.21.123
TypeError: Cannot read property 'error' of undefined
    at getSpecs.then.catch (/usr/local/lib/node_modules/homebridge-vieramatic/lib/viera.coffee:80:14)
    at <anonymous>:null:null
    at process._tickCallback (internal/process/next_tick.js:160:7)

**Just making sure--**
$ npm list -g | grep vieramatic
├─┬ homebridge-vieramatic@0.5.9

**In the home bridge logging, I get this over and over:**
[PanasonicVieraTV] An unexpected error happened while fetching TV metadata. Please do make sure that the TV is powered on and NOT in stand-by. Trying again in 10s.**

**Comment by AntonioMeireles** [comment]
@chrismaurer 

0.5.10 is out ... no functional changes other than just stop masking  a few error classes. try again plz and paste output ... this time we may get a bit more meaningful debug info :-)

**Comment by chrismaurer** [comment]
Hi Antonio.
Thanks!

Here is what happened when trying to pair using 0.5.10.
I think you might need to declare the variable groups used in the regex on line 14 of viera.coffee, no?

`$ viera-pair 192.168.21.123
An unexpected error happened while fetching TV metadata. Please do make sure that the TV is powered on and NOT in stand-by. 


'SyntaxError: Invalid regular expression: /<friendlyName>(?<found>...*)</friendlyName>/: Invalid group'`

**Comment by AntonioMeireles** [comment]
send plz the output of `curl -I http://192.168.21.123:55000/nrc/ddd.xml` and `curl http://192.168.21.123:55000/nrc/ddd.xml` withe the TV ON and standby (it's a slightly different endpoint).

**Comment by AntonioMeireles** [comment]
@chrismaurer - just pushed - 0.5.11 - just has a few more debugging hooks to help sort out your case ...

**Comment by chrismaurer** [comment]
Hi Antonio! Sorry I've been quiet the past couple of days due to some overtime at work.

0.5.11 - This fixed all of the viera-pair issues and now I have my TV working correctly in HomeKit for the first time ever! This is really fantastic!

I read through the other issue regarding HDMI inputs (#7) so I will wait patiently for that. More importantly, however, it's the basic functions that are most important to me, so I can now retire my IR blaster!

Thanks so much for all of your hard work and kind, patient support on this. You're a star! ⭐︎

I am assuming that this now invalidates your need for the output you requested previously (the "/nrc" endpoint), but if you still need that I'll be happy to gather that for you.

**Comment by AntonioMeireles** [comment]
@chrismaurer 

Thanks for your kind words! glad it all works for you now :-) 

just ping me back if you need more features or i break things :-)
