### ISSUE TITLE
add support for sets that require Wake on Lan to get out standby [like Panasonic Ez950]

### ISSUE THREAD

**Issue by jvic1234** [AntonioMeireles/homebridge-vieramatic#30]
Hello,

The tv only responds to wol packet using mac address, I am able to turn on the tv using wol command, the tv wont keep the network card powered up when it is powered off even though I have selected network standby, I reached out to Panasonic and they don't seem to care.

**Comment by AntonioMeireles** [comment]
Hi, 

thanks for reporting. this one is odd, because afaict there are other users with models from that generation with all working without that _kind_ of issue. 

Are you sure that *ALL* the settings bellow  are **ON** on  TV's `Menu -> Network -> TV Remote App Settings` ?
 
> - **TV Remote**
> - **Powered On by Apps**
> - **Networked Standby**


Could you please provide the homebridge logs, also ?

**Thanks**!

**Comment by jvic1234** [comment]
On this tv. I get the following:

Menu -> Network -> TV Remote App Settings

Tv remote = on
Wake on LAN/Wireless Lan = on
Device to upload contents = -

No idea what device to upload is. I don’t see any settings for network standby anywhere. I have all energy savings off.

**Comment by AntonioMeireles** [comment]
humm... per https://www.panasonic.com/content/dam/Panasonic/au/en/support_manual/televisions/TH-65EZ950_eHELP-Operating_Instructions_User_Manual.pdf (page 182)

<img width="904" alt="image" src="https://user-images.githubusercontent.com/743527/92511790-bc87dc00-f205-11ea-8b6c-a477960beb4f.png">

you should have a `Powered On by Apps` option which must be ON ... and should be enough :-) to move forward :-). if you haven't you probably need to update the firmware... 

Hoping this helps! (and thanks for your patience)

**Comment by jvic1234** [comment]
I have the latest firmware on the tv.

Panasonic dropped the game on this tv, they promised hdr10+ for this tv but never delivered.

I don't know if you can have the option to turn on the tv using wol option in your plugin.
you plugin does see the tv online and can turn off the tv.

There is no option for powered on by apps. I looked at every option on the tv. nothing

:(

**Comment by AntonioMeireles** [comment]
(pasted from #32)

> Although my tv won’t turn on as it doesn’t support network standby.
> 
> I also use a Sony tv plugin. Bravia
> 
> This plugin does have the option to wake the tv up using Wol.
> 
> I know I am probably in the minority here but an option to configure the wake up feature using wol would be awesome.
> 
> The plugin does recognize when I manually turn on the tv. It can also power it off. Just unable to turn it on since Panasonic drooped the ball on this oled model. :(

My problem with adding WoL support is that i have no way to test properly :/ 

to be 100% sure
- did you tested with the Panasonic mobile app (Panasonic TV Remote 3) ? Also unable to see/wake the TV ?
- with the TV 'down' a `sudo nmap -Pn IPofTV -p- -sV` gives you what ?

Thanks again for your patience!

**Comment by AntonioMeireles** [comment]
FWIW - from googling yet again ... from [here](http://help.panasonic.ca/PCS/OperatingInstructions/TQBeHELP-EZ1000C-eng.pdf) which also covers (see first page) your model you have again on page 160 that enabling **TV Remote** is all you need... puzzling.  BTW try plz a cheap trick - enable the TV to act as a **DNLA server** (page 64) to check wether that way it just keeps up ...

**Comment by jvic1234** [comment]
I reset the tv, followed all your advice, can't turn on the tv through the plugin.

when the tv is off, I am able to ping the tv.
I can turn on/off the tv using the panasonic app and sending wol command to the tv from my router.

**Comment by jvic1234** [comment]
pi@pi4:~ $ sudo nmap -Pn 192.168.5.50 -p- -sV
Starting Nmap 7.70 ( https://nmap.org ) at 2020-09-10 12:22 MDT


nothing else comes up

**Comment by jvic1234** [comment]
Thanks a ton

**Comment by jvic1234** [comment]
sudo nmap 192.168.5.50
Starting Nmap 7.70 ( https://nmap.org ) at 2020-09-10 13:19 MDT
Nmap scan report for Panasonic.local.lan (192.168.5.50)
Host is up (0.00010s latency).
Not shown: 998 closed ports
PORT    STATE SERVICE
139/tcp open  netbios-ssn
445/tcp open  microsoft-ds
MAC Address: D8:AF:F1:45:23:12 (Panasonic Appliances Company)

**Comment by AntonioMeireles** [comment]
@jvic1234 i'll see what i can do in the next few days... 

meanwhile two quick questions ...

a) can you measure how long it takes for the TV to come out of standby ? (i.e. how long it takes from become unreachable to become reachable on port 55000 (it's api port)) ?
b) how long it takes to go in deep standby (i.e. no pingable) after a power off command is issued. ?

Thanks for your patience!

**Comment by jvic1234** [comment]
Hello. 

In the Apple App Store, there are few official Panasonic tv remote apps. 

Panasonic tv remote 2 is able to turn on the tv. 
Panasonic tv remote 3 is not able to turn on the tv

A) 5 seconds for it to be reachable. 
B) oled tv when turned off has different times it goes into standby mode but it seems less than 20 minute is average. After this time, the device is not ping able but it does respond to Wake on Lan command from my pc and router. 

So it seems Panasonic firmware for this set is the issue but they won’t help at all. 

The only way to wake this tv up is to have the option in the plugin for wol. 

Sadly

**Comment by AntonioMeireles** [comment]
@jvic1234 

is something realistically doable still left from currently shipping plugin feature list or can this now be closed ?

thanxs!

**Comment by stan69b** [comment]
on some TVs, the wakeup from lan does not work, but it can be achived using CEC hdmi.

on.sh
`#!/bin/sh
echo 'on 0' | cec-client -s -d 1 && echo "ON"`

off.sh
`#!/bin/bash
echo 'standby 0' | cec-client -s -d 1 && echo "OFF"`

state.sh
`#!/bin/bash
state=$(echo 'pow <DEVICE #>' | cec-client -s -d 1)
if [[ $state == *" on"* ]]; then
    echo "ON"
else
    echo "OFF"
fi`

using the Script2 plugin from home bridge to execute those 3 scripts, you should have on and off capabilities now 

Homebridge script conf 
`{
            "accessory": "Script2",
            "name": "TV ON/OFF",
            "on": "/var/homebridge/TV-ON-OFF/on.sh",
            "off": "/var/homebridge/TV-ON-OFF/off.sh",
            "state": "/var/homebridge/TV-ON-OFF/state.sh",
            "on_value": "ON",
            "unique_serial": "1234568"
        },`

**Comment by AntonioMeireles** [comment]
@stan69b 

great feedback!

do you want to provide a PR to add just that cookbook for the docs ;-) ?

**Comment by stan69b** [comment]
@AntonioMeireles 

Do you want me to make a PR request on your README.md file to explain this little trick ? or I may have misunderstood your request :P

**Comment by AntonioMeireles** [comment]
yes, a PR would be very handy, and you have the first hand know how about this specific issue :-) . 

have a great weekend!

**Comment by stan69b** [comment]
I'll try to do this today or tomorrow.
Thanks, have a great week end as well.

**Comment by stan69b** [comment]
Pull Request has been made, feel free to edit anything I wrote and change the layout I made :) 
[!63](https://github.com/AntonioMeireles/homebridge-vieramatic/pull/63)

**Comment by AntonioMeireles** [comment]
folks, closing, as afaict we'd gone as far as we could. please reopen or fill a new issue if you find that there's still room for improvement.
