### ISSUE TITLE
TV not found after 2.0.0 update

### ISSUE THREAD

**Issue by 1rado1** [AntonioMeireles/homebridge-vieramatic#33]
Hi António, after update to 2.0.0 from beta release tv cannot be added (not found) within Home.app even after homebridge default restore. 
All worked fine on beta release. 
Any ideas?
Thanks

**Comment by AntonioMeireles** [comment]
that's... *odd* 🤕


could you please paste your homebridge's config.json together with the homebridge's full boot log ?


thanks for your patience!

**Comment by AntonioMeireles** [comment]
@1rado1

test please `2.0.1`, taht just got out, and see if issue persists. (i suspect your issue same as #32). FWIW, boot logs would still be handy.

Thanks again for your patience

**Comment by AntonioMeireles** [comment]
@1rado1 ping

**Comment by 1rado1** [comment]
Hi, I'm sorry for late reply. New version fixes the issue for me. Unfortunately, not able to provide log of initial bug, but as I quickly checked, it was more or less the same issue as you indicated. 
Thanks!
