### ISSUE TITLE
Wrong Pin when pairing

### ISSUE THREAD

**Issue by wagnpi** [AntonioMeireles/homebridge-vieramatic#34]
Hello

I get a message "Wrong PIN" when I try to connect to the TV to get the key.

I'm on the latest 2.0.1 version and I had also instaled previous versions. With the old version the TV show up in the Homekit when adding it with + button, had a bit strugle to find this out cause I was use that things showed up automaticly when adding them to the config file. Anyway the only thing working in the old version was the Volume slider. I could not tunr the TV ON or OFF. Log told moe the TV is not reachable and maybe turned off.

So I gave it a new start with removing it completly and installing the new version 2.0.1
Now I can not find my TV anymore and when I run the page on 8973 to generate the key, I'm submiting my IP, enter the PIN shown on the TV screen then I get a message on the TV that the connection is succesfull but the webpage returns wrong PiN.

Here are my specs:

OS | macOS Catalina
-- | --
10.0.0.20
Node v11.6.0
Mpm v6.14.4
OWmacmini
/Users/OWmacmini/.homebridge
/Users/OWmacmini/.homebridge/config.json

TV Model: TX-65FX680W

My config.json

{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:81:EA:3B:1D:6E",
        "port": 51826,
        "pin": "447-94-860"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "debug": true,
            "log": {
                "method": "file",
                "path": "/Users/OWmacmini/.homebridge/logfile.log"
            },
            "accessoryControl": {
                "debug": true
            },
            "platform": "config"
        },
        {
            "name": "KNX",
            "platform": "KNX"
        },
        {
            "platform": "Calendar",
            "calendars": [
                {
                    "name": "Sandra",
                    "url": "webcal://p33-caldav.icloud.com/published/2/AAAAAAAAAAAAAAAAAAAAAHZC2-Or2j5lNzc4rDOTatVOrPMgedaxuSNKXJOliOOdvwKY2582koG1W1BVK5DfpvISduNieUGJGPcUmALkDbc",
                    "pollingInterval": 15,
                    "offset": "-4h",
                    "sensors": [
                        "Home",
                        "WKND"
                    ]
                }
            ]
        },
        {
            "platform": "Logic",
            "name": "Logic",
            "cacheDir": "/Users/OWmacmini/.homebridge/logic"
        },
        {
            "tvs": [
                {
                    "ipAddress": "10.0.0.50",
                    "hdmiInputs": [
                        {
                            "id": "2",
                            "name": "AppleTV"
                        },
                        {
                            "id": "3",
                            "name": "Mac Mini"
                        }
                    ],
                    "customVolumeSlider": true
                }
            ],
            "platform": "PanasonicVieraTV"
        }
    ],
    "accessories": [
        {
            "accessory": "DummySwitch",
            "name": "Bad Handtuch ON",
            "contact": true
        }
    ]
}

Here is my homebridge Log:

Server Listening...localhost:18082
Setup Payload:
X-HM://00247LO18IAH8
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
[30m[47m                       [49m[39m
[30m[47m    ┌────────────┐     [49m[39m
[30m[47m    │ 447-94-860 │     [49m[39m
[30m[47m    └────────────┘     [49m[39m
[30m[47m                       [49m[39m
[37m[9/9/2020, 11:46:38 PM] [39mHomebridge is running on port 51826.
found a 'Panasonic VIErA' TV (TX-65FX680W) at '10.0.0.50' (requires crypto for comunication).

[37m[9/9/2020, 11:46:38 PM] [39m[36m[PanasonicVieraTV] [39m[31mIGNORING '10.0.0.50' as it is from a Panasonic TV that requires encryption[39m
[31m           'Panasonic VIErA' and no valid credentials were supplied.[39m
[37m[9/9/2020, 11:46:39 PM] [39m[36m[Calendar] [39mPushing calendar sensor 'Sandra' state 0 - value 0
[37m[9/9/2020, 11:46:39 PM] [39m[36m[Calendar] [39mPushing calendar sensor 'Home' state 0 - value 0
[37m[9/9/2020, 11:46:39 PM] [39m[36m[Calendar] [39mPushing calendar sensor 'WKND' state 0 - value 0
[37m[9/9/2020, 11:46:39 PM] [39m[36m[Calendar] [39mScheduling next action in 36800889ms
[37m[9/9/2020, 11:46:39 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:39 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:40 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:40 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:43 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:43 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:43 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:43 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:44 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:47 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[1599688008292] INFO  (175 on OWmacmini.fritz.box): incoming request
    v: 1
    reqId: 286
    req: {
      "method": "GET",
      "url": "/api/server/qrcode.svg",
      "hostname": "10.0.0.20:8581",
      "remoteAddress": "::ffff:10.0.0.35",
      "remotePort": 58047
    }
[1599688008299] INFO  (175 on OWmacmini.fritz.box): request completed
    v: 1
    reqId: 286
    res: {
      "statusCode": 200
    }
    responseTime: 7.125431001186371
[0;37m[9/9/2020, 11:46:48 PM] [0m[0;36m[Config][0m [HapClient] [10.0.0.20:51826 (0E:81:EA:3B:1D:6E)] Connected
[0;37m[9/9/2020, 11:46:48 PM] [0m[0;36m[Config][0m [HapClient] Discovery :: Started
[0;37m[9/9/2020, 11:46:48 PM] [0m[0;36m[Config][0m [HapClient] Discovery :: Found HAP device with username 0E:81:EA:3B:1D:6E
[37m[9/9/2020, 11:46:49 PM] [39m[36m[KNX] [39mGarageDoorOpenerAdvanced->customServiceAPI.getValue(CurrentDoorState)
[37m[9/9/2020, 11:46:49 PM] [39m[36m[KNX] [39mReturning HomeKitValue
[37m[9/9/2020, 11:46:49 PM] [39m[36m[KNX] [39mReturning HomeKitValue of 0
INFO undefined: on KNX Value Change(KNXDoorClosed, old=null, new=1)
INFO undefined: myCurrentDoorState = 0
[37m[9/9/2020, 11:46:49 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:53 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:53 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:53 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:54 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:59 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:46:59 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:01 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:03 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:03 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:03 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:04 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:04 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:05 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:06 PM] [39m[36m[KNX] [39mGarageDoorOpenerAdvanced->customServiceAPI.getValue(CurrentDoorState)
[37m[9/9/2020, 11:47:06 PM] [39m[36m[KNX] [39mReturning HomeKitValue
[37m[9/9/2020, 11:47:06 PM] [39m[36m[KNX] [39mReturning HomeKitValue of 0
INFO undefined: on KNX Value Change(KNXDoorOpened, old=null, new=1)
INFO undefined: myCurrentDoorState = 0
INFO undefined: In if-case -> field===KNXDoorOpened
INFO undefined: knxValue: 1
INFO undefined: oldValue: null
[37m[9/9/2020, 11:47:06 PM] [39m[36m[KNX] [39mGarageDoorOpenerAdvanced->customServiceAPI.setValue(CurrentDoorState,0)
[37m[9/9/2020, 11:47:06 PM] [39m[36m[KNX] [39mGarageDoorOpenerAdvanced->customServiceAPI.setValue(TargetDoorState,0)
INFO undefined: CurrentDoorState = 0 OPEN set
INFO undefined: Init Garage Door HK Status KNXDoorOpened = true
INFO undefined: lastMove = Stopped set
[37m[9/9/2020, 11:47:08 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:13 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:13 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:13 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:14 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:14 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:17 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:19 PM] [39m[36m[KNX] [39mGarageDoorOpenerAdvanced->customServiceAPI.getValue(CurrentDoorState)
[37m[9/9/2020, 11:47:19 PM] [39m[36m[KNX] [39mReturning HomeKitValue
[37m[9/9/2020, 11:47:19 PM] [39m[36m[KNX] [39mReturning HomeKitValue of 0
INFO undefined: on KNX Value Change(KNXDoorClosed, old=1, new=1)
INFO undefined: myCurrentDoorState = 0
[37m[9/9/2020, 11:47:19 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:21 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:24 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:24 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:24 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:24 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:27 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:31 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:31 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:31 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:33 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:34 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:34 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:34 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:34 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:36 PM] [39m[36m[KNX] [39mGarageDoorOpenerAdvanced->customServiceAPI.getValue(CurrentDoorState)
[37m[9/9/2020, 11:47:36 PM] [39m[36m[KNX] [39mReturning HomeKitValue
[37m[9/9/2020, 11:47:36 PM] [39m[36m[KNX] [39mReturning HomeKitValue of 0
INFO undefined: on KNX Value Change(KNXDoorOpened, old=1, new=1)
INFO undefined: myCurrentDoorState = 0
INFO undefined: In if-case -> field===KNXDoorOpened
INFO undefined: knxValue: 1
INFO undefined: oldValue: 1
[37m[9/9/2020, 11:47:37 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:38 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:43 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:43 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:44 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:44 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:44 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[37m[9/9/2020, 11:47:47 PM] [39m[36m[KNX] [39mContactSensor->customServiceAPI.setValue(ContactSensorState,0)
[0;37m[9/9/2020, 11:47:48 PM] [0m[0;36m[Config][0m [HapClient] Discovery :: Ended
[37m[9/9/2020, 11:47:49 PM] [39m[36m[KNX] [39mGarageDoorOpenerAdvanced->customServiceAPI.getValue(CurrentDoorState)
[37m[9/9/2020, 11:47:49 PM] [39m[36m[KNX] [39mReturning HomeKitValue
[37m[9/9/2020, 11:47:49 PM] [39m[36m[KNX] [39mReturning HomeKitValue of 0
INFO undefined: on KNX Value Change(KNXDoorClosed, old=1, new=1)
INFO undefined: myCurrentDoorState = 0

Here is the Vieramtic.json from the previous installation:

{"4D454930-0200-1000-8001-80C75512B448":{"data":{"inputs":{"hdmi":[{"id":"1","name":"Soround","hiden":0},{"id":"2","name":"Apple TV","hiden":0},{"id":"3","name":"Mac mini","hiden":0}],"applications":{"0":{"name":"Apps Market","id":"0387878700000102","hiden":1},"1":{"name":"Netflix","id":"0010000200000001","hiden":1},"2":{"name":"YouTube","id":"0070000200180001","hiden":1},"3":{"name":"Cinema","id":"0020002400180001","hiden":1},"4":{"name":"VIERA Link","id":"0387878700000016","hiden":1},"5":{"name":"TV Guide","id":"0387878700000003","hiden":1},"6":{"name":"Browser","id":"0077777700160002","hiden":1},"7":{"name":"Amazon Prime Video","id":"0010000100180001","hiden":1},"8":{"name":"TuneIn","id":"0010001800000001","hiden":1},"9":{"name":"ARTE","id":"0020000600000001","hiden":1},"10":{"name":"Meteonews TV","id":"0020007100000001","hiden":1},"11":{"name":"AccuWeather.com","id":"0070000C00000001","hiden":1},"12":{"name":"Digital Concert Hall","id":"0076002307170001","hiden":1},"13":{"name":"Audio Link","id":"0387878700000141","hiden":1},"14":{"name":"TV-Aufnahmen","id":"0387878700000013","hiden":1},"15":{"name":"Multi Window","id":"0387878700000050","hiden":1},"16":{"name":"Mitteilungszentrale","id":"0387878700000140","hiden":1},"17":{"name":"Kalender","id":"0387878700150020","hiden":1},"18":{"name":"Smart Speaker Settings","id":"0387878700000146","hiden":1}},"TUNER":{"hiden":0}},"specs":{"friendlyName":"TV_Stuff","modelName":"Panasonic VIErA","modelNumber":"TX-65FX680W","manufacturer":"Panasonic","serialNumber":"4D454930-0200-1000-8001-80C75512B448","requiresEncryption":true}}}}

**Comment by AntonioMeireles** [comment]
**SORRY**,  just my fault. 

just try `2.0.2` (that just was published) as it should just behave again as expected. (crossing fingers) 

Thanks for your patience!

**Comment by wagnpi** [comment]
Hi

Wrong PIN was solved, could pair the TV.

Did try turn ON/OFF. First time no response, Log showed that TV is probably turned OFF.

Turned it off with panasonnic iOS App, but then it stuck in cycling rebooting, and keeps turning ON and OFF after few seconds.

Log.log
https://www.icloud.com/iclouddrive/01YGzcYxBIhSQemG3R8pR9K4Q#logfile

Homebridge.log
https://www.icloud.com/iclouddrive/0DaOzZWnXTdaO7zED7gQCM3wQ#homebridge

Thx for your work.

Pitt

**Comment by AntonioMeireles** [comment]
OK, from the logs ... at sight it seems that you have something else already using / binding to port **`8973`** in homebridge's box. (as you got tons of `Error: listen EADDRINUSE: address already in use :::8973` on them) . freeing it should fix things. Meanwhile, i 'll get a better/ more useful  error message in my side :-)

**Comment by wagnpi** [comment]
Wrong PIN issue is solved, works for me now.
