### ISSUE TITLE
iOS 14 now likely requires a model to be specified. 

### ISSUE THREAD

**Issue by stijndevries** [AntonioMeireles/homebridge-vieramatic#36]
In the GM of iOS 14 new TV models have been added. My TV now shows the generic HomeKit icon. This is probably happening because it requires a type to be specified. 
https://twitter.com/herrsupereg/status/1306279252745166848?s=21

**Comment by AntonioMeireles** [comment]
@stijndevries 

can you try please try `2.0.6` that just went out ? Also, you're in very latest homebridge (1.2.x) right ?

Regards

**Comment by stijndevries** [comment]
Hi Antonio,
It's still showing the home icon with the new update.

**Comment by AntonioMeireles** [comment]
humm... i'm not sure i'm following. I'm on IOS 14 here (both on phone and Apple TVs) and things at sight look OK but, hey - i may be missing the obvious. could you please attach a screenshot ? 

Thanks again!

**Comment by stijndevries** [comment]
It looks like this. 
![image](https://user-images.githubusercontent.com/25649105/93709499-dc40cd80-fb3e-11ea-90c0-b33b22c17e61.jpeg)

Maybe Andi on Twitter has some more information on this. [https://twitter.com/herrsupereg/status/1306194402197622784?s=21](https://twitter.com/herrsupereg/status/1306194402197622784?s=21)

**Comment by AntonioMeireles** [comment]
OK, this one *is* interesting. because i can't reproduce it at all.  i'm on IOS 14 (public release) on iphone, tvOS 14 on apple TVs (all) and homebridge 1.2.3.

if you remove and add again the TV on your setup issue persists ?

Thanks again!

**Comment by wagnpi** [comment]
Hello

Since I updated to iOS14 the plugin does not work anymore. No response from TV. I've already reinstalled it and deleted it from homekit. Now I can not add the TV to homekit, in homebridge devices it shows up and still is able to controle the TV.

Any clues?

Pitt

**Comment by AntonioMeireles** [comment]
> Hello
> 
> Since I updated to iOS14 the plugin does not work anymore. No response from TV. I've already reinstalled it and deleted it from homekit. Now I can not add the TV to homekit, in homebridge devices it shows up and still is able to controle the TV.
> 
> Any clues?
> 
> Pitt

Not sure i follow. what do you mean by  `I can not add the TV to homekit, in homebridge devices it shows up and still is able to controle the TV.` ? by `homebridge devices` you mean homebridge's UI ?

Thanks in advance!

**Comment by wagnpi** [comment]
Hello

Withe homebridge UI I mean the devices in the homebridge UI X from oznu. I've ad a pic.![image](https://user-images.githubusercontent.com/61478013/94462575-07b95d00-01bc-11eb-9766-9321091c9750.jpeg)

With homekit I mean the home app from apple.

Thx to you for your work and patience.

**Comment by wagnpi** [comment]
Hello
Finally I managed to get it back on track. I had to unpair the TV first in the Homebridge settings. Then I could add the TV again. Now everything works again.
Thank you.

**Comment by stijndevries** [comment]
This fixed my issue as well!
