### ISSUE TITLE
pre-flight setup script

### ISSUE THREAD

**Issue by naartem** [AntonioMeireles/homebridge-vieramatic#4]
Hi, How to run the pre-flight setup script?

` $ viera-pair YOUR_TV_IP_ADDRESS_HERE`

I'm running homebridge in a docker container on a pi, but cannot find the script viera-pair.

**Comment by AntonioMeireles** [comment]
on a pi setup (nom dockerized) you'd get ...
```
pi@rpiOne:~ $ sudo npm install -g homebridge-vieramatic
/usr/bin/viera-pair -> /usr/lib/node_modules/homebridge-vieramatic/bin/pair.js
```
above should be enough to get you move further ... (if not - full dockerfile plz)

**Comment by naartem** [comment]
thanks!

**Comment by AntonioMeireles** [comment]
Hi! so things worked out for you ?

**Comment by Berlinologe86** [comment]
Hello I have the same problem with the pairing I have the Docker image (oznu) on libreELEC with homebridge-config-ui-x and do not know where I should now hear the pairing command (console in Configui-X / or terminal on the mac) maybe someone can help me :)
