### ISSUE TITLE
TV not showing in HomeKit 

### ISSUE THREAD

**Issue by mike3177** [AntonioMeireles/homebridge-vieramatic#40]
Hi, my TV shows up and can be switched on and off via Homebridge accessories, but it is missing in HomeKit. 

I’m wondering if it has to do with: 
If your homebridge setup is a containerized one please do note that in order for this plugin to fully work you need to also expose to the outside port 8973, otherwise you won't be able to access to endpoint that generates your encryption credentials.

Does that mean I have to open up port 8973 on my router? 

I’m using homebridge on a synology NAS installed via docker. Version 1.2.3

TV is an FZ800 series.
```
 "tvs": [
                {
                    "ipAddress": "192.168.0.26",
                    "encKey": "5r3zEiT2vhRJnqc81SRNEQ==",
                    "appId": "AbLy+gARMn7K5Q==",
                    "hdmiInputs": [
                        {
                            "id": "1",
                            "name": "Apple TV"
                        },
                        {
                            "id": "2",
                            "name": "Xbox One X"
                        }
                    ],
                    "customVolumeSlider": false
                }
            ],
            "platform": "PanasonicVieraTV"
        }
```

**Comment by AntonioMeireles** [comment]
Hi, 

thanks for reporting! 

at sight, you have no need to access `:8973` anymore - as you seem to have already generated the credentials. 

OTOH, a quick question is you iphone/wifi network in the same vlan as the synology where the docker container is running ?

**Comment by mike3177** [comment]
Hi,

I never realised I had to add the TV as an accessory in HomeKit, it’s all working now thanks!
