### ISSUE TITLE
TV Randomly Turning on - Panasonic TX-65FZ950b 

### ISSUE THREAD

**Issue by Peterjohnwood** [AntonioMeireles/homebridge-vieramatic#44]
Hi Antonio, 

Hope you are well. 

Recently my TV keeps turning itself **on** randomly. I check in homebridge and initially I thought it was down to the startup procedure of the plugin. It does turn on during a homebridge reboot (see below, it does not turn back off again though as indicated below but I assume that's just a timing thing maybe you can change the time from turning on to turning off from 3 seconds to 5 seconds???). 

[11/12/2020, 20:47:09] [PanasonicVieraTV] handling 192.168.1.91 from config.json
found a 'Panasonic VIErA' TV (TX-65FZ950B) at '192.168.1.91' (requires crypto for comunication).
[11/12/2020, 20:47:**09**] [PanasonicVieraTV] TV was OFF; turning it ON for a bit in order to fetch its built-in app list
[11/12/2020, 20:47:11] [Ring] Creating location socket.io connection
[11/12/2020, 20:47:12] [Ring] Ring connected to socket.io server
[11/12/2020, 20:47:**12**] [PanasonicVieraTV] turning TV OFF again
[11/12/2020, 20:47:12] [PanasonicVieraTV] successfully loaded Viera65
[11/12/2020, 20:47:12] Viera65 9C65 is running on port 42101.

But the main problem I'm having is the TV random switching itself on outside of a homebridge reboot.

Any ideas? (I'm on latest version of Raspbian, latest version of homebridge, and latest version of your plugin)

Thanks

P

**Comment by AntonioMeireles** [comment]
@Peterjohnwood 

two quick questions - regarding the TV becoming awake randmnly do you have **anything** in the logs ? also, are you using any sort of automations ?  

Thanks for your patience and a great weekend!

**Comment by Peterjohnwood** [comment]
hey @AntonioMeireles I'm only using automations to turn make sure the TV is off. Like when I leave the house / go to bed etc. How do I turn the detailed logs on, there is nothing in the homebridge logs. 

Re the turning on on Homebridge restart - can you make a change to wait 5 seconds before turning off? i think its currently set at 3.

Pete

**Comment by AntonioMeireles** [comment]
looking into it right now. 

currently is 2s + .5 secs  (per https://github.com/AntonioMeireles/homebridge-vieramatic/blob/master/src/platform.ts#L128-L145) . i'm looking into refactoring it in a more robust way asap. Meanwhile, could you disable all your automations regarding the TV just to make sure that they are unrelated to all this (i start to suspect that they are :( )

**Comment by Peterjohnwood** [comment]
@AntonioMeireles I’ll test for a week and feedback

**Comment by AntonioMeireles** [comment]
@Peterjohnwood 

upgrade and test please the just published `homebridge-vieramatic@2.0.9`. Hopefully it will make the issue go away.

**Comment by Peterjohnwood** [comment]
@AntonioMeireles upgraded and currently testing. Looking good so far.

**Comment by Peterjohnwood** [comment]
@AntonioMeireles mate all good from my end. Didn’t change any automations, just installed your new update. Thanks again, great support. 👍🏼

**Comment by Peterjohnwood** [comment]
Happy to close

**Comment by AntonioMeireles** [comment]
glad it works for you! feel free to bug me again if issues arise again. 


stay safe and have a great and fun weekend
