### ISSUE TITLE
Not recognising TV

### ISSUE THREAD

**Issue by hourami** [AntonioMeireles/homebridge-vieramatic#47]
Hiya,

I installed the script and went into settings and clicked on this Note: If your TV is a 2018 or later model please generate here the required authentication tuple. But it took forever and never came back with the results. 

So I ran  $ viera-pair YOUR_TV_IP_ADDRESS_HERE and got the encryption key and appid (do I need == in both of them?). I put them both in and restarted but still nothing showing in the Home App. 

Help!

**Comment by AntonioMeireles** [comment]
@hourami 

Hi! That's odd.  could you post please your full homebridge `config.json`, together with your homebridge logs, in order to try to spot what's going on  ? 

Thanks in advance!

**Comment by hourami** [comment]
Apologies, really odd, seems to have kicked into life!!
