### ISSUE TITLE
i can't get Encryption Key

### ISSUE THREAD

**Issue by chiuch930** [AntonioMeireles/homebridge-vieramatic#48]
HI Sir
i have  TH-55HX750W and TH-49GX750W ,but can not get Encryption Key 
i has setted remote app option is all open
http://172.16.0.11:8973/?ip=172.16.0.238 is not response
OS: CentOS 7
Homebridge: v1.2.4
Node.js: v14.15.1

Homebridge log:

URL {
  href: 'http://172.16.0.11:8973/',
  origin: 'http://172.16.0.11:8973',
  protocol: 'http:',
  username: '',
  password: '',
  host: '172.16.0.11:8973',
  hostname: '172.16.0.11',
  port: '8973',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
URL {
  href: 'http://172.16.0.11:8973/?ip=172.16.0.238',
  origin: 'http://172.16.0.11:8973',
  protocol: 'http:',
  username: '',
  password: '',
  host: '172.16.0.11:8973',
  hostname: '172.16.0.11',
  port: '8973',
  pathname: '/',
  search: '?ip=172.16.0.238',
  searchParams: URLSearchParams { 'ip' => '172.16.0.238' },
  hash: ''
}
found a 'Panasonic VIErA' TV (TH-55HX750W) at '172.16.0.238' (requires crypto for comunication).

(node:1888) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'requiresEncryption' of undefined
    at VieraTV.sendRequest (/usr/lib/node_modules/homebridge-vieramatic/src/viera.ts:406:18)
    at VieraTV.requestPinCode (/usr/lib/node_modules/homebridge-vieramatic/src/viera.ts:474:17)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge-vieramatic/src/viera.ts:687:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
URL {
  href: 'http://172.16.0.11:8973/?ip=172.16.0.238',
  origin: 'http://172.16.0.11:8973',
  protocol: 'http:',
  username: '',
  password: '',
  host: '172.16.0.11:8973',
  hostname: '172.16.0.11',
  port: '8973',
  pathname: '/',
  search: '?ip=172.16.0.238',
  searchParams: URLSearchParams { 'ip' => '172.16.0.238' },
  hash: ''
}
found a 'Panasonic VIErA' TV (TH-55HX750W) at '172.16.0.238' (requires crypto for comunication).

(node:1888) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'requiresEncryption' of undefined
    at VieraTV.sendRequest (/usr/lib/node_modules/homebridge-vieramatic/src/viera.ts:406:18)
    at VieraTV.requestPinCode (/usr/lib/node_modules/homebridge-vieramatic/src/viera.ts:474:17)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge-vieramatic/src/viera.ts:687:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by mmn3** [comment]
Me neither. Please fix! Thanks!

**Comment by AntonioMeireles** [comment]
issue spotted. fix and new release in a bit

**Comment by AntonioMeireles** [comment]
@chiuch930, @mmn3 

could you both please give a try to `homebridge-vieramatic@2.0.12-beta.2` that i've just published. should get this fixed for good!

Have a great weekend and thanks for your patience!

**Comment by mmn3** [comment]
> @chiuch930, @mmn3
> 
> could you both please give a try to `homebridge-vieramatic@2.0.12-beta.2` that i've just published. should get this fixed for good!
> 
> Have a great weekend and thanks for your patience!

Thank you so much! It's working again :) Good job!

**Comment by AntonioMeireles** [comment]
@mmn3 

**great to hear** && thanks for the quick feedback! will promote to non beta status :-) 

[closing]

**Comment by chiuch930** [comment]
it working ，very thanks
