### ISSUE TITLE
Automated TV Apps handling and Volume 

### ISSUE THREAD

**Issue by koupus** [AntonioMeireles/homebridge-vieramatic#5]
Hello Antonio,

Many thanks for your work. It's great!!

I just would like to know if it's possible ti make the "Automated TV Apps handling" optional ?  Or hide it in Homekit? (with a add in my json config) cause it make me 25 accessories I don't use...

And same thing with the lightbulb accessories (open as volume)?

Thanks again, bye.

Tom

**Comment by AntonioMeireles** [comment]
Hi! 

regarding your questions:

- i'm already 'hiding'/disabling the discovered apps by default (as they are too many and i doubt that people want / expect **not** to have them all enabled)  - isn't that enough for you, or isn't working as expected ?
- yes, i can add a flag to make the lightbulb optional. expect it later this week. 

**Thanks** again for your feedback!

**Comment by koupus** [comment]
Hy Antonio,
Don’t find the hiding/disabling function! Something i miss?
You can see my capture in attachment.
Nice for the lightbulb.
Bye, Tom
![9EFFC8CC-68F9-40C4-868F-E52DC44DBE76](https://user-images.githubusercontent.com/50924184/72932432-16639080-3d60-11ea-934b-fdab26666a76.jpeg)
![735AE98D-3CAF-4B23-ACF2-6882FE94F880](https://user-images.githubusercontent.com/50924184/72932433-16fc2700-3d60-11ea-952a-86acf02e9b98.png)

**Comment by James712346** [comment]
When I first installed the plugin, all those accessories were inputs but after restarting homebridge I have got the same issue as @koupus

**Comment by AntonioMeireles** [comment]
@James712346 

i think i spotted the root  cause and hope to have a fix available later in the day. While on this, what's your model btw ?

@koupus, no that is not not the desired behaviour :-) hope to have permanent fix later today!.

Thanks  you all for your patience!

**Comment by AntonioMeireles** [comment]
Hi again, 


could you give a try to 0.5.8 that i just pushed, and give please feedback ? 

thanks in advance

P.S. you may need to unpair and pair again your TV on Home.app.

**Comment by koupus** [comment]
Hi,
the new pair method work fine but a few time after turn off the tv with HomeKit there's a bug (see below), homebridge restart and: 
[1/23/2020, 9:03:29 PM] [PanasonicVieraTV] **unable to connect to TV (at 192.168.1.13). Either it is powered off** or the supplied IP is wrong 
[1/23/2020, 9:03:29 PM] [PanasonicVieraTV] DidFinishLaunching

The bug log:
Error: Request failed with status code 400
    at createError (/usr/local/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1137:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
 {
  config: {
    url: 'http://192.168.1.13:55000/dmr/control_0',
    method: 'post',
    data: '<?xml version="1.0" encoding="utf-8"?> <s:Envelope ' +
      'xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" ' +
      's:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> ' +
      '<s:Body> <u:GetMute ' +
      'xmlns:u="urn:schemas-upnp-org:service:RenderingControl:1"> ' +
      '<InstanceID>0</InstanceID><Channel>Master</Channel> </u:GetMute> ' +
      '</s:Body> </s:Envelope>',
    headers: {
      Accept: 'text/xml',
      'Content-Type': 'text/xml; charset="utf-8"',
      Host: '192.168.1.13:55000',
      SOAPACTION: '"urn:schemas-upnp-org:service:RenderingControl:1#GetMute"',
      'Cache-Control': 'no-cache',
      Pragma: 'no-cache',
      'User-Agent': 'axios/0.19.2',
      'Content-Length': 331
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'text',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function],
      abort: [Function],
      aborted: [Function],
      error: [Function],
      timeout: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular],
      write: [Function: writeAfterFIN],
      [Symbol(asyncId)]: 14444,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 47,
      [Symbol(kBytesWritten)]: 628
    },
    connection: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular],
      write: [Function: writeAfterFIN],
      [Symbol(asyncId)]: 14444,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBytesRead)]: 47,
      [Symbol(kBytesWritten)]: 628
    },
    _header: 'POST /dmr/control_0 HTTP/1.1\r' +
      '\nAccept: text/xml\r' +
      '\nContent-Type: text/xml; charset="utf-8"\r' +
      '\nHost: 192.168.1.13:55000\r' +
      '\nSOAPACTION: ' +
      '"urn:schemas-upnp-org:service:RenderingControl:1#GetMute"\r' +
      '\nCache-Control: no-cache\r' +
      '\nPragma: no-cache\r' +
      '\nUser-Agent: axios/0.19.2\r' +
      '\nContent-Length: 331\r' +
      '\nConnection: close\r' +
      '\n\r' +
      '\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256
    },
    socketPath: undefined,
    method: 'POST',
    path: '/dmr/control_0',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [Socket],
      connection: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: false,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: true,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [Socket],
      _consuming: true,
      _dumped: false,
      req: [Circular],
      responseUrl: 'http://192.168.1.13:55000/dmr/control_0',
      redirects: []
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 331,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function],
      _currentRequest: [Circular],
      _currentUrl: 'http://192.168.1.13:55000/dmr/control_0'
    },
    [Symbol(isCorked)]: false,
    [Symbol(outHeadersKey)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      host: [Array],
      soapaction: [Array],
      'cache-control': [Array],
      pragma: [Array],
      'user-agent': [Array],
      'content-length': [Array]
    }
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: { connection: 'close' },
    config: {
      url: 'http://192.168.1.13:55000/dmr/control_0',
      method: 'post',
      data: '<?xml version="1.0" encoding="utf-8"?> <s:Envelope ' +
        'xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" ' +
        's:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> ' +
        '<s:Body> <u:GetMute ' +
        'xmlns:u="urn:schemas-upnp-org:service:RenderingControl:1"> ' +
        '<InstanceID>0</InstanceID><Channel>Master</Channel> </u:GetMute> ' +
        '</s:Body> </s:Envelope>',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      responseType: 'text',
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'POST /dmr/control_0 HTTP/1.1\r' +
        '\nAccept: text/xml\r' +
        '\nContent-Type: text/xml; charset="utf-8"\r' +
        '\nHost: 192.168.1.13:55000\r' +
        '\nSOAPACTION: ' +
        '"urn:schemas-upnp-org:service:RenderingControl:1#GetMute"\r' +
        '\nCache-Control: no-cache\r' +
        '\nPragma: no-cache\r' +
        '\nUser-Agent: axios/0.19.2\r' +
        '\nContent-Length: 331\r' +
        '\nConnection: close\r' +
        '\n\r' +
        '\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      path: '/dmr/control_0',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      _redirectable: [Writable],
      [Symbol(isCorked)]: false,
      [Symbol(outHeadersKey)]: [Object: null prototype]
    },
    data: ''
  },
  isAxiosError: true,
  toJSON: [Function]
}

**Comment by AntonioMeireles** [comment]
@koupus

could you get me the homebridge logs previous to that please ? and what model / year is that ? ... anyway will try to repro here. 

*THANKS* again!

**Comment by James712346** [comment]
Ok, it all working now
I had to delete and reinstall my homebridge docker as the TV platform was acting as an accessory to the bridge, not being independent and wouldn't go away even after uninstalling this plugin. 
My TV model: TH-40CS610A

**Comment by koupus** [comment]
> @koupus
> 
> could you get me the homebridge logs previous to that please ? and what model / year is that ? ... anyway will try to repro here.
> 
> _THANKS_ again!

Hi my log:
[1/23/2020, 8:46:17 PM] Homebridge is running on port 51826.
[0;37m[1/23/2020, 8:46:34 PM] [0m[0;36m[Config][0m [0;31m[homebridge-vieramatic] Error: ESOCKETTIMEDOUT[0m
[0;37m[1/23/2020, 8:46:34 PM] [0m[0;36m[Config][0m [0;31m[homebridge-tahoma] Error: ESOCKETTIMEDOUT[0m
[0;37m[1/23/2020, 8:49:52 PM] [0m[0;36m[Config][0m Homebridge restart request received
[0;37m[1/23/2020, 8:49:53 PM] [0m[0;36m[Config][0m No restart command defined, killing process...
[1/23/2020, 8:49:53 PM] Got SIGTERM, shutting down Homebridge...
[1/23/2020, 8:49:59 PM] Loaded config.json with 0 accessories and 4 platforms.
[1/23/2020, 8:49:59 PM] ---
[1/23/2020, 8:49:59 PM] Loaded plugin: homebridge-config-ui-x
[1/23/2020, 8:49:59 PM] Registering platform 'homebridge-config-ui-x.config'
[1/23/2020, 8:49:59 PM] ---
[1/23/2020, 8:49:59 PM] Loaded plugin: homebridge-nest
[1/23/2020, 8:49:59 PM] Registering platform 'homebridge-nest.Nest'
[1/23/2020, 8:49:59 PM] ---
[1/23/2020, 8:50:00 PM] Loaded plugin: homebridge-tahoma
homebridge-tahoma API version: 2.4
[1/23/2020, 8:50:00 PM] Registering platform 'homebridge-tahoma.Tahoma'
[1/23/2020, 8:50:00 PM] ---
[1/23/2020, 8:50:01 PM] Loaded plugin: homebridge-vieramatic
homebridge API version: 2.4
[1/23/2020, 8:50:01 PM] Registering platform 'homebridge-vieramatic.PanasonicVieraTV'
[1/23/2020, 8:50:01 PM] ---
[1/23/2020, 8:50:01 PM] Loading 4 platforms...
[1/23/2020, 8:50:01 PM] [Config] Initializing config platform...
[1/23/2020, 8:50:01 PM] [Config] Spawning homebridge-config-ui-x with PID 68430
[1/23/2020, 8:50:01 PM] [Tahoma] Initializing Tahoma platform...
[1/23/2020, 8:50:01 PM] [Tahoma] Fetch accessories...
[1/23/2020, 8:50:01 PM] [Tahoma] Login TaHoma server...
[1/23/2020, 8:50:01 PM] [Nest] Initializing Nest platform...
[1/23/2020, 8:50:01 PM] [Nest] Fetching Nest devices.
[1/23/2020, 8:50:01 PM] [PanasonicVieraTV] Initializing PanasonicVieraTV platform...
[1/23/2020, 8:50:01 PM] [PanasonicVieraTV] Vieramatic Init
[1/23/2020, 8:50:01 PM] Loading 0 accessories...
found a Panasonic VIErA TV (TX-58GX800E) at 192.168.1.13.

found Panasonic VIErA TV (TX-58GX800E) requires crypto for comunication.
[1/23/2020, 8:50:01 PM] [PanasonicVieraTV] DidFinishLaunching
[1/23/2020, 8:50:01 PM] 58GX800_Series is running on port 64265.
[1/23/2020, 8:50:01 PM] Please add [58GX800_Series] manually in Home app. Setup Code: 031-45-154

Tv model: TX-58GX810E
2019

Thanks,bye.
Tom

**Comment by koupus** [comment]
Hi,
Seems to be ok now! I Made a « clean » install (delete the persist and accesories folder). Reinstall the plugin, pair the TV in terminal and home.
Thanks!

**Comment by AntonioMeireles** [comment]
Hi, i've fixed a few more corner cases, fwiw 

...can you give a try to latest tip please and report back? ... (`npm i homebridge-vieramatic@latest` as i've not yet pushed a new version yet)

thanks && have a great weekend!

**Comment by koupus** [comment]
Work great now! Thanks

**Comment by AntonioMeireles** [comment]
@koupus 

**GREAT** to hear! thanks again for your patience! 

p.s. now just spread the word :-)
