### ISSUE TITLE
Vieramatic on Hyper-V homebridge - cant get encryption details

### ISSUE THREAD

**Issue by olloT** [AntonioMeireles/homebridge-vieramatic#50]
I am using latest homebridge image via hyper-v. Installation via webinterface went easy, TV is also found but i cant get the "required authentication tuple" 

The tool always give this errormessage - TV is definitly ON. 
```
"Found a TX-65FZ800W, on ip address 192.168.1.151, which requires encryption.
Unfortunatelly the TV seems to be in standby. Please turn it ON and try again."
```

Any ideas? I read something about Port openings. But how can i identify if the relevant port is open?

**Comment by AntonioMeireles** [comment]
humm. hyper-V may or not be the issue. not sure. i'm using now UPnP probes to detect TV power status as it works across more (old and new) models. (can you start homebridge in debug mode and send me the whole logs ?) 

Thanks in advance and Happy Hollidays!

**Comment by olloT** [comment]
Thanks for the fast reply.  Here is the logon-protocol regarding vieramatic. 
Just to let you know - I also tested the iOS app Panasonic remote 3 to check if the TV network is okay - it connected flawlesss

```
[12/22/2020, 9:19:17 PM] [Config] Initializing config platform...
[12/22/2020, 9:19:17 PM] [Config] Running in Service Mode
[12/22/2020, 9:19:17 PM] [PanasonicVieraTV] Initializing PanasonicVieraTV platform...
[12/22/2020, 9:19:17 PM] [PanasonicVieraTV] Finished initializing platform: PanasonicVieraTV
[12/22/2020, 9:19:17 PM] [PanasonicVieraTV] Executed didFinishLaunching callback
[12/22/2020, 9:19:17 PM] [PanasonicVieraTV] handling 192.168.1.151 from config.json
[12/22/2020, 9:19:17 PM] [PanasonicVieraTV] handling undefined from config.json
Setup Payload:
X-HM://0023ISYWY89O1
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[12/22/2020, 9:19:17 PM] Homebridge v1.2.4 is running on port 52134.
[12/22/2020, 9:19:17 PM] [PanasonicVieraTV] IGNORING 'undefined' as it is not a valid ip address.
        

{
  "customVolumeSlider": false
}
[12/22/2020, 9:19:17 PM] [Homebridge UI] Homebridge Config UI X v4.36.0 is listening on :: port 8581
found a 'Panasonic VIErA' TV (TX-65FZ800W) at '192.168.1.151' (requires crypto for comunication).
[12/22/2020, 9:19:17 PM] [PanasonicVieraTV] IGNORING '192.168.1.151' as it is from a Panasonic TV that requires encryption 'Panasonic VIErA' and no valid credentials were supplied.
```

**Comment by AntonioMeireles** [comment]
@olloT, still puzzled by this. looks an issue specific to your setup. could you email me (email is the one in git commit logs) to try to debug this offline ?

thanks for your patience!.

**Comment by olloT** [comment]
Hi Antonio. In the meantime I tried several things and can help you ;) 
Its not an HyperV related bug because I have same behavior with a Raspberry Pi 4.  So I played a little in the Panasonic TV setup options. 

Im using the Main TV as a TV-IP Server to stream DVB-T2 signals via network to the TVs in the other rooms. When i disable the TV-Server your plugin works flawless ;)

**Comment by AntonioMeireles** [comment]
@olloT - humm - could it be a port collision ?

**Comment by AntonioMeireles** [comment]
@olloT did you had any progress on this ?

**Comment by AntonioMeireles** [comment]
closing per lack of additional data. AFAICT this isn't related to the plugin per se. please reopen if this is still an issue.

**Comment by maverick85** [comment]
Hi there I'm sorry but I'm having sort of similar issue my error is:

```
[15/08/2022, 18:50:20] Homebridge v1.5.0 (HAP v0.10.2) (HomeBridge) is running on port 51463.
[15/08/2022, 18:50:20] [PanasonicVieraTV] found a 'Panasonic VIErA' TV (TX-49FX600E) at '192.168.231.51' (requires crypto for communication).
[15/08/2022, 18:50:20] [PanasonicVieraTV] '192.168.231.51 ('Panasonic VIErA')' ignored, as it is from a Panasonic TV that
        requires encryption and no working credentials were supplied.
```

The Panasonic TV is model TX-49FX600.

I have HomeBridge on a given VLAN and on another I have Home Assistant (more on that below). The HomeBridge IS on the same network (/24).
Currently at the router I have allow all from network to network. I have avahi support. Everything works but the TV.

But putting aside the firewall allow rules and avahi etc, because homebridge and in fact on the same network. I can ping it, I can communicate

```
curl -L 192.168.231.101:55000/nrc/ddd.xml
<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:vli="urn:schemas-panasonic-com:vli" xmlns:viera="urn:schemas-panasonic-com:viera" xmlns:pxn="urn:schemas-panasonic-com:pxn">
...
```

From the machine running homebridge.

So I connected the TV to the network where home assistant is, added it, connected without issues. I connected the TV back, got the appid and encryption key from the config file and replaced for the older values. (those older values came from backup config. I'm not sure if they were invalid bc in the meanwhile Factory reset the tv, but still wasn't able to connect with homebridge) connected.

But by only entering the IP, I never got to connect. If not relevant I am sorry and please do close! TY

**Comment by maverick85** [comment]
Hi I'm sorry but I have a follow up on this.
Unfortunately even tho I got the credentials from hassio and no longer shows the error of `requires encryption and no working credentials were supplied.`, and it does appear to connect to the TV,  I am completely unable to control it.

I've changed the Home Assistant to the IoT devices network, and as before it connects and finds the Viera TV.
Panasonic Remote App works as well, both v2 and v3 available on the App Store.

Removing all conf from the plugin and re-adding, fails as it says A.B.C.D can't be edited.

**Comment by AntonioMeireles** [comment]
Hi, 

a quick question ? from the TV's network - can you ping the TV ? and curl TV's port 55000 ?

This looks like a network, bridging issue. 

All the best, 

António

**Comment by maverick85** [comment]
Hi @AntonioMeireles thank you for the quick reply.

Yes I can ping the TV and curl TV's port 55000. Actually I've port scanned it and I see a couple more open as well.

```
# curl -L 192.168.231.51:55000/nrc/ddd.xml
<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:vli="urn:schemas-panasonic-com:vli" xmlns:viera="urn:schemas-panasonic-com:viera" xmlns:pxn="urn:schemas-panasonic-com:pxn">
  <specVersion><major>1</major><minor>0</minor></specVersion>
  <device>
    <deviceType>urn:panasonic-com:device:p00RemoteController:1</deviceType>
    <friendlyName>PanasonicTVS</friendlyName>
    <manufacturer>Panasonic</manufacturer>
    <modelName>Panasonic VIErA</modelName>
    <modelNumber>TX-49FX600E</modelNumber>

[...]
```

Homebridge and the TV are on the same subnet.

**Comment by maverick85** [comment]
A follow up:

I was looking at the logs and this crossed my sight:

```
[16/08/2022, 14:52:13] [Homebridge UI] [homebridge-vieramatic] Incoming Request: /ping
[16/08/2022, 14:52:15] [Homebridge UI] [homebridge-vieramatic] ---> (ping) 192.168.231.101 false
[16/08/2022, 14:52:23] [Homebridge UI] [homebridge-vieramatic] Terminating child process...
[16/08/2022, 14:52:23] [Homebridge UI] [homebridge-vieramatic] Child process ended
[16/08/2022, 15:42:58] [Homebridge UI] [homebridge-vieramatic] Incoming Request: /ping
[16/08/2022, 15:42:59] [Homebridge UI] [homebridge-vieramatic] ---> (ping) 192.168.231.101 false
[16/08/2022, 15:43:03] [Homebridge UI] [homebridge-vieramatic] Terminating child process...
[16/08/2022, 15:43:03] [Homebridge UI] [homebridge-vieramatic] Child process ended
```

```
[root@home-ai homebridge-vieramatic]# ping panasonic49fx600
PING panasonic49fx600.iot.home-ai.local (192.168.231.101) 56(84) bytes of data.
64 bytes from panasonic49fx600.iot.home-ai.local (192.168.231.101): icmp_seq=1 ttl=64 time=2.08 ms
64 bytes from panasonic49fx600.iot.home-ai.local (192.168.231.101): icmp_seq=2 ttl=64 time=2.25 ms
64 bytes from panasonic49fx600.iot.home-ai.local (192.168.231.101): icmp_seq=3 ttl=64 time=2.75 ms
64 bytes from panasonic49fx600.iot.home-ai.local (192.168.231.101): icmp_seq=4 ttl=64 time=2.30 ms
^C
--- panasonic49fx600.iot.home-ai.local ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 2.075/2.343/2.752/0.256 ms
[root@home-ai homebridge-vieramatic]# 
```

It's pingable from the homebridge host, even via name it resolves, not that I'm using names really, but just to see if it was working.

I have no idea why the plugin isn't able to ping. This is literally the only thing that is not working.

**Comment by maverick85** [comment]
@AntonioMeireles should I open a new ticket for this? Thank you

**Comment by AntonioMeireles** [comment]
no need. on my queue... sorry latency; bad time of the year... will take a look next week

**Comment by maverick85** [comment]
@AntonioMeireles alright mate thanks a lot for the quick feedback! If you do need anything let me know!
