### ISSUE TITLE
How do i get the Encryption Key and the AppID for 2018 Models and later?

### ISSUE THREAD

**Issue by Chrislak2000** [AntonioMeireles/homebridge-vieramatic#51]
Hey guys!
I`m new on GitHub and recently startet with my Homebridge setup.
I´ve installed this plugin and everything worked fine on the first TV (2017 Model i guess). Then i tried to activate the new one (2020 Model) but couldn´t find out where to get the Encryption Key and the AppID.

Can anyone help me?
Thanks for your replies, wish you merry chrismas and stay healthy!
Chris

**Comment by olloT** [comment]
When you install the plugin you have a link on top of the config-page. You have to insert the IP of your TV afterwards and hopefully youll get the auth-key.

**Comment by Chrislak2000** [comment]
Thank you so much! It works now :)
