### ISSUE TITLE
Request: TV Visible in Control Center

### ISSUE THREAD

**Issue by Peterjohnwood** [AntonioMeireles/homebridge-vieramatic#52]
Hi @AntonioMeireles , 

Is it possible to get the TV volume visible in the control center?

**Comment by Peterjohnwood** [comment]
Hi, is it Possible to get the TV volume visible in the control Center?

**Comment by AntonioMeireles** [comment]
you need to have the  

```json 
"customVolumeSlider": true,
```

snippet on your TV's config block homebridge's `in settings.json`


that should make the Volume be visible :-) 

Happy New Year!

**Comment by Peterjohnwood** [comment]
Thanks @AntonioMeireles i mean like a normal HomeKit compatible TV, in IOS control Centre

**Comment by Peterjohnwood** [comment]
Happy new year to you too

**Comment by AntonioMeireles** [comment]
@Peterjohnwood 

how so?, it should just be there ... can you post a screenshot / example of what are you looking for ? (maybe it's just me missing the point)

**Comment by Peterjohnwood** [comment]
lol, no problem, so I have the volume control turned on and can (via home) turn the volume up and down. Where I’m referring to is here, is there anyway to show the TV in this section and be able to use this area re volume control:

![E5B96B88-28F1-4452-AA0E-7EA2D0FB4EA7](https://user-images.githubusercontent.com/56692030/103463958-22a1ed00-4d28-11eb-825a-42107c81a8d8.png)

**Comment by g30r93g** [comment]
@Peterjohnwood thats an airplay feature, not a home feature. sure you could setup an airplay speaker proxy to allow you to change the tv's volume but it won't show the now playing and will also be a bit verbose. in terms of an implementation for this plugin, it's a little bit more difficult than just adding one line of code, it's writing a whole other plugin and then writing interface code to allow the two to communicate.

**Comment by Peterjohnwood** [comment]
Thanks for your response @g30r93g, i thought as much to be honest, I just wasn’t 100% sure if that control panel was only an airplay feature. 👍🏼

**Comment by AntonioMeireles** [comment]
@Peterjohnwood 

yeah! @g30r93g is right - not much i could do without inside help from Panasonic folks. 

Happy New Year for both. 

Closing.

**Comment by Peterjohnwood** [comment]
👍🏼

**Comment by standre** [comment]
But did you know that you can use the iPhone volume buttons to control the TV volume? Just select the Panasonic TV in the Apple TV Remote control and try.

**Comment by Peterjohnwood** [comment]
Oh nice one...thanks for that...just sorted it for me :)
