### ISSUE TITLE
requires crypto for comunication

### ISSUE THREAD

**Issue by Merexor** [AntonioMeireles/homebridge-vieramatic#57]
Hello,
I have a Panasonic TX-58GXW804 and I have it since last year. Since then I had no success controlling the TV via a plugin. My older TV TX-43EXW604 has been able to do this since the beginning. Can somebody help me ?

found a 'Panasonic VIErA' TV (TX-58GX800W) at '10.0.0.3' (requires crypto for comunication).
[PanasonicVieraTV] IGNORING '10.0.0.3' as it is from a Panasonic TV that requires encryption 'Panasonic VIErA' and no valid credentials were supplied

**Comment by AntonioMeireles** [comment]
hi @Merexor 

it seems that you need to generate the encryption key pair that is required to talk to the TV as it seems to be one that requires it. Following the steps [here](https://github.com/AntonioMeireles/homebridge-vieramatic#the-simple-way-recommended) should guide you to generate and install it, which should solve you issue.

**Comment by Merexor** [comment]
@AntonioMeireles you mean step 3 ? 
I tried it .. i think i make something wrong. The command didn't work. Can you give me more details to do this ?

3. run the pre-flight setup script, and take note of the output

 $ viera-pair YOUR_TV_IP_ADDRESS_HERE

**Comment by AntonioMeireles** [comment]
[with TV turned ON] which part of running `viera-pair 10.0.0.3`  is failing for you ?

**Comment by Merexor** [comment]
@AntonioMeireles Sorry .. if I misunderstand the instructions. 

![Uploading 104513330...]

**Comment by AntonioMeireles** [comment]
Oh, it seems you are using HOOBS [there already a long thread about if - #14] which isn't actually very well supported :/ 


> **\<context>**
> i don't use it nor have bandwidth to also have it it / target it and OTOH with the advent of the homebridge-config-ui which is officially blessed by homebridge upstream team the HOOBS appeal not that big **
> <\/context>**

long shot - please run from the cli on HOOBS box `find  / | grep viera-pair$` and then to `...FULL_PATH_/viera-pair  10.0.0.3` and report back. 

hope this helps.

**Comment by Merexor** [comment]
@AntonioMeireles thanks !!
It works ! .. Finally ;)

**Comment by AntonioMeireles** [comment]
@Merexor

great to hear!. closing then.

feel free to reopen or fill a new issue if issues arise! 

all the best!
