### ISSUE TITLE
Authentication tuple fails

### ISSUE THREAD

**Issue by cewuk** [AntonioMeireles/homebridge-vieramatic#59]
Fresh install of Homebridge image, attempting to add TV and getting following error when attempting to generate authentication key:

"Found a TX-43HX940B, on ip address 192.168.178.60, which requires encryption. 
Unfortunatelly the TV seems to be in standby. Please turn it ON and try again."

TV is on, and all settings advised in instructions are turned on.

Any advice?

Thanks for developing plugin, looks great - hopefully I can get it to work 👍

**Comment by AntonioMeireles** [comment]
@cewuk 

all items referenced [here](https://github.com/AntonioMeireles/homebridge-vieramatic#tv-setup) are activated in your TV ?

**Comment by cewuk** [comment]
Yes all on and able to access the TV via the Panasonic remote app.

Oddly I now can access the tuple at all, saying Safari can't connect to server - although able to access other parts of Homebridge fine. Worked fine yesterday so not sure what's going on.

**Comment by cewuk** [comment]
Getting there:

Needed to add the TV without an encryption key, this then enabled the Tuple to work.

I also then tried to use the Panasonic Remote app. Seems this then allowed the Tuple to successfully connect.

I've now got the TV appearing in Homebridge but not yet in the iOS Home app for some reason.

**Comment by cewuk** [comment]
All working now 🙂
