### ISSUE TITLE
Callback function error

### ISSUE THREAD

**Issue by koupus** [AntonioMeireles/homebridge-vieramatic#6]
Hi Antonio,

Got the following error this morning.I think it happen after an automation...
what do think about?

Bye, Tom.

"Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at fn (/usr/local/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:344:22)
    at down (/usr/local/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:360:9)
    at Subscription.<anonymous> (/usr/local/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:369:50)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)"

**Comment by AntonioMeireles** [comment]
humm... my fault i'd guess :-) . looking into it. **THANKS!**

**Comment by koupus** [comment]
Just verified, It happen with an automation (power off when I leave home) and it restart homebridge!

**Comment by AntonioMeireles** [comment]
@koupus `0.5.12` is out. please give it a try :-) 

&& **Thanks**!

**Comment by AntonioMeireles** [comment]
@koupus 

hi, any update on you side on this ?

Thanks in advance!

**Comment by koupus** [comment]
Hey Antonio,

still persist with 0.5.12 

"Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at fn (/usr/local/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:371:24)
    at down (/usr/local/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:387:11)
    at Subscription.<anonymous> (/usr/local/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:396:52)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)"

Seems to be ok with 0.5.13 ! Thanks!
Unfortunately the 24 accessories come back with the plugin update as issue #5 ;-(

Do i re-open the issue #5 ? 

Let me know, bye.

Tom

**Comment by AntonioMeireles** [comment]
Thanks for coming back! 

glad that the callback thing seems to be gone. 

re: the accessories getting unlinked - that may be a (sort of cosmetic) side-effect of you upgrading from a version prior to the turn of the TV into an (homebridge) 'external accessory'. Just removing the TV from your 'home' and re-adding it should be all that is needed to get this right. (if not then there's **really** a bug.) 

thanks again for your patience!

**Comment by koupus** [comment]
Hey! You’re right!!!
It’s ok with removing and re-add the TV from
Home App!!!!
Many thanks again!!!

**Comment by AntonioMeireles** [comment]
@koupus 

**GREAT**!! && have a great weekend! 

PS: feel free to bug again if you feel things aren't _100%_ right :-)

**Comment by koupus** [comment]
Hi Antonio,
Sorry I have to reopen the issue. I thought it was good (in reality, I just made a test of the automation in the home app) but not.
That the log happen when I leave home  : 

Error: Request failed with status code 500
    at createError (/usr/local/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  config: {
    url: 'http://192.168.1.13:55000/nrc/control_0',
    method: 'post',
    data: '<?xml version="1.0" encoding="utf-8"?> <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <s:Body> <u:X_EncryptedCommand xmlns:u="urn:panasonic-com:service:p00NetworkControl:1"> <X_ApplicationId>ARSPkwxN6aQCoQ==</X_ApplicationId> <X_EncInfo>Fl2QziiJJotMalz4FAFXYDWBcLIbimJvHUqndwal0Fuqa2kSKwF291U6aSB/aVFK/19TuyDNYM0vAQ/VedXSP2lRFcobtOQH6sI1mTQYcD/Kxr8DkieGVU72bzCHS9Yq96MUEI6YfWcsLbLTW37jXoyAF4rnSXabSCCrV5RyFInkfqNlGSgyFshLrsRTet0EmIdLbw9Baz/pqdRSvbsi+zA4XgECjHDcrnNcCbIXTOUyuXuRyVtIMrF01r0qolrLdPMkh4VH3tP6FimBtg0yqrKtxmUbo7apcmgYDsJCo2PsbsXWwUfiIgykYtvKE+qisB/2o/zrZA3OK4GnNWkykB2oOU4TCjuMkDENeiWxUakqSwI3A+9BdFSG7wbmcyfTs6ByQiNSHp01s0vqLsPFzg==</X_EncInfo> </u:X_EncryptedCommand> </s:Body> </s:Envelope>',
    headers: {
      Accept: 'text/xml',
      'Content-Type': 'text/xml; charset="utf-8"',
      Host: '192.168.1.13:55000',
      SOAPACTION: '"urn:panasonic-com:service:p00NetworkControl:1#X_EncryptedCommand"',
      'Cache-Control': 'no-cache',
      Pragma: 'no-cache',
      'User-Agent': 'axios/0.19.2',
      'Content-Length': 783
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'text',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(asyncId)]: 1189382,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'POST /nrc/control_0 HTTP/1.1\r\n' +
      'Accept: text/xml\r\n' +
      'Content-Type: text/xml; charset="utf-8"\r\n' +
      'Host: 192.168.1.13:55000\r\n' +
      'SOAPACTION: "urn:panasonic-com:service:p00NetworkControl:1#X_EncryptedCommand"\r\n' +
      'Cache-Control: no-cache\r\n' +
      'Pragma: no-cache\r\n' +
      'User-Agent: axios/0.19.2\r\n' +
      'Content-Length: 783\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    path: '/nrc/control_0',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://192.168.1.13:55000/nrc/control_0',
      redirects: [],
      [Symbol(kCapture)]: false
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 783,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://192.168.1.13:55000/nrc/control_0',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      host: [Array],
      soapaction: [Array],
      'cache-control': [Array],
      pragma: [Array],
      'user-agent': [Array],
      'content-length': [Array]
    }
  },
  response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: {
      'content-length': '488',
      'content-type': 'text/xml; charset="utf-8"',
      ext: '',
      server: 'Panasonic-VIErA/1, UPnP/1.0, Panasonic MIL DLNA SERVER',
      connection: 'close'
    },
    config: {
      url: 'http://192.168.1.13:55000/nrc/control_0',
      method: 'post',
      data: '<?xml version="1.0" encoding="utf-8"?> <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <s:Body> <u:X_EncryptedCommand xmlns:u="urn:panasonic-com:service:p00NetworkControl:1"> <X_ApplicationId>ARSPkwxN6aQCoQ==</X_ApplicationId> <X_EncInfo>Fl2QziiJJotMalz4FAFXYDWBcLIbimJvHUqndwal0Fuqa2kSKwF291U6aSB/aVFK/19TuyDNYM0vAQ/VedXSP2lRFcobtOQH6sI1mTQYcD/Kxr8DkieGVU72bzCHS9Yq96MUEI6YfWcsLbLTW37jXoyAF4rnSXabSCCrV5RyFInkfqNlGSgyFshLrsRTet0EmIdLbw9Baz/pqdRSvbsi+zA4XgECjHDcrnNcCbIXTOUyuXuRyVtIMrF01r0qolrLdPMkh4VH3tP6FimBtg0yqrKtxmUbo7apcmgYDsJCo2PsbsXWwUfiIgykYtvKE+qisB/2o/zrZA3OK4GnNWkykB2oOU4TCjuMkDENeiWxUakqSwI3A+9BdFSG7wbmcyfTs6ByQiNSHp01s0vqLsPFzg==</X_EncInfo> </u:X_EncryptedCommand> </s:Body> </s:Envelope>',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      responseType: 'text',
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'POST /nrc/control_0 HTTP/1.1\r\n' +
        'Accept: text/xml\r\n' +
        'Content-Type: text/xml; charset="utf-8"\r\n' +
        'Host: 192.168.1.13:55000\r\n' +
        'SOAPACTION: "urn:panasonic-com:service:p00NetworkControl:1#X_EncryptedCommand"\r\n' +
        'Cache-Control: no-cache\r\n' +
        'Pragma: no-cache\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Content-Length: 783\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      path: '/nrc/control_0',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '<?xml version="1.0" encoding="utf-8"?>\n' +
      '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">\n' +
      ' <s:Body>\n' +
      '  <s:Fault>\n' +
      '   <faultcode>s:Client</faultcode>\n' +
      '   <faultstring>UPnPError</faultstring>\n' +
      '   <detail>\n' +
      '    <UPnPError xmlns="urn:schemas-upnp-org:control-1-0">\n' +
      '     <errorCode>612</errorCode>\n' +
      '     <errorDescription>No such session</errorDescription>\n' +
      '    </UPnPError>\n' +
      '   </detail>\n' +
      '  </s:Fault>\n' +
      ' </s:Body>\n' +
      '</s:Envelope>\n'
  },
  isAxiosError: true,
  toJSON: [Function (anonymous)]
}

**Comment by AntonioMeireles** [comment]
hi!

this one is a **very** interesting error - `No such session`. Trying to understand how that could be - could be either my side - or we've hit an odd Panasonic TV sw bug ... What was the command being executed ?  Also, what's your setup - running homebridge over what ? In the meantime - looking into making these non fatal. 

Thanks once again!

**Comment by AntonioMeireles** [comment]
@koupus

what version were you running btw at time of crash ?

**Comment by koupus** [comment]
I run Homebridge on a macmini.
Actualy use the 0.5.80 version. It happen only when my automation ‘leave home’ start (not in test mode).
Will try tomorrow with the 0.5.82
![47954918-265A-4BC1-B66A-0083FD10872D](https://user-images.githubusercontent.com/50924184/73682676-24e76b80-46c1-11ea-8101-4265bc0b45dd.jpeg)

**Comment by koupus** [comment]
Hi Antonio,
seems to be good now with your last version (0.5.82)!
Great work again, many thanks.
Bye, Tom.

**Comment by AntonioMeireles** [comment]
@koupus 

thanks for the update! glad it's working for you **again** :-) 

FWIW i'm not fully confident that i've cornered already all the corner cases. i'm slowly refactoring all the callback web involved talking to te TV to get things a fair bit more robust. may take a while as the TV is a sort of black box which makes hard to develop a proper test suite. 

All the Best, 

António

**Comment by koupus** [comment]
Hey Antonio,
don't understand It happen again... it's really strange...
I'm in V0.5.82

The log:
Error: Request failed with status code 500
    at createError (/usr/local/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-vieramatic/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:333:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  config: {
    url: 'http://192.168.1.13:55000/nrc/control_0',
    method: 'post',
    data: '<?xml version="1.0" encoding="utf-8"?> <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <s:Body> <u:X_EncryptedCommand xmlns:u="urn:panasonic-com:service:p00NetworkControl:1"> <X_ApplicationId>ARSPkwxN6aQCoQ==</X_ApplicationId> <X_EncInfo>70u0Z1POfJIP+OzjLkmiFDZcsAdcd7IcbAX1+vqeEsTEGNGvy2F2hmHRJYNRFAR+VsMUh8vbI7I+oppV6AnJ/W2a62JJT+aY1ym9PCcdJ5GEaTEmrdnSd7Yu0Ezs/u3ukwIfOBheviM4AJvi/AU3Hksv4bVUmKFNb3eBZGHsZUpLYmfs8CuMih8dNHe9Gv3Gx2xs0lS+b2TBsqPk8+u2HEE2zKestS7TpC4Z+qBUd1teIgp9UefVXCkPFgOy7xborvv3gJNH/2Nza3FY21quLxNeOBjdPg9yT0HnOLX8Pzarytcltphalr9kDnu6uVxsoqygPb25wmuUbF+c3zIIJRADX2hNAw1GRhzJUEbkU4C7WWobVvyzVUJGdCLMZ5sm/SO3BOWXzS2opCHlVOHoug==</X_EncInfo> </u:X_EncryptedCommand> </s:Body> </s:Envelope>',
    headers: {
      Accept: 'text/xml',
      'Content-Type': 'text/xml; charset="utf-8"',
      Host: '192.168.1.13:55000',
      SOAPACTION: '"urn:panasonic-com:service:p00NetworkControl:1#X_EncryptedCommand"',
      'Cache-Control': 'no-cache',
      Pragma: 'no-cache',
      'User-Agent': 'axios/0.19.2',
      'Content-Length': 783
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'text',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(asyncId)]: 266169,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'POST /nrc/control_0 HTTP/1.1\r\n' +
      'Accept: text/xml\r\n' +
      'Content-Type: text/xml; charset="utf-8"\r\n' +
      'Host: 192.168.1.13:55000\r\n' +
      'SOAPACTION: "urn:panasonic-com:service:p00NetworkControl:1#X_EncryptedCommand"\r\n' +
      'Cache-Control: no-cache\r\n' +
      'Pragma: no-cache\r\n' +
      'User-Agent: axios/0.19.2\r\n' +
      'Content-Length: 783\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    path: '/nrc/control_0',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://192.168.1.13:55000/nrc/control_0',
      redirects: [],
      [Symbol(kCapture)]: false
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 783,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://192.168.1.13:55000/nrc/control_0',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      host: [Array],
      soapaction: [Array],
      'cache-control': [Array],
      pragma: [Array],
      'user-agent': [Array],
      'content-length': [Array]
    }
  },
  response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: {
      'content-length': '488',
      'content-type': 'text/xml; charset="utf-8"',
      ext: '',
      server: 'Panasonic-VIErA/1, UPnP/1.0, Panasonic MIL DLNA SERVER',
      connection: 'close'
    },
    config: {
      url: 'http://192.168.1.13:55000/nrc/control_0',
      method: 'post',
      data: '<?xml version="1.0" encoding="utf-8"?> <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <s:Body> <u:X_EncryptedCommand xmlns:u="urn:panasonic-com:service:p00NetworkControl:1"> <X_ApplicationId>ARSPkwxN6aQCoQ==</X_ApplicationId> <X_EncInfo>70u0Z1POfJIP+OzjLkmiFDZcsAdcd7IcbAX1+vqeEsTEGNGvy2F2hmHRJYNRFAR+VsMUh8vbI7I+oppV6AnJ/W2a62JJT+aY1ym9PCcdJ5GEaTEmrdnSd7Yu0Ezs/u3ukwIfOBheviM4AJvi/AU3Hksv4bVUmKFNb3eBZGHsZUpLYmfs8CuMih8dNHe9Gv3Gx2xs0lS+b2TBsqPk8+u2HEE2zKestS7TpC4Z+qBUd1teIgp9UefVXCkPFgOy7xborvv3gJNH/2Nza3FY21quLxNeOBjdPg9yT0HnOLX8Pzarytcltphalr9kDnu6uVxsoqygPb25wmuUbF+c3zIIJRADX2hNAw1GRhzJUEbkU4C7WWobVvyzVUJGdCLMZ5sm/SO3BOWXzS2opCHlVOHoug==</X_EncInfo> </u:X_EncryptedCommand> </s:Body> </s:Envelope>',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      responseType: 'text',
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'POST /nrc/control_0 HTTP/1.1\r\n' +
        'Accept: text/xml\r\n' +
        'Content-Type: text/xml; charset="utf-8"\r\n' +
        'Host: 192.168.1.13:55000\r\n' +
        'SOAPACTION: "urn:panasonic-com:service:p00NetworkControl:1#X_EncryptedCommand"\r\n' +
        'Cache-Control: no-cache\r\n' +
        'Pragma: no-cache\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Content-Length: 783\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      path: '/nrc/control_0',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '<?xml version="1.0" encoding="utf-8"?>\n' +
      '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">\n' +
      ' <s:Body>\n' +
      '  <s:Fault>\n' +
      '   <faultcode>s:Client</faultcode>\n' +
      '   <faultstring>UPnPError</faultstring>\n' +
      '   <detail>\n' +
      '    <UPnPError xmlns="urn:schemas-upnp-org:control-1-0">\n' +
      '     <errorCode>612</errorCode>\n' +
      '     <errorDescription>No such session</errorDescription>\n' +
      '    </UPnPError>\n' +
      '   </detail>\n' +
      '  </s:Fault>\n' +
      ' </s:Body>\n' +
      '</s:Envelope>\n'
  },
  isAxiosError: true,
  toJSON: [Function (anonymous)]
}

**Comment by AntonioMeireles** [comment]
Hi again. 

**THANKS** for reporting! I'm making progresses in my callback handling refactoring which _en passant_ should make understanding and dealing this kind of errors way more simple. i hope to have something releasable and (crossing fingers) without major regressions later this week. 

All the best, 

António

**Comment by koupus** [comment]
No problem and many thanks for your (great) work!

**Comment by AntonioMeireles** [comment]
@koupus 

can you give please a try to latest tip (it's tagged but yet unpublished in npm) ? (npm i "github:AntonioMeireles/homebridge-vieramatic#28ff0fc")

thanks in advance!

**Comment by koupus** [comment]
Hello Antonio, new test yesterday and it's OK for me, no bug!!! Thanks !!!!
