### ISSUE TITLE
Prompted for Homekit Setup Code when adding accessing to Apple 'Home'

### ISSUE THREAD

**Issue by tallguy999** [AntonioMeireles/homebridge-vieramatic#61]
Hi,
I've successfully installed the plugin and can power my TV on and off from the Homebridge UI, however if I try to add the TV to the Apple 'Home' app, I'm being prompted 'Enter HomeKit Setup Code'? (Or 'Use Camera'). Is that to be expected? If so, can you advise what number/code I should be using? 

My TV is a 2015 TX-50CX680B.

Thanks,

Steve
![Screenshot 2021-01-21 at 20 55 45](https://user-images.githubusercontent.com/57621544/105412045-170d5c00-5c2c-11eb-8ff4-dcc954610663.png)
![Screenshot 2021-01-21 at 20 55 07](https://user-images.githubusercontent.com/57621544/105412051-18d71f80-5c2c-11eb-89e5-30b2479e9726.png)

**Comment by tallguy999** [comment]
Television	
Active	1
Active Identifier	0
Configured Name	50CX680_Series
Remote Key	
Sleep Discovery Mode	1
Power Mode Selection	
Manufacturer	Panasonic
Model	Panasonic VIErA TX-50CX680B
Name	50CX680_Series
Serial Number	4D454930-0200-1000-8001-A8137441B307
Firmware Revision	2.0.16
Homebridge Instance IP	192.168.1.113
Homebridge Instance Port	37451
Homebridge Instance Username	11:9B:0F:CF:7A:6E
aid	1
iid	8

**Comment by tallguy999** [comment]
Oooops - Schoolboy error!

**Comment by AntonioMeireles** [comment]
@tallguy999 

Welcome to the open source world as this seems your first ever issue 😄!

you should have the PIN in your homebridge boot logs. You can get it static by setting in your homebridge's 
`config.json`   inside the `"bridge"` block per snippet bellow
```
 "bridge": {
    "name": "homebridgeMobile",
    "username": "CC:22:3D:E3:CE:32",
    "port": 51827,
    "pin": "012-34-567",
    "bind": ["en0"]
  },```


All the best,
