### ISSUE TITLE
Can't retrieve authentication Tuple - it hangs for some reason

### ISSUE THREAD

**Issue by wlee88** [AntonioMeireles/homebridge-vieramatic#62]
**Describe your issue**
When trying to retrieve the authentication tuple for my tv (in my case the site is http://192.168.1.88:8973/) - the webpage simply hangs.

I've also tried `viera-pair [ip-address-of-tv]`
```
/homebridge # viera-pair 192.168.1.32
found a 'Panasonic VIErA' TV (TH-55FZ950U) at '192.168.1.32' (requires crypto for comunication).
```
I've attached my homebridge log - not sure if that helps

**Issue Context**

[homebridge.log](https://github.com/AntonioMeireles/homebridge-vieramatic/files/5872864/homebridge.log)
config.json
```
{
    "bridge": {
        "name": "Homebridge 6343",
        "username": "0E:16:D1:4D:63:43",
        "port": 53978,
        "pin": "031-45-154"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8888,
            "platform": "config"
        },
        {
            "tvs": [
                {
                    "ipAddress": "192.168.1.32",
                    "hdmiInputs": [
                        {
                            "id": "1",
                            "name": "Playstation 5"
                        },
                        {
                            "id": "2",
                            "name": "AppleTV"
                        }
                    ],
                    "disabledAppSupport": false,
                    "customVolumeSlider": false
                }
            ],
            "platform": "PanasonicVieraTV"
        }
    ],
    "accessories": []
}

```

I run this on a qnap NAS (followed these instructions and have the latest version of homebridge https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-QNAP)

I have a 2018 viera `55FZ950_series` connected via wifi. I'm wondering if there's a firewall port i need to open which i'm missing?

**Comment by AntonioMeireles** [comment]
@wlee88 

hi!

you need to have port `8973` **binded** to the outside in the homebridge container. that will fix the `http://192.168.1.88:8973/` hanging part. OTOH from where are you running the `viera-pair` command ? from inside the homebridge container or from qnap host ?

thanks for your patience!

**Comment by wlee88** [comment]
thanks for the reply @AntonioMeireles!

the homebridge container is configured to `host` meaning it should have access to all ports.
I ran the `viera-pair` command via the homebridge UI (from http://192.168.1.88:8888/)

**Comment by wlee88** [comment]
nvm - thanks again for your help on this - i just wasted your time. i ran it locally on my pc and it worked. 
Definitely a QNAP/docker/ports configuration issue.
