### ISSUE TITLE
TX-49EX600B not working whatsoever since version 2.0.15

### ISSUE THREAD

**Issue by rickt42uk** [AntonioMeireles/homebridge-vieramatic#69]
**Describe your issue**
Since version 2.0.15, I have been unable to use the plugin with my TV. It doesn't show up in the Home app, or in the Accessories section in homebridge-config-ui-x
I've tested several newer versions and none have worked

**Issue Context**
For context / fair testing, I've set up a fresh homebridge instance. I've also tried removing and reinstalling on my main homebridge server, and completely removing the accessory using homebridge-config-ui-x

**Error in Log**
```
 [3/3/2021, 8:28:41 AM] [PanasonicVieraTV] found a 'Panasonic VIErA' TV (TX-49EX600B) at '192.168.1.68' .
 
 (node:19448) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toFixed' of undefined
     at visibility (/usr/local/lib/node_modules/homebridge-vieramatic/src/accessory.ts:342:21)
     at VieramaticPlatformAccessory.configureInputSource (/usr/local/lib/node_modules/homebridge-vieramatic/src/accessory.ts:373:20)
     at new VieramaticPlatformAccessory (/usr/local/lib/node_modules/homebridge-vieramatic/src/accessory.ts:267:10)
     at VieramaticPlatform.deviceSetup (/usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:207:14)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
     at /usr/local/lib/node_modules/homebridge-vieramatic/src/platform.ts:59:23
 (Use `node --trace-warnings ...` to show where the warning was created)
 (node:19448) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
 (node:19448) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
``` 

**Minimal Config**
```json
{
    "tvs": [
        {
            "friendlyName": "Test",
            "ipAddress": "192.168.1.68",
            "disabledAppSupport": false,
            "customVolumeSlider": false
        }
    ],
    "platform": "PanasonicVieraTV"
}

```
**Thank you**
Even if I'm forever stuck on version 2.0.15, thank you so much for all your hard effort in creating this fantastic plugin.

**Comment by AntonioMeireles** [comment]
Hi, 

first let me thank you for your kind words. 

i think i know what the issue is, but unsure how it happened. somehow your `vieramatic.json` seems to have gotten got in a state that messes with late releases of he plugin.

please attach here its full contents. it's in `accessories/vieramatic.json` [path relative to the dir where your homebridge `config.json` is placed]. That should be enough for me to fix it in order for never happen to anyone again. 

after that if you remove that `accessories/vieramatic.json` file and restart homebridge with current plugin iteration, hopefully everything will work out of the box again. 


Thanks again for your patience

**Comment by AntonioMeireles** [comment]
@rickt42uk 

please just update to just published `homebridge-vieramatic@3.1.1` restart homebridge and report back. if i'm right will fix your issue without you having to do any further action. 

thanks again!

**Comment by rickt42uk** [comment]
Hi there.

Unfortunately I didn't see your last message so I removed /var/lib/homebridge/accessories/vieramatic.json, and the config and then upgraded to version 3.1.1. Having re-added the config, everything is now working perfectly.

However, here is the vieramatic.json:
`{
	"4D454930-0200-1000-8001-D8AFF1B055AB": {
		"data": {
			"inputs": {
				"hdmi": [{
					"id": "1",
					"name": "Apple TV",
					"hiden": 0
				}],
				"applications": {
					"0": {
						"name": "Apps Market",
						"id": "0387878700000102",
						"hiden": 1
					},
					"1": {
						"name": "Netflix",
						"id": "0010000200000001",
						"hiden": 1
					},
					"2": {
						"name": "Freeview Play",
						"id": "0387878700000109",
						"hiden": 1
					},
					"3": {
						"name": "Cinema",
						"id": "0020002A00000001",
						"hiden": 1
					},
					"4": {
						"name": "VIERA Link",
						"id": "0387878700000016",
						"hiden": 1
					},
					"5": {
						"name": "Calendar",
						"id": "0387878700150020",
						"hiden": 1
					},
					"6": {
						"name": "Browser",
						"id": "0077777700160002",
						"hiden": 1
					},
					"7": {
						"name": "Amazon Prime Video",
						"id": "0010000100170001",
						"hiden": 1
					},
					"8": {
						"name": "BBC iPlayer",
						"id": "0020000A00170010",
						"hiden": 1
					},
					"9": {
						"name": "ITV Hub",
						"id": "0387878700000124",
						"hiden": 1
					},
					"10": {
						"name": "All 4",
						"id": "0387878700000125",
						"hiden": 1
					},
					"11": {
						"name": "My5",
						"id": "0020009300000002",
						"hiden": 1
					},
					"12": {
						"name": "YouTube",
						"id": "0070000200170001",
						"hiden": 1
					},
					"13": {
						"name": "Recorded TV",
						"id": "0387878700000013",
						"hiden": 1
					},
					"14": {
						"name": "BBC News",
						"id": "0020000A00170006",
						"hiden": 1
					},
					"15": {
						"name": "BBC Sport",
						"id": "0020000A00170007",
						"hiden": 1
					},
					"16": {
						"name": "AccuWeather.com",
						"id": "0070000C00000001",
						"hiden": 1
					},
					"17": {
						"name": "CHILI",
						"id": "0020004700000001",
						"hiden": 1
					},
					"18": {
						"name": "STV Player",
						"id": "0387878700000132",
						"hiden": 1
					},
					"19": {
						"name": "Digital Concert Hall",
						"id": "0076002307170001",
						"hiden": 1
					},
					"20": {
						"name": "My App",
						"id": "0387878700000130",
						"hiden": 1
					},
					"21": {
						"name": "Plex",
						"id": "0076010507000001",
						"hiden": 1
					},
					"22": {
						"name": "BritBox UK",
						"id": "0020013200000001",
						"hiden": 1
					}
				},
				"TUNER": {
					"hiden": 0
				}
			},
			"specs": {
				"friendlyName": "TV",
				"modelName": "Panasonic VIErA",
				"modelNumber": "TX-49EX600B",
				"manufacturer": "Panasonic",
				"serialNumber": "4D454930-0200-1000-8001-D8AFF1B055AB",
				"requiresEncryption": false
			},
			"ipAddress": "192.168.1.68"
		}
	}
}`

I hope that helps confirm that the issue is what you thought. 

Again, I've been using this plugin pretty much since it launched and it's been utterly fantastic.

**Comment by AntonioMeireles** [comment]
ok. Thanks. this should no be fixed for real. will close. feel free to bug me again if somehow issue resurrects or if you have any other issue or feature suggestion!

thanks again for your kind words and glad you find the plugin handy! (if you have the means - just spread the word about it :-) ) 

All the best, 

António
