### ISSUE TITLE
Warning / Error in logs when restarting Homebridge

### ISSUE THREAD

**Issue by Seexelas** [AntonioMeireles/homebridge-vieramatic#70]
#### **Describe your issue**

When restarting homebridge, i get an warning and a error

#### **Issue Context**

Please add the following items, when applicable:

1. :
---------------------------------------------------------------------------------------------------
```
[08/03/2021, 08:23:28] [PanasonicVieraTV] WARNING: unable to fetch specs from TV at '192.168.1.10'. Using the previously cached ones: 

{
  friendlyName: 'Galaxy-PanasonicTV',
  manufacturer: 'Panasonic',
  modelName: 'Panasonic VIErA',
  modelNumber: 'TX-65GZ2000E',
  requiresEncryption: true,
  serialNumber: 'XXXXXXXXXXXXXXXXXX'
}
[08/03/2021, 08:23:28] [PanasonicVieraTV] IGNORING '192.168.1.10' as we do not support offline initialization,  from cache, for models that require encryption.
```
--------------------------------------------------------------------------------------------------
2. your homebridge's `config.json` contents : 
```json
"tvs": [
        {
            "friendlyName": "Galaxy-PanasonicTV",
            "encKey": "XXX",
            "hdmiInputs": [
                {
                    "name": "HDMI - 1",
                    "id": "1"
                },
                {
                    "name": "HDMI - 2",
                    "id": "2"
                },
                {
                    "name": "HDMI - 3",
                    "id": "3"
                },
                {
                    "name": "HDMI - 4",
                    "id": "4"
                }
            ],
            "customVolumeSlider": true,
            "appId": "ATpeJrgn67YCjg==",
            "ipAddress": "192.168.1.10"
        }
    ],
    "platform": "PanasonicVieraTV"
}
```
3. the contents of `accessories/vieramatic.json` (path is relative to homebridge's _datadir_)
4. Details about your specific homebridge setup
    - hardware and arch : Raspb 3
    - Operating System and its version : Raspbian GNU/Linux Buster (10)
    - NodeJS version : v14.15.5
    - Homebridge version : 1.3.2
    - specific vieramatic version being used
    - Viera TV(s) model(s) being used (and connectivity type being used - wired or wireless) : GZ2000 - Wireless
    
5. anything else you may find relevant

Thanks for the help,

**Comment by AntonioMeireles** [comment]
humm.... 
thanks for reporting. two quick questions ?

a) and **when** that happens the TV is **not** powered off (from the wall), right ?
b) is this a recent issue, i.e wasn't happening before ? (if TV is NOT powered off)  

thanks in advance 

António

**Comment by Seexelas** [comment]
It's the first time I saw it. 

Tv in standby and plugged all the time.

**Comment by AntonioMeireles** [comment]
strange. some more debugging:

a) no power saving features in your wireless router / AP right ? 
b) could you check TV's network settings and confirm that it  hasn't lost IP i.e. that it has a valid IP lease?. 
c) if issue persists could you try to connect TV to wired network and see if it goes away ?


thanks again for your patience!

**Comment by AntonioMeireles** [comment]
@Seexelas 

disregard questions above, for now. This may just be a side effect of a bug on my side. Just give a try to `homebridge-vieramatic@3.1.3` that i've just published and report . hopefully will get rid of this issue for real. 

Thanks!

**Comment by Seexelas** [comment]
So logs are clean. What is weird is the tv was declared not reachable for homebridge with no errors in logs...

I restarted the whole server, now it's working !

**Comment by AntonioMeireles** [comment]
@Seexelas 

so, your issue seems fixed, right ? will leave this open. feel free to close this issue as soon you're confident that it won't come back!

Thanks again for your patience!

**Comment by Seexelas** [comment]
It's working :) I'll come back to you if i have any issue, thanks for the support
