### ISSUE TITLE
This plugin slows down Homebridge

### ISSUE THREAD

**Issue by peezy45** [AntonioMeireles/homebridge-vieramatic#76]
Hey, 

I'm receiving this error with the newest version of the plugin and homebridge.
- Homebridge 1.3.4
- NodeJS: v14.16.1
- NPM v6.14.12

```
[4/14/2021, 8:55:43 AM] [homebridge-vieramatic] This plugin slows down Homebridge. The read handler for the characteristic 'Active' on the accessory 'Schlafzimmer Fernseher 2BCB' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[4/14/2021, 8:55:43 AM] [homebridge-vieramatic] Error: 
    at Accessory.sendCharacteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1874:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1431:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

Kind regards

**Comment by AntonioMeireles** [comment]
hi @peezy45 

thanks for reporting! AFAIK this may happen if/when you restart homebridge while the TV is off / in standby, and should be innoccuous. If it isn't - i.e. if somehow this implies that things won't work i.e. that TV won't power on / etc via homekit then it is a bug, otherwise just _cosmetic_ cruft 😄 

So, which case it is ? 

All the best, 

António

**Comment by peezy45** [comment]
Hey Antonio,

The result is that Homebridge successfully starts but TVs are not responding in the home app. Other Homebridge devices work as expected. 

Greetings

**Comment by AntonioMeireles** [comment]
> Hey Antonio,
> 
> The result is that Homebridge successfully starts but TVs are not responding in the home app. Other Homebridge devices work as expected.
> 
> Greetings

humm, that's sad ...so, we'll need a bit of additional data in order to try to id the root issue and fix it: 

- Please attach here the full homebridge's `config.json`
- Please attach here the full homebridge startup logs
- Please attach here contents of `accessories/vieramatic.json` (path is relative to where is homebridge's `config.json`) 
- Is this a new install ? if not what's the last version of the plugon that worked for you ?  
- The issue happens always ? or only if / when the TV is powered off ?

Thanks in advance!

António

**Comment by peezy45** [comment]
Hey, files are included in the zip file.
It's an old install, I just updated my homebridge and plugin version and it happens always, already tried to restart homebridge while tvs are both turned on. Didn't help
Already restart the whole docker container multiple times. Updated the container. Nothing helped

Greetings

Pascal

[Archiv.zip](https://github.com/AntonioMeireles/homebridge-vieramatic/files/6327234/Archiv.zip)

**Comment by AntonioMeireles** [comment]
ok... thanks!!!

2 ,5 quickies, for a start : 

- what's your specific TV model ? you also *anonymised* that ? [i care about the one that appears in the logs or in `vieramatic.json`] 

- could you please disable for a bit `homebridge-nuki`from your setup, restart homebridge,  and see if it fixes anything. `homebridge-nuki`is also popping (config) errors that may slow down homebridge enogh to trigger the issue you are hotting in my plugin. 

- (also with  `homebridge-nuki` disabled) could you please try to change in your homebridge's `config.json`  `"advertiser": "ciao"` =>  `"advertiser": "bonjour-hap"`, then restart homebridge and see if it matters ? 

Thanks once again for your patience!

**Comment by AntonioMeireles** [comment]
@peezy45 

also of note: 
-  your `vieramatic.json` only has data from one TV (and not the two that you have) which isn't supposed at all. could you also just delete it and restart homebridge and attach newly generated one please.
- your docker setup follows upsteams' recommendations [see [here](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Docker)], right  ? (namelly that the network mode is 'host' ?)

have a great weekend too!

**Comment by peezy45** [comment]
So I tried to disable nuki plugin - no change
changed the mdns advertiser - no change
tv models are  TX-49GXN938 and TX-65GZT1506.
docker container network is setup as host, yes 
I even completely removed the plugin and restored it but still no change. 
I removed your plugin for now cause the "not responding" devices in my home app really annoy me 😅

greetings mate

**Comment by AntonioMeireles** [comment]
> So I tried to disable nuki plugin - no change
> changed the mdns advertiser - no change
> tv models are TX-49GXN938 and TX-65GZT1506.
> docker container network is setup as host, yes
> I even completely removed the plugin and restored it but still no change.
> I removed your plugin for now cause the "not responding" devices in my home app really annoy me 😅
> 
> greetings mate


😢 could you do an experiment please ? have **only** a single TV configured in the plugin. restart homebridge and see please if issue persists. 

Thanks!

**Comment by peezy45** [comment]
Hello again, sorry for the late reply.

So I deleted the plugin including the persistent files and reinstalled it , now I can't even generate encryption keys anymore.
It just says the tv uses encrypted communication and cancels viera-pair command.
Could it be related to a software update of my tv's or something ? 

Greetings

**Comment by AntonioMeireles** [comment]
@peezy45 is this still happening to you

**Comment by AntonioMeireles** [comment]
closing per lack of reply. afaict this shouldn't be an issue anymore. if it is with recent versions of the plugin just reopen.
