### ISSUE TITLE
TV does not appear in Home App

### ISSUE THREAD

**Issue by tobias11-at** [AntonioMeireles/homebridge-vieramatic#77]
Unfortunately the TVs are only visible on Homebridge, but not in Home App.
Works fine on Homebridge and does what it is supposed to do.
Thanks.

**Comment by AntonioMeireles** [comment]
@tobias11-at 

seems to be a local issue, as things seem to work from homebridge's side. could you please try to remove your homebridge bridge from Home.app, restart homebridge, and then re-add it again (followed by the TV) to the home app, in order to check if that fixes it ?  

Thanks in advance and a great weekend!

**Comment by tobias11-at** [comment]
Thanks so far, but that did not change anything.
I wonder because all other plugins work - this one too, but not in home app ....

**Comment by AntonioMeireles** [comment]
@tobias11-at 

hi again ... 
so, after re-adding your homebridge bridge to **Home.app** when you go to '**Add Accessory**' (and select '**I Don't Have a Code or Cannot Scan**') the TV doesn't apear there, at all  ? could you atach please your homebridge logs please too. 

thanks again

**Comment by dirkmch** [comment]
I have the same problem. TVs are only visible on Homebridge, not available in HomeKit
I've uninstalled and reinstalled the plugin several times, but it doesn't work. The TV isn't available in HomeKit.

{
            "tvs": [
                {
                    "friendlyName": "Panasonic",
                    "ipAddress": "192.168.178.29",
                    "mac": "F4:69:42:29:28:53",
                    "encKey": "lrwPA+okefLLkZl8t1wZjw==",
                    "appId": "Ac4Z+9ymMt0bLQ==",
                    "hdmiInputs": [
                        {
                            "id": "2",
                            "name": "Amazon"
                        }
                    ],
                    "disabledAppSupport": false,
                    "customVolumeSlider": false
                }
            ],
            "platform": "PanasonicVieraTV",
            "_bridge": {
                "username": "0E:CF:B7:1A:F2:32",
                "port": 46019
            }
        }
    ],
    "disabledPlugins": []
}

**Comment by AntonioMeireles** [comment]
@dirkmch 
Hi!
**if** you disable the child bridge (and restart homebridge) things behave the same way ?
i.e. removing the following snippet from your config ...
```json
 "_bridge": {
                "username": "0E:CF:B7:1A:F2:32",
                "port": 46019
            } 
``` 

Also, could you attach here you homebridge logs ?

thanks in advance !

**Comment by dirkmch** [comment]
Hi, if you diasable the childbridge and restart the bridge i got the same issue:

{
            "tvs": [
                {
                    "friendlyName": "Panasonic",
                    "ipAddress": "192.168.178.29",
                    "mac": "F4:69:42:29:28:53",
                    "encKey": "lrwPA+okefLLkZl8t1wZjw==",
                    "appId": "Ac4Z+9ymMt0bLQ==",
                    "hdmiInputs": [
                        {
                            "id": "2",
                            "name": "Amazon"
                        }
                    ],
                    "disabledAppSupport": false,
                    "customVolumeSlider": false
                }
            ],
            "platform": "PanasonicVieraTV"
        }
    ],
    "disabledPlugins": []
}

**Comment by AntonioMeireles** [comment]
@dirkmch 

thanxs! logs plz.

**Comment by dirkmch** [comment]
Starting to advertise 'Homebridge 49D6 69A1' using bonjour-hap backend!
[26/05/2021, 11:44:12] Homebridge v1.3.4 (Homebridge 49D6) is running on port 51458.
[26/05/2021, 11:44:12] [PanasonicVieraTV] found a 'Panasonic VIErA' TV (TX-40HX800W) at '192.168.178.29' (requires crypto for communication).

[26/05/2021, 11:44:12] [PanasonicVieraTV] successfully loaded Panasonic
Preparing Advertiser for 'Panasonic 07F3' using bonjour-hap backend!
Starting to advertise 'Panasonic 07F3' using bonjour-hap backend!
[26/05/2021, 11:44:12] Panasonic 07F3 is running on port 36959.
[26/05/2021, 11:44:12] Please add [Panasonic 07F3] manually in Home app. Setup Code:

**Comment by AntonioMeireles** [comment]
OK. thanxs. now to debug further do please: 

a) attach here contents of `accessories/vieramatic.json`(path is relative to the directory where your homebridge config is). 
b) remove the `accessories/vieramatic.json` above and restart homebridge. does the issue persists ? if not please attach also the newly generated `accessories/vieramatic.json`. 
c) can you tell more about your specific setup ? arch/OS/node/homebridge version etc ?

thanks once again for your patience!

**Comment by dirkmch** [comment]
i solved it. the problem was (maybe) at the bridge i had many "childbriges" named Panasonic... I deleted all of them and reboot the server after that HomeKit showed me the TV. Thank very much and have a great day

**Comment by segundofdez** [comment]
Hi there,
same problem here. Works fine in homebridge, but not visible in home app:

{
    "tvs": [
        {
            "friendlyName": "Panasonic TV",
            "ipAddress": "192.168.1.142",
            "hdmiInputs": [
                {
                    "id": "1",
                    "name": "Apple TV"
                },
                {
                    "id": "2",
                    "name": "Onkyo"
                },
                {
                    "id": "3",
                    "name": "PSP 4"
                }
            ],
            "disabledAppSupport": false,
            "customVolumeSlider": false
        }
    ],
    "platform": "PanasonicVieraTV",
    "_bridge": {
        "username": "...............(here is the number)",
        "port": 46906
    }
}

**Comment by AntonioMeireles** [comment]
closing per above.
