### ISSUE TITLE
Need to remove/re-add tv when adding HDMI inputs

### ISSUE THREAD

**Issue by yahms** [AntonioMeireles/homebridge-vieramatic#79]
#### **Describe your issue**

Not major issue, just wasn't immediately obvious to me, thought it was related to support of my tv / ie something specific to my tv (S610)

#### **Issue Context**

Previously I didnt use the input switching, (everything goes via an amp) so my hdmiInputs was []. for funsies i added them (ids 1 and 2), and in Apple Home app two new switches showed up immediately with the hdmi input's names i gave them, but were unable to do anything : they were stated by Apple Home as 'On' even though the tile was dark as if it was off.

I removed and re-added the TV from the home app and voila! they were there. Maybe worth making note in the docs?

Thanks!

**Comment by AntonioMeireles** [comment]
@yahms 

Hi, 

i'm not sure if this is a bug or just a caching / timing issue/"feature" on HomeKit part ... **if** after adding the inputs you - in IOS - force exit the home app and then load it again would things behave ? (without  readding the TV or restarting  homebridge). FWIW i'd expect things to behave if you just wait a bit more too. 

please report back if i'm wrong :-) as in that case i'll dig further (but will need your logs :-) ) 

Thanks in advance!

**Comment by yahms** [comment]
sure!

so i just removed my hdmi2 entry.

restarted homebridge and home app... and its gone. just HDMI1 and TVtuner in my list of inputs, and when i go deeper to look at the available inputs to show in the menu, theres no reference to my HDMI2 at all.

cool.

force exited home app, added hdmi2 to hb config, restarted homebridge. saw the message about adding hdmi2 in the logs, all good.

open home app, and still nope. just HDMI1 and TV tuner, and deeper in the TV config in the home app, just HDMI1 then all the list of apps

**Comment by AntonioMeireles** [comment]
@yahms - do you have `homebridge-config-x` ? do thing appear right in its web UI ? 

could you please paste here your setup ? and tell more about your setup  please ?

**Comment by AntonioMeireles** [comment]
also paste please contents of `accessories/vieramatic.json` here too.

**Comment by yahms** [comment]
sure

homebridge running in docker on a syno nas.
i have homebridge-config-x running  v4.41.1 (pretty sure its latest)
heres the config for this plugin from my config

`
        {
            "tvs": [
                {
                    "ipAddress": "10.8.16.79",
                    "friendlyName": "Panasonic",
                    "hdmiInputs": [
                        {
                            "id": "1",
                            "name": "Apple TV"
                        },
                        {
                            "id": "2",
                            "name": "HDMI2"
                        }
                    ],
                    "disabledAppSupport": true,
                    "customVolumeSlider": false
                }
            ],
            "platform": "PanasonicVieraTV"
        }`

accessories / veiramatic.json is this:

`{"4D454930-0200-1000-8001-A813744DD5A2":{"data":{"inputs":{"hdmi":[{"id":"1","name":"Apple TV"},{"id":"2","name":"HDMI2"}],"applications":{"0":{"name":"Apps Market","id":"0387878700000062","hiden":1,"hidden":1},"1":{"name":"Screen Market","id":"0387878700000064","hiden":1,"hidden":1},"2":{"name":"Media Player","id":"0387878700000032","hiden":1,"hidden":1},"3":{"name":"Media Server","id":"0387878700000014","hiden":1,"hidden":1},"4":{"name":"Mirroring","id":"0387878700000049","hiden":1,"hidden":1},"5":{"name":"USB Sharing","id":"0387878700000015","hiden":1,"hidden":1},"6":{"name":"Web Browser","id":"0077777700140002","hiden":1,"hidden":1},"7":{"name":"Netflix","id":"0010000200000001","hiden":1,"hidden":1},"8":{"name":"ABC iview","id":"0030000300000001","hiden":1,"hidden":1},"9":{"name":"SBS On Demand","id":"0076001906000001","hiden":1,"hidden":1},"10":{"name":"Digital Concert Hall","id":"0076002307000001","hiden":1,"hidden":1},"11":{"name":"YouTube","id":"0070000200000001","hiden":1,"hidden":1},"12":{"name":"Recorded TV","id":"0387878700000013","hiden":1,"hidden":1},"13":{"name":"TV Guide","id":"0387878700000003","hiden":1,"hidden":1},"14":{"name":"VIERA Link","id":"0387878700000016","hiden":1,"hidden":1},"15":{"name":"TV","id":"0387878700000001","hiden":1,"hidden":1},"16":{"name":"Main Menu","id":"0387878700000009","hiden":1,"hidden":1},"17":{"name":"AccuWeather.com","id":"0070000C00000001","hiden":1,"hidden":1},"18":{"name":"TuneIn","id":"0010001800000001","hiden":1,"hidden":1}},"TUNER":{"hiden":1,"hidden":0}},"specs":{"friendlyName":"Panasonic","manufacturer":"Panasonic","modelName":"Panasonic VIErA","modelNumber":"S610","requiresEncryption":false,"serialNumber":"4D454930-0200-1000-8001-A813744DD5A2"},"ipAddress":"10.8.16.79"}}}`

current status is hdmi1 aka Apple TV is showing as an input in home. but recently added 'HDMI2' isnt. am leaving it in this state tho i can easily reproduce steps to get here etc

let me know what you need :)

**Comment by AntonioMeireles** [comment]
in that regard `homebridge-config-x` UI lacking. 

inputs **should** land, sooner or later, in `Home.app` like ... 
<img width="500" alt="image" src="https://user-images.githubusercontent.com/743527/117995171-04cd4000-b339-11eb-8f47-74e8ceb925f5.png">

Are you running docker with host networking i.e. fully along [upstream docs](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Docker) ?

At sight things look sane   and changes shouyld just propagate...

**Comment by yahms** [comment]
yeah host networking on the docker. havent messed with the docker config, so should be as per the oznu docker tho i am using ubunti-no-avahi because ubuntu plays better with the ffmpeg camera plugin.

 atm in its current state, the inputs that existed in homebridge when I (re)added the TV to the Home App work as expected, like your screenshot above. but since adding the HDMI2 input, the Home app has only updated to have that non-functional switch (currently called HDMI2), which appeared after i added the hdmi2 input and restarted homebridge. its associated with the tv by default ( i set my TV to 'show as separate tiles' to split it out to its own tile) . that HDMI2 tile is grey in the Home app, but its 'On'.

![43829633-54C2-4D37-A321-A305CBDAC49F_1_201_a](https://user-images.githubusercontent.com/26289008/117997201-5a274280-b375-11eb-9306-450423b73862.jpeg)

![DDC84CD7-19DD-4FA7-A52A-2FE9CA75AED2](https://user-images.githubusercontent.com/26289008/117997234-61e6e700-b375-11eb-816b-3c1205b38aaf.png)


![E2824F30-9D81-40A6-BDF2-EF080EF8E0A0](https://user-images.githubusercontent.com/26289008/117997279-6a3f2200-b375-11eb-981c-89a88d21b6f3.png)

**Comment by yahms** [comment]
oh i really should have resized those screenshots

**Comment by AntonioMeireles** [comment]
what happens if you stop using `ubunti-no-avahi` ? same behaviour ?

**Comment by yahms** [comment]
Ah so a quick check , no changes, and the input is there in the right place - just seems to be a time delay for the Home app to update as you said

**Comment by AntonioMeireles** [comment]
@yahms 

thanks for the update. so ok to close this one ? or is there anything else still bugging you/not performing as it should :-) ?

**Comment by yahms** [comment]
close away :) worth documenting the behaviour still?

**Comment by AntonioMeireles** [comment]
Will close. AFAICT this is default/expected behaviour of Homekit. 

thanks again for your patience!
