### ISSUE TITLE
Not showing the Encryption Key

### ISSUE THREAD

**Issue by tony7288** [AntonioMeireles/homebridge-vieramatic#81]
I tried to use both Homebridge UI way and old fashion way to look for the key to setup Homekit
The HB found the TV but unable to show the Encryption Key

Log as below
```
[6/18/2021, 11:23:18 AM] [PanasonicVieraTV] found a 'Panasonic VIErA' TV (TH-55FX700H) at '192.168.1.50' (requires crypto for communication).

[6/18/2021, 11:25:18 AM] [PanasonicVieraTV] found a 'Panasonic VIErA' TV (TH-55FX700H) at '192.168.1.50' (requires crypto for communication).

[6/18/2021, 11:27:40 AM] [PanasonicVieraTV] found a 'Panasonic VIErA' TV (TH-55FX700H) at '192.168.1.50' (requires crypto for communication).
```

**Comment by AntonioMeireles** [comment]
hi @tony7288 

Could you please attach here your homebridge's `config.json` ?

Thanks in advance!

**Comment by tony7288** [comment]
sure , see attached
[config.json.zip](https://github.com/AntonioMeireles/homebridge-vieramatic/files/6677309/config.json.zip)

**Comment by AntonioMeireles** [comment]
Hi,

something odd going on in your setup. there's no TV defined in the config you sent. (and at some point there was otherwise you couldn't get the original log message) . Please set it up here (following this [steps]( https://github.com/AntonioMeireles/homebridge-vieramatic#the-old-fashioned-way)) and please get back with the outcome. 

Thanks!

**Comment by tony7288** [comment]
[config (1).json.zip](https://github.com/AntonioMeireles/homebridge-vieramatic/files/6677362/config.1.json.zip)

How about this?  I input via Homebridge UI

Try again still cannot look for the encryptiont key

/homebridge # viera-pair 192.168.1.50
found a 'Panasonic VIErA' TV (TH-55FX700H) at '192.168.1.50' (requires crypto for communication).

/homebridge #

**Comment by AntonioMeireles** [comment]
OK, things a bit clearer now. some questions: 
a) is the TV up when you run `viera-pair` ? if not, please turn it on.
b) what's your nodejs and  homebridge version ? and which host OS/Arch  ?

thnxs!

**Comment by tony7288** [comment]
a) is the TV up when you run viera-pair ? if not, please turn it on.
It is Power On

b) what's your nodejs and homebridge version ? and which host OS/Arch ?

Node.js Version | v12.16.3
Homebridge v1.3.4
QNAP NAS Container (OS | Alpine Linux (3.11.6))

**Comment by colombif** [comment]
Hello,

do You use the embeded process to generate the key ?
![1DC8ED02-ABCC-44EA-9661-6F25F5C96D27](https://user-images.githubusercontent.com/84316445/122593418-f07e1080-d065-11eb-8ccf-c30a70b19f06.jpeg)
![04B57E36-46E6-45FE-BEFB-52543685DEF2](https://user-images.githubusercontent.com/84316445/122593436-f673f180-d065-11eb-9633-e9d0515ae6a7.jpeg)

First time I don’t use it and generate the key with python…

**Comment by tony7288** [comment]
> Hello,
> 
> do You use the embeded process to generate the key ?
> ![1DC8ED02-ABCC-44EA-9661-6F25F5C96D27](https://user-images.githubusercontent.com/84316445/122593418-f07e1080-d065-11eb-8ccf-c30a70b19f06.jpeg)
> ![04B57E36-46E6-45FE-BEFB-52543685DEF2](https://user-images.githubusercontent.com/84316445/122593436-f673f180-d065-11eb-9633-e9d0515ae6a7.jpeg)
> 
> First time I don’t use it and generate the key with python…
> 
> @AntonioMeireles : can You move the note near the Authentication section ?

Yes, nothing come up and that's why i use old fashion way

**Comment by AntonioMeireles** [comment]
(sorry lag). 

@tony7288 the 'nothing come up' part may (should) be due to you not having the '8973' port open/reachable/mapped in your homebridge dockerfile. can you check, please ?

[still digging on this on my side, still]

thanks for your patience and a great weekend!

**Comment by tony7288** [comment]
> (sorry lag).
> 
> @tony7288 the 'nothing come up' part may (should) be due to you not having the '8973' port open/reachable/mapped in your homebridge dockerfile. can you check, please ?
> 
> [still digging on this on my side, still]
> 
> thanks for your patience and a great weekend!

@AntonioMeireles  I might not descible it clearly.  I am able to reach that port 8973 page.  Tried key in my TV's IP Address and  the page keep trying/loading after clicking the submit button.
That is why i fall back to use cmdlet viera-pair

I really appericate your plugin made for Panasonic TV and have a great weekend too

**Comment by AntonioMeireles** [comment]
things getting weirder. 

do you have an linux / mac  box  around ? if so could you install homebridge and the plugin on it. and just run `viera-pair` from it ? (fwiw at sight this a networking issue ...) btw - everything is in same vlan right ? (and wired or wireless ?)

**Comment by AntonioMeireles** [comment]
@tony7288 

you running homebridge container in `host` network mode, right ? (per [this](https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-QNAP#confirm-settings-are-correct))

**Comment by AntonioMeireles** [comment]
> Hello,
> 
> do You use the embeded process to generate the key ?
> ![1DC8ED02-ABCC-44EA-9661-6F25F5C96D27](https://user-images.githubusercontent.com/84316445/122593418-f07e1080-d065-11eb-8ccf-c30a70b19f06.jpeg)
> ![04B57E36-46E6-45FE-BEFB-52543685DEF2](https://user-images.githubusercontent.com/84316445/122593436-f673f180-d065-11eb-9633-e9d0515ae6a7.jpeg)
> 
> First time I don’t use it and generate the key with python…
> 
> @AntonioMeireles : can You move the note near the Authentication section ?

@colombif 

makes **absolute** sense. will look into that ... many thanks for suggesting it!

**Comment by tony7288** [comment]
> @tony7288
> 
> you running homebridge container in `host` network mode, right ? (per [this](https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-QNAP#confirm-settings-are-correct))

@AntonioMeireles Confirm the homebridge container is in "host" network mode
I had just installed homebridge in my macOS for testing 

good news is i am able to look up the key via testing platform on macOS

bad news is i used found key and appid input in my production Homebridge Container.  My Home App won't show the TV
even those i tried:
-restarted homebridge couple time
-remove homebridge is iOS and re-add

Here i can show some log
[6/20/2021, 2:08:37 AM] [PanasonicVieraTV] found a 'Panasonic VIErA' TV (TH-55FX700H) at '192.168.1.50' (requires crypto for communication).

[6/20/2021, 2:08:37 AM] [PanasonicVieraTV] successfully loaded Panasonic TV
Preparing Advertiser for 'Panasonic TV 8777' using ciao backend!
Starting to advertise 'Panasonic TV 8777' using ciao backend!
[6/20/2021, 2:08:37 AM] Panasonic TV 8777 is running on port 45005.
[6/20/2021, 2:08:37 AM] Please add [Panasonic TV 8777] manually in Home app. Setup Code: 845-62-514
[INFO] Adding RF Support to device 780f77fd6eed with type 279d
[6/20/2021, 2:08:37 AM] [Broadlink RM] [INFO] Discovered Broadlink RM3 Pro Plus (279d) at 192.168.1.122 (78:0f:77:fd:6e:ed)
[6/20/2021, 2:13:12 AM] [Homebridge UI] Terminal session ended.

**Comment by AntonioMeireles** [comment]
@tony7288 

ok, the good news (not to you) is that i'm innocent and this does not seem to be plugin's fault. OTOH that doesn't solve your issue at all. **still researching**. this is fundammentally a documentation issue - something needs to be set additionally on your docker setup so that communication occurs both ways. 

thanks once again for your patience!

**Comment by AntonioMeireles** [comment]
@tony7288 

just to confirm - if you load homebridge/the plugin on your mac - there everything works OK, right ? [just to fully exclude the TV from the trouble equation]

**Comment by tony7288** [comment]
@AntonioMeireles I do think it is not plugin's fault but i still not able to figure out why

I clone my config in my testing macOS and add in my Home app
Panasonic still not add in Home app but other accessories (Broadlink RM) are able to add in

Another bad news is...
I tried remove Homebridge in my Home app (my production container one), reboot my iOS, and re-add in my Home app
None accessories add just now (even my existing Broadlink RM accessories is not showing....) 
lmao

I might figure out on tomorrow (it is very night in my time zone)

But thanks for your advise.

**Comment by AntonioMeireles** [comment]
@tony7288 

just one note ... plugin is a `platform` one... which means that after you add the homebridge to home.app you need to _also_ **add** the TV itself. (needs to be that way - `platform` - as one user may have multiple TVs)

 good night!

**Comment by tony7288** [comment]
@AntonioMeireles Appreciate your help again.  I had changed my container network setting from host to bridge.  It seems resolved all issue. I finally able to power on and off TV from Home App and the status of power is in real time. 
It seems there is other port conflicts with my other containers. (i am still unsure)

**Comment by AntonioMeireles** [comment]
@tony7288 

great to hear! glad that you sorted it out. hope you enjoy and have gun using the plugin. feel fre to bug me again if you feel that something is not behaving as it should on my/plugin's side. 

All the Best, 

António
