### ISSUE TITLE
Panasonic ZT60

### ISSUE THREAD

**Issue by To-Azamat** [AntonioMeireles/homebridge-vieramatic#82]
Have an old ZT60 plasma, and looks like it does not support WOL as I don't see even related menu entries in setup.
Installed plugin with IP and MAC specified, all works ok except for turning on from standby. Also it looks like plugin can't reach TV in standby at all as I get these in log:
 ```
 [homebridge-vieramatic] This plugin slows down Homebridge. 
 The read handler for the characteristic 'Active' on the accessory 'Panasonic ZT60 867F' didn't respond at all!. 
 Please check that you properly call the callback!
 ```
Can I make this work somehow or should give up due to hardware restrictions?

Best regards!

**Comment by AntonioMeireles** [comment]
@To-Azamat 

hi!

there isn't much i can do here, since the TV doesn't do WOL, so formally the plugin is working as designed.  
Your best bet is to workaround the lack of WOL along the _trick_ documented [here](https://github.com/AntonioMeireles/homebridge-vieramatic#how-to-power-on-tv-on-very-old-unsupported-tv-sets) and just use HDMI-CEC. 

**if** that fails to work, then we may then have a real bug in the plugin. 

All the Best, 

António

**Comment by To-Azamat** [comment]
Thanks for prompt reply!
Nah, I have HB running on NAS in Docker, so no way I can connect that to TV.
Not a big problem actually, need turning off more then ON.
I assume I can safely ignore warnings about plugin not reaching TV and "slowing down HB"?


Best regards,
Sergey

**Comment by AntonioMeireles** [comment]
@To-Azamat 

yes, those warnings should be harmless. will close - feel free to bug me again if you have / need additional help / input :-) 

all the best, 

António

**Comment by tjm7844** [comment]
Not to revive a closed thread, but just wanted to mention that I also have a ZT60, and WOL does function (both through this plugin and a couple other apps I’ve used over the years).

The main caveat is that the TV has to be hardwired to the network.

A lot of other control issues exist for a set this old, so you still might be better off using CEC anyway though 🤷‍♂️

**Comment by To-Azamat** [comment]
Aye, thinks for info!
Do you have Networked Standby in TV Remote App Settings menu? I have only TV Remote. 
Except for turning on everything else works fine: off, apps, volume control.

**Comment by tjm7844** [comment]
In TV Remote App Settings, I’ve got “TV Remote App” and “Wake On Lan” both set to On.

**Comment by To-Azamat** [comment]
Ok. Your ZT60 is probably USA version, those had WOL. Mine is European without it. Guess will have to bite it )

**Comment by tjm7844** [comment]
Ah, yes, that would explain it. Sorry for the added confusion!
