### ISSUE TITLE
Latest update 3.1.24 won't update.

### ISSUE THREAD

**Issue by Marfre888** [AntonioMeireles/homebridge-vieramatic#84]
Hi,

For some reason, the latest (3.1.24) update that was pushed won't update on my Pi.

Just wondering if anyone else is experiencing this problem, or if it is just me..

Thanks

**Comment by AntonioMeireles** [comment]
@Marfre888 

Hi! great to hear from you again (even if due to wrong reasons :-) ) 

I need **way** more details...
can you give me some more context 
0. version you migrated from
1. the homebridge logs, up from starting until the bug popped up there.
2. your homebridge's `config.json` contents.
3. the contents of `accessories/vieramatic.json` (path is relative to homebridge's _datadir_)
4. Details about your specific homebridge setup
    - hardware (which exact pi ?)
    - Operating System and its version 
    - NodeJS version
    - Homebridge version
    - specific vieramatic version being used
    - Viera TV(s) model(s) being used (and connectivity type being used - wired or wireless)
5. anything else you may find relevant

All the best

**Comment by Marfre888** [comment]
Hi,

Firstly, I have nothing to complain, this plugin has to the one of the best if not the best I run..

Homebridge will shows I'm on 3.1.22 (which is what it was at before attempting to update)

1. No errors in log, plugin updates succesfully

2. `        {
            "tvs": [
                {
                    "friendlyName": "Upstairs Living Room Television",
                    "ipAddress": "192.168.1.15",
                    "mac": "60:02:B4:A0:F6:D4",
                    "hdmiInputs": [
                        {
                            "id": "1",
                            "name": "STB"
                        },
                        {
                            "id": "3",
                            "name": "Blu-ray Disc"
                        }
                    ],
                    "disabledAppSupport": false,
                    "customVolumeSlider": false
                }
            ],
            "_bridge": {
                "username": "0E:C2:D7:2A:14:C4",
                "port": 53154
            },
            "platform": "PanasonicVieraTV"
        },`

3. `{"4D454930-0200-1000-8001-20C6EBE0422D":{"data":{"inputs":{"applications":{"0":{"id":"0387878700000062","name":"Apps Market"},"1":{"id":"0387878700000064","name":"Screen Market"},"2":{"id":"0387878700000016","name":"VIERA Link"},"3":{"id":"0387878700000032","name":"Media Player"},"4":{"id":"0387878700000014","name":"Media Server"},"5":{"id":"0387878700000003","name":"TV Guide"},"6":{"id":"0077777700140002","name":"Web Browser"},"7":{"id":"0070000200000001","name":"YouTube","hidden":0},"8":{"id":"0020007100000001","name":"Meteonews TV"},"9":{"id":"0076002307000001","name":"Digital Concert Hall"},"10":{"id":"0010000100000001","name":"Amazon Prime Video","hidden":0},"11":{"id":"0020001200000001","name":"CineTrailer"},"12":{"id":"0020001000000001","name":"euronews"},"13":{"id":"0020007600000001","name":"Deezer"},"14":{"id":"0387878700000013","name":"Recorded TV"},"15":{"id":"0387878700000056","name":"my Stream"},"16":{"id":"0387878700000049","name":"Mirroring"},"17":{"id":"0020000600000001","name":"ARTE"},"18":{"id":"0010000200000001","name":"Netflix","hidden":0},"19":{"id":"0070000600000001","name":"Skype"},"20":{"id":"0387878700000009","name":"Main Menu"},"21":{"id":"0387878700000001","name":"TV"},"22":{"id":"0070000C00000001","name":"AccuWeather.com"}},"hdmi":[{"id":"1","name":"STB"},{"id":"3","name":"Blu-ray Disc"}],"TUNER":{"hidden":0}},"ipAddress":"192.168.1.15","specs":{"friendlyName":"Upstairs Living Room Television","manufacturer":"Panasonic","modelName":"Panasonic VIErA","modelNumber":"TX-47AS650E","requiresEncryption":false,"serialNumber":"4D454930-0200-1000-8001-20C6EBE0422D"}}}}
<html>
<body>


Raspbian GNU/Linux Buster (10)
--



</body>
</html>`

4.  Raspberry Pi 4B 2GB, Raspbian GNU/Linux Buster (10), NodeJS 14.17.6, Vieramatic 3.1.22, Panasonic TX-47AS650E.

5. It's never happened before ;)

**Comment by AntonioMeireles** [comment]
still lost. 

so `npm update homebridge-vieramatic` is not working ?  
`npm ls -g | grep viera` gives you what ?
`npm i  homebridge-vieramatic@3.1.24` changes anything ?

**Comment by AntonioMeireles** [comment]
btw .. 
when you start homebridge you should have something in its logas along ...

```
Initializing HAP-NodeJS v0.9.4...
[9/28/2021, 4:40:40 PM] Loaded config.json with 0 accessories and 2 platforms.
[9/28/2021, 4:40:40 PM] Loaded 0 cached accessories from cachedAccessories.
[9/28/2021, 4:40:40 PM] ---
[9/28/2021, 4:40:40 PM] Loaded plugin: homebridge-config-ui-x@4.41.2
[9/28/2021, 4:40:40 PM] Registering platform 'homebridge-config-ui-x.config'
[9/28/2021, 4:40:40 PM] ---
[9/28/2021, 4:40:40 PM] Loaded plugin: homebridge-vieramatic@3.1.24
[9/28/2021, 4:40:40 PM] Registering platform 'homebridge-vieramatic.PanasonicVieraTV'
[9/28/2021, 4:40:40 PM] ---
[9/28/2021, 4:40:40 PM] Loading 2 platforms...
[9/28/2021, 4:40:40 PM] [Config] Initializing config platform...

``` 

what's in your side ?

**Comment by Marfre888** [comment]
> npm ls -g | grep viera

`pi@homebridge:/var/lib/homebridge` $ sudo npm ls -g | grep viera
+-- homebridge-vieramatic@3.1.22`

`Initializing HAP-NodeJS v0.9.4...
[9/29/2021 22:03:45] Loaded config.json with 13 accessories and 9 platforms.
[9/29/2021 22:03:45] Loaded 0 cached accessories from cachedAccessories.
[9/29/2021 22:03:45] ---
[9/29/2021 22:03:49] Loaded plugin: homebridge-config-ui-x@4.41.2
[9/29/2021 22:03:49] Registering platform 'homebridge-config-ui-x.config'
[9/29/2021 22:03:52] ---
[9/29/2021 22:03:52] Loaded plugin: homebridge-vieramatic@3.1.22
`

**Comment by AntonioMeireles** [comment]
way odd. looks some sort of local issue. so `sudo npm i -g homebridge-vieramatic@3.1.24` errors ? or wont't update to 3.1.22 ?
could you plz do `sudo npm uni -g homebridge-vieramatic && sudo npm i homebridge-vieramatic` and report back?

**Comment by AntonioMeireles** [comment]
@Marfre888 

(curious) any new data on this ?

All the best, 

António

**Comment by Marfre888** [comment]
> way odd. looks some sort of local issue. so `sudo npm i -g homebridge-vieramatic@3.1.24` errors ? or wont't update to 3.1.22 ? could you plz do `sudo npm uni -g homebridge-vieramatic && sudo npm i homebridge-vieramatic` and report back?

Hi,

Very weird.. running 'sudo npm i -g homebridge-vieramatic@3.1.24' now installed it correctly whereas before I did not.

No clue at all what I have done to fix it..

Thanks for your help and continued maintenance of this plugin..

M
