### ISSUE TITLE
Can't update plugin to 3.2.4

### ISSUE THREAD

**Issue by Seexelas** [AntonioMeireles/homebridge-vieramatic#86]
Hello, I hope everything is good for you ?

Little problem : 

#### **Describe your issue**

I can't update to the last version 3.2.4

#### **Issue Context**
USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-vieramatic@latest

npm ERR! code Unknown system error -117
npm ERR! syscall lstat
npm ERR! path /home/pi/.npm/_cacache/content-v2/sha512/43/a7/16b32b3cf07a0f80068501551bd16a4f9343bc8937a2b11f4832acbd1bc01b3b8365a55927ae7412d37cf317d3c601680eddc8257ad3b756357f3fb573b4
npm ERR! errno -117
npm ERR! Unknown system error -117: Unknown system error -117, lstat '/home/pi/.npm/_cacache/content-v2/sha512/43/a7/16b32b3cf07a0f80068501551bd16a4f9343bc8937a2b11f4832acbd1bc01b3b8365a55927ae7412d37cf317d3c601680eddc8257ad3b756357f3fb573b4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-11-20T11_59_38_136Z-debug.log

Command failed. Please review log for details.

Details : 

OS | Raspbian GNU/Linux Buster (10)
-- | --
Node.js v16.13.0
Npm version v8.1.0

Just a question for a feature : 

Is it possible to have a input selector for image settings (pro1, pro2, true cinema etc) ? As my Tv was calibrated, I need to switch sometime depending of what type of content I'm looking. 

Thanks for the help, take care,

Alexis

**Comment by AntonioMeireles** [comment]
humm... 

a) `sudo -E -n npm update -g homebridge-vieramatic` _also_ fails ?
b) regarding your question about image settings changes, it would be trivial but afaict that isn't exposed from the Panasonic TV's API... Again if someone from Panasonic ever read this ... - a few extra hints about TVs API internals  and this plugin could be made perfect (and made the TVs even more competitive...)

**Comment by Seexelas** [comment]
With your command, it also fails :

npm ERR! code Unknown system error -117
npm ERR! syscall lstat
npm ERR! path /home/pi/.npm/_cacache/content-v2/sha512/43/a7/16b32b3cf07a0f80068501551bd16a4f9343bc8937a2b11f4832acbd1bc01b3b8365a55927ae7412d37cf317d3c601680eddc8257ad3b756357f3fb573b4
npm ERR! errno -117
npm ERR! Unknown system error -117: Unknown system error -117, lstat '/home/pi/.npm/_cacache/content-v2/sha512/43/a7/16b32b3cf07a0f80068501551bd16a4f9343bc8937a2b11f4832acbd1bc01b3b8365a55927ae7412d37cf317d3c601680eddc8257ad3b756357f3fb573b4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-11-20T14_06_17_495Z-debug.log

Thanks for the help :)

**Comment by Seexelas** [comment]
I rebooted the whole raspberry and it has updated... bref problem solved

**Comment by AntonioMeireles** [comment]
thanxs for the update!

All the best!
