### ISSUE TITLE
viera-pair error

### ISSUE THREAD

**Issue by 1rado1** [AntonioMeireles/homebridge-vieramatic#9]
Hi, I am getting following error, can you please help to debug?

```
pi@raspberrypi:~ $ sudo viera-pair xx.xx.xx.xx
An unexpected error happened while fetching TV metadata. Please do make sure that the TV is powered on and NOT in stand-by. 


'SyntaxError: Invalid regular expression: /<friendlyName>(?<found>...*)</friendlyName>/: Invalid group'
```

**Comment by AntonioMeireles** [comment]
hummm...  that's odd

some more data please: 
- what TV model do you have ?
- what node version ?
- which homebridge version ?
- and which homebridge-vieramatic is this with ?

Thanks in advance!

**Comment by 1rado1** [comment]
what TV model do you have ?
TX-55DX603E
what node version ?
v8.15.1
which homebridge version ?
0.4.50
and which homebridge-vieramatic is this with ?
@latest

**Comment by AntonioMeireles** [comment]
**THANKS**. can you provide please the output of `curl http://YOUR_TV_IP:55000/nrc/ddd.xml`

Thanks **again** for your patience!

**Comment by 1rado1** [comment]
Sure, here it is:
`<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:vli="urn:schemas-panasonic-com:vli" xmlns:viera="urn:schemas-panasonic-com:viera" xmlns:pxn="urn:schemas-panasonic-com:pxn">
  <specVersion><major>1</major><minor>0</minor></specVersion>
  <device>
    <deviceType>urn:panasonic-com:device:p00RemoteController:1</deviceType>
    <friendlyName>TV</friendlyName>
    <manufacturer>Panasonic</manufacturer>
    <modelName>Panasonic VIErA</modelName>
    <modelNumber>TX-55DX600EA</modelNumber>
    <UDN>uuid:4D454930-0200-1000-8001-D8AFF149DC1E</UDN>
    <viera:X_DMSUDN>uuid:4D454930-0000-1000-8001-D8AFF149DC1E</viera:X_DMSUDN>
    <viera:X_DMRUDN>uuid:4D454930-0100-1000-8001-D8AFF149DC1E</viera:X_DMRUDN>
    <viera:X_NRCUDN>uuid:4D454930-0200-1000-8001-D8AFF149DC1E</viera:X_NRCUDN>
    <vli:X_MHC_DEVICE_ID>3238052562207156</vli:X_MHC_DEVICE_ID>
    <viera:X_VERSION>NRC-3.00</viera:X_VERSION>
    <viera:X_DEVICE_TYPE>DTV</viera:X_DEVICE_TYPE>
    <viera:X_KEY_TYPE>PAL-41,PAL-21,PAL-1</viera:X_KEY_TYPE>
    <viera:X_PAD_TYPE>15-1</viera:X_PAD_TYPE>
    <viera:X_NRC_ID>D8AFF149DC1E</viera:X_NRC_ID>
    <viera:X_NRCCAP>VR_POWER,VR_DMR,VR_DMS,VR_VECTOR,VR_BROWSER,VR_VCTRL,VR_LAUNCH,VR_RECDMS,VR_TUNERDMS,VR_MEDIADMS,VR_LVDMS,VR_VGADMS,VR_UPDMS,VR_TUNER1,VR_WOL,VR_OWNPLAY,VR_XRC,VR_MES,VR_UPBROWSER,VR_MC</viera:X_NRCCAP>
    <iconList>
      <icon>
        <mimetype>image/png</mimetype>
        <width>48</width>
        <height>48</height>
        <depth>24</depth>
        <url>/nrc/dlna_icon_48.png</url>
      </icon>
      <icon>
        <mimetype>image/png</mimetype>
        <width>120</width>
        <height>120</height>
        <depth>24</depth>
        <url>/nrc/dlna_icon_120.png</url>
      </icon>
      <icon>
        <mimetype>image/jpeg</mimetype>
        <width>48</width>
        <height>48</height>
        <depth>24</depth>
        <url>/nrc/dlna_icon_48.jpg</url>
      </icon>
      <icon>
        <mimetype>image/jpeg</mimetype>
        <width>120</width>
        <height>120</height>
        <depth>24</depth>
        <url>/nrc/dlna_icon_120.jpg</url>
      </icon>
    </iconList>
    <serviceList>
      <service>
        <serviceType>urn:panasonic-com:service:p00NetworkControl:1</serviceType>
        <serviceId>urn:upnp-org:serviceId:p00NetworkControl</serviceId>
        <SCPDURL>/nrc/sdd_0.xml</SCPDURL>
        <controlURL>/nrc/control_0</controlURL>
        <eventSubURL>/nrc/event_0</eventSubURL>
      </service>
    </serviceList>
  </device>
</root>`

Thank you!

**Comment by AntonioMeireles** [comment]
@1rado1 

can you give please a try to latest tip (it's tagged but yet unpublished in npm) ? (`npm i "github:AntonioMeireles/homebridge-vieramatic#28ff0fc"`)

thanks in advance!

**Comment by 1rado1** [comment]
Hi,

`npm ERR! code 128
npm ERR! Command failed: /usr/bin/git submodule update -q --init --recursive
npm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-bc68bc8e': Operace zamítnuta
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-12T22_07_49_064Z-debug.log
`

**Comment by 1rado1** [comment]
@AntonioMeireles 
Now getting this:
```
0|homebridge  | Error: The requested platform 'PanasonicVieraTV' was not registered by any plugin.
0|homebridge  |     at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:134:13)
0|homebridge  |     at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:327:45)
0|homebridge  |     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
0|homebridge  |     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
0|homebridge  |     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
0|homebridge  |     at Module._compile (module.js:653:30)
0|homebridge  |     at Object.Module._extensions..js (module.js:664:10)
0|homebridge  |     at Module.load (module.js:566:32)
0|homebridge  |     at tryModuleLoad (module.js:506:12)
0|homebridge  |     at Function.Module._load (module.js:498:3)
0|homebridge  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:27:21)
0|homebridge  |     at Module._compile (module.js:653:30)
0|homebridge  |     at Object.Module._extensions..js (module.js:664:10)
0|homebridge  |     at Module.load (module.js:566:32)
0|homebridge  |     at tryModuleLoad (module.js:506:12)
0|homebridge  |     at Function.Module._load (module.js:498:3)
0|homebridge  |     at Function.Module.runMain (module.js:694:10)
0|homebridge  |     at startup (bootstrap_node.js:204:16)
0|homebridge  |     at bootstrap_node.js:625:3
```

**Comment by AntonioMeireles** [comment]
(sorry lag) . can't reproduce atm (on the road). just install latest version published in npm (v0.5.82)

**Comment by 1rado1** [comment]
No problem, thank you for your support!
Unfortunately the issue is still there:
```
An unexpected error happened while fetching TV metadata. Please do make sure that the TV is powered on and NOT in stand-by. 


'SyntaxError: Invalid regular expression: /<friendlyName>(?<found>...*)</friendlyName>/: Invalid group'
```
It is very strange, just fyi TV is on the same VLAN as rpi, there is no firewall issue

**Comment by AntonioMeireles** [comment]
can you retry with  **`homebridge-vieramatic@0.5.83`** (just out) and report back please. 

And thanks again for your patience!

**Comment by 1rado1** [comment]
Hi, unfortunately still same error:
```
An unexpected error happened while fetching TV metadata. Please do make sure that the TV is powered on and NOT in stand-by. 


'SyntaxError: Invalid regular expression: /<friendlyName>(?<found>.*)</friendlyName>/: Invalid group'
```

**Comment by AntonioMeireles** [comment]
*this is odd*. what timezone are you on ? available for a sort of "live debug session"?

**Comment by 1rado1** [comment]
It is, hopefully I am not doing something wrong. Sure I am, Central Europe

**Comment by AntonioMeireles** [comment]
can you please apply the patch bellow locally and report back the viera-pair output ?
```
diff --git a/lib/viera.coffee b/lib/viera.coffee
index 73f429a..0d1350f 100644
--- a/lib/viera.coffee
+++ b/lib/viera.coffee
@@ -12,6 +12,7 @@ axios.default.timeout = 1000
 defaultAudioChannel = '<InstanceID>0</InstanceID><Channel>Master</Channel>'

 findValue = (xml, tag) ->
+  @log.debug(xml, tag)
   new RegExp("<#{tag}>(?<found>.*)</#{tag}>", 'gmu').exec(xml)?.groups?.found

 class Viera
@@ -384,6 +385,7 @@ class Viera
       .get("#{@baseURL}/nrc/ddd.xml")
       .then((r) ->
         {
+          @log.debug(r.data)
           friendlyName: findValue(r.data, 'friendlyName'),
           modelName: findValue(r.data, 'modelName'),
           modelNumber: findValue(r.data, 'modelNumber'), 
```

**Comment by 1rado1** [comment]
No problem, I really appreciate your support within this issue. 
Just note, I am a beginner and my linux skills are week, I have never done applying patches and so on, so please can you guide me more deeply how to apply? Sorry for this :-(

**Comment by AntonioMeireles** [comment]
edit `homebridge-vieramatic/lib/viera.coffee` under homebridge plugins dir and then mod lines 14/15 and 386/387 per patch manually if you prefer :-)

**Comment by AntonioMeireles** [comment]
and XXXL thanks for your patience!

**Comment by AntonioMeireles** [comment]
btw - looking back i just realized that your node version is a bit old. any chance of you getting/testing over a newer (not 8.x) one ?

**Comment by 1rado1** [comment]
Thank you very much, I am on it to edit, just having some issues (with code and with kids :-)), so please be patient.
Regarding node, I probably can, Ive been messing with it lately, but found this version most reliable. Which one do you recommend to go with?

**Comment by AntonioMeireles** [comment]
latest LTS (12.16.0 atm).

**Comment by AntonioMeireles** [comment]
well, after googling a bit it seems that named capture groups in regexps are **only** supported in node 10.x and newer... that may explain it :-) (but confirm plz)

**Comment by 1rado1** [comment]
Thank you for all the info!
You are totally right, only upgrade to node 10.4.1 made it work.. BUT :-) found another issue/s
Seems like no HDMI inputs found:
```
found a Panasonic VIErA TV (TX-55DX600EA) at xx.xx.xx.xx .

Please add the snippet bellow inside the 'platforms' array of your homebridge's 'config.json'
{
    "platform": "PanasonicVieraTV",
    "tvs": [
        {
            "ipAddress": "xx.xx.xx.xx",
            "hdmiInputs": []
        }
    ]
}

```
also getting this errors in home bridge log:
```
0|homebridge  | [2020-2-14 21:14:46] [PanasonicVieraTV] found a Panasonic VIErA TV (TX-55DX600EA) at xx.xx.xx.xx .
0|homebridge  | TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
0|homebridge  |     at Function.from (buffer.js:207:11)
0|homebridge  |     at Viera.deriveSessionKeys (/usr/lib/node_modules/homebridge-vieramatic/lib/viera.coffee:118:17)
0|homebridge  |     at Vieramatic.init (/usr/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:77:18)
0|homebridge  |     at process._tickCallback (internal/process/next_tick.js:68:7)

```
No accessory appeared

**Comment by AntonioMeireles** [comment]
ok. this is a new / different issue, post plz full homebridge log... it's breaking because it's trying to setup crypto and your model is oldish and doesn't have it.

**Comment by AntonioMeireles** [comment]
issue spotted. fix on the way. **THANKS** for catching it!

**Comment by AntonioMeireles** [comment]
just give a try plz to homebridge-vieramatic@0.5.85 and thanks again for your patience!

**Comment by 1rado1** [comment]
Thank you for update, just tried, issue still occurs 
Full error log:
```
[2020-2-14 21:45:46] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-config-ui-x' since we already loaded the same plugin from '/usr/lib/node_modules/homebridge-config-ui-x'.
[2020-2-14 21:45:46] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-vieramatic' since we already loaded the same plugin from '/usr/lib/node_modules/homebridge-vieramatic'.
[2020-2-14 21:45:54] Plugin /usr/lib/node_modules/homebridge-vieramatic requires Node version of >=10.17.0 which does not satisfy the current Node version of v10.4.1. You may need to upgrade your installation of Node.
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:207:11)
    at Viera.deriveSessionKeys (/usr/lib/node_modules/homebridge-vieramatic/lib/viera.coffee:118:17)
    at Vieramatic.init (/usr/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:77:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by AntonioMeireles** [comment]
humm. did you restart homebridge after updating plugin ?

**Comment by 1rado1** [comment]
Yes I did.
Here is the output:
```
0|homebridge  | [2020-2-14 11:16:46 PM] [PanasonicVieraTV] Viera {
0|homebridge  |   isReachable: [Function: bound isReachable],
0|homebridge  |   needsCrypto: [Function: bound needsCrypto],
0|homebridge  |   isTurnedOn: [Function: bound isTurnedOn],
0|homebridge  |   ipAddress: 'xx.xx.xx.xx',
0|homebridge  |   port: 55000,
0|homebridge  |   log:
0|homebridge  |    { [Function: bound ]
0|homebridge  |      debug: [Function],
0|homebridge  |      info: [Function],
0|homebridge  |      warn: [Function],
0|homebridge  |      error: [Function],
0|homebridge  |      log: [Function],
0|homebridge  |      prefix: 'PanasonicVieraTV' },
0|homebridge  |   _appId: null,
0|homebridge  |   _encKey: null,
0|homebridge  |   baseURL: 'http://xx.xx.xx.xx:55000',
0|homebridge  |   specs:
0|homebridge  |    { friendlyName: 'TV',
0|homebridge  |      modelName: 'Panasonic VIErA',
0|homebridge  |      modelNumber: 'TX-55DX600EA',
0|homebridge  |      manufacturer: 'Panasonic',
0|homebridge  |      serialNumber: '4D454930-0200-1000-8001-D8AFF149DC1E',
0|homebridge  |      requiresEncryption: false } }
```

**Comment by AntonioMeireles** [comment]
ok. thnxs! I "think" i've found the culprit but not sure. logic spaguetti :( . will get back to you tomorrow or later today!  (my fault really :( ) **have a great weekend**

**Comment by AntonioMeireles** [comment]
@1rado1 

try plz `homebridge-vieramatic@0.5.85`.

**Comment by 1rado1** [comment]
:-) logic spaguetti, no problem at all, I am glad for your great work and effort to solve the issue. 
Just **tried 0.5.86 and the error log is the same**, so no change. Maybe my old viera is really not compatible (I had a lot of troubles with other homebridge plugins - only one which works out of the box is `homebridge-panasonic-viera-tv`

**Comment by AntonioMeireles** [comment]
bah ... i'm missing something really obvious 😶... your tv not at fault afaict, not with this error. could you plz email me privately (address is in git commit logs) to try to setup a joint debug session? (i suspect the fix will end close to some one-liner)

All the best

**Comment by 1rado1** [comment]
or I do something terribly wrong :-).. nah, I think we (actually you :-)) figure this out soon. Sending email now

**Comment by AntonioMeireles** [comment]
@1rado1 

now, on the record, again **THANKS**

just got `homebridge-vieramatic@0.5.87` out. it's the same you tested minus debug marks. confirm please that there no more surprises and if so feel free to mark this issue as fixed closed :-) .

**Comment by 1rado1** [comment]
0.5.87 tested and works great! Thank you very much for your outstanding support! Closing this issue
