### ISSUE TITLE
TV wont appear in HomeKit

### ISSUE THREAD

**Issue by letszock** [AntonioMeireles/homebridge-vieramatic#94]
I have a 55FX720 TV I'm trying to add to my HomeBridge. I used the automatic setup, enter the pin code and the TV seems to be connected. I can controll my TV using the Homebridge Interface, but the TV wont show up in my HomeKit Apps (I mainly use the standard Apple Home App). When I press the + in the upper right corner and choose to add a device manually the TV shows up, but when I press it I get a promt asking me to enter a 8-digit code.

**Comment by AntonioMeireles** [comment]
@letszock 

it's the one you set in your homebridge config (**`pin`**). 
```json
 "bridge": {
   (...)
        "pin": "012-34-567",
     (...)
    },
   (...)
```

doesn't work for you ?

**Comment by letszock** [comment]
@AntonioMeireles 

Wow didnt even think of using that. It worked. Maybe you could add this to the installation guide?

**Comment by AntonioMeireles** [comment]
glad it's sorted. 

i will add it to the docs, albeit it's absolutelly standard homekit behaviour for platform accessories. 

will keep this open until docs updated. 

Other than this, plugin working up to your expectations ? if not just bug me and i'll see what can be done. 

All the best, 

António

**Comment by letszock** [comment]
Yeah I didnt know that as the only other plugins I've used are Hue and Xiaomi Vaccum. But I guess its good to know and will help save some other noobs like me some headaches. 

As I've not used it until now I can't say much about the plugin, but it looks good to me. Thanks for the headsup, but I hope I wont have to bug you again. 👍

**Comment by AntonioMeireles** [comment]
@letszock 

updated docs are in. **THANKS**!

> (...) but I hope I wont have to bug you again. (...)

Believe me, when i say that there are **three things absolutelly certain in life** - **death**, **taxes** and that **all software** (even the one written by me) **ends having bugs**.
