### ISSUE TITLE
Unable to install/upgrade 4.0.24 on HOOBS

### ISSUE THREAD

**Issue by jvhooijdonk** [AntonioMeireles/homebridge-vieramatic#95]
When I upgrade to version 4.0.24 on a Hoobs (RP4) the plugin in not installed/upgraded. I can install a lower version (4.0.23).
I get the following error when I upgrade to 4.0.24:

```**PanaBridgeConfiguration change
2/7/2022, 10:17:32 AMpanabridge stopping
2/7/2022, 10:17:37 AMPanaBridge starting
2/7/2022, 10:17:42 AMPanaBridgeERRORError loading plugin "homebridge-vieramatic"
2/7/2022, 10:17:42 AMPanaBridgeWARNINGNo plugins installed.
2/7/2022, 10:17:42 AMPanaBridgeLoading 1 platforms...
2/7/2022, 10:17:42 AMPanaBridgeBridge is running on port 51846.**
```
When I install 4.0.23 everthing works just fine.

**Comment by AntonioMeireles** [comment]
@jvhooijdonk 

thanks for reporting. is there any way to provide more complete logs ? (can you enable `DEBUG`in hoobs ?)
will try to see what's going on. (will only be able to do so at end of day, fwiw)

Thanks for your patience!

**Comment by jvhooijdonk** [comment]
Can you work with this:

**[1/4] Resolving packages...
2/7/2022, 10:17:27 AM[2/4] Fetching packages...
2/7/2022, 10:17:28 AM[3/4] Linking dependencies...
2/7/2022, 10:17:28 AMwarning "homebridge-vieramatic > @hookstate/core@3.0.13" has unmet peer dependency "react@^16.8.6 || ^17.0.0".
2/7/2022, 10:17:28 AMwarning "homebridge-vieramatic > react-bootstrap@1.6.4" has unmet peer dependency "react@>=16.8.0".
2/7/2022, 10:17:28 AMwarning "homebridge-vieramatic > react-bootstrap@1.6.4" has unmet peer dependency "react-dom@>=16.8.0".
2/7/2022, 10:17:28 AMwarning "homebridge-vieramatic > react-bootstrap > @restart/context@2.1.4" has unmet peer dependency "react@>=16.3.2".
2/7/2022, 10:17:28 AMwarning "homebridge-vieramatic > react-bootstrap > @restart/hooks@0.3.27" has unmet peer dependency "react@>=16.8.0".
2/7/2022, 10:17:28 AMwarning "homebridge-vieramatic > react-bootstrap > prop-types-extra@1.1.1" has unmet peer dependency "react@>=0.14.0".
2/7/2022, 10:17:28 AMwarning "homebridge-vieramatic > react-bootstrap > react-overlays@5.1.1" has unmet peer dependency "react@>=16.3.0".
2/7/2022, 10:17:28 AMwarning "homebridge-vieramatic > react-bootstrap > react-overlays@5.1.1" has unmet peer dependency "react-dom@>=16.3.0".
2/7/2022, 10:17:28 AMwarning "homebridge-vieramatic > react-bootstrap > react-transition-group@4.4.2" has unmet peer dependency "react@>=16.6.0".
2/7/2022, 10:17:28 AMwarning "homebridge-vieramatic > react-bootstrap > react-transition-group@4.4.2" has unmet peer dependency "react-dom@>=16.6.0".
2/7/2022, 10:17:28 AMwarning "homebridge-vieramatic > react-bootstrap > uncontrollable@7.2.1" has unmet peer dependency "react@>=15.0.0".
2/7/2022, 10:17:28 AMwarning "homebridge-vieramatic > @fortawesome/react-fontawesome@0.1.17" has unmet peer dependency "@fortawesome/fontawesome-svg-core@~1 || >=1.3.0-beta1".
2/7/2022, 10:17:28 AMwarning "homebridge-vieramatic > @fortawesome/react-fontawesome@0.1.17" has unmet peer dependency "react@>=16.x".
2/7/2022, 10:17:32 AM[4/4] Building fresh packages...
2/7/2022, 10:17:32 AMsuccess Saved lockfile.
2/7/2022, 10:17:32 AMsuccess Saved 3 new dependencies.
2/7/2022, 10:17:32 AMinfo Direct dependencies
2/7/2022, 10:17:32 AM└─ homebridge-vieramatic@4.0.24
2/7/2022, 10:17:32 AMinfo All dependencies
2/7/2022, 10:17:32 AM├─ @fortawesome/react-fontawesome@0.1.17
2/7/2022, 10:17:32 AM├─ homebridge-vieramatic@4.0.24
2/7/2022, 10:17:32 AM└─ preact@10.6.5
2/7/2022, 10:17:32 AMDone in 8.00s.
2/7/2022, 10:17:32 AMPanaBridgeConfiguration change
2/7/2022, 10:17:32 AMpanabridge stopping
2/7/2022, 10:17:37 AMPanaBridge starting
2/7/2022, 10:17:42 AMPanaBridgeERRORError loading plugin "homebridge-vieramatic"
2/7/2022, 10:17:42 AMPanaBridgeWARNINGNo plugins installed.
2/7/2022, 10:17:42 AMPanaBridgeLoading 1 platforms...
2/7/2022, 10:17:42 AMPanaBridgeBridge is running on port 51846**.

**Comment by AntonioMeireles** [comment]
THANKS! this is *interesting* :|. what npm version is hoobs shipping ? (attach plz `npm version` output in you hoobs box)

**Comment by jvhooijdonk** [comment]
hoobs@hoobs:~ $ npm version
{
  npm: '8.1.2',
  node: '16.13.2',
  v8: '9.4.146.24-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
hoobs@hoobs:~ $

**Comment by jvhooijdonk** [comment]
If you need more information please let me know!

**Comment by AntonioMeireles** [comment]
give a try please to `homebridge-vieramatic@4.0.25-beta2` and see if it fix this issue, also attach debug logs .

Thanks again.

**Comment by jvhooijdonk** [comment]
Just installed the version:
**hoobs@hoobs:~ $ sudo npm install -g homebridge-vieramatic@4.0.25-beta2
[sudo] password for hoobs:

added 81 packages, and audited 82 packages in 33s

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 8.1.2 -> 8.4.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.4.1
npm notice Run npm install -g npm@8.4.1 to update!
npm notice**

But there is no logging whatsoever in the Hoobs webconsole or a version change in the webconsole. Noob question, but how can I check the version and see the logging form the terminal?

**Comment by jvhooijdonk** [comment]
BTW, everything is still running

**Comment by AntonioMeireles** [comment]
fwiw, not an hoobs user, but afaik you should be able to see plugin version in its UI. still need to understand this issue way better, as it should have been failing before. Thanks again!

**Comment by jvhooijdonk** [comment]
This is what is says in the GUI after updating to the BETA version.

![image](https://user-images.githubusercontent.com/42796272/152781200-213226dd-70ad-443d-a184-730a89530497.png)

**Comment by AntonioMeireles** [comment]
oosp, that's the old version... follow upstream docs plz here - https://support.hoobs.org/docs/60e0cdc7646faaa152f10dd9 (`Plugins Versions` at the bottom of that page)

**Comment by jvhooijdonk** [comment]
Just updated to version 4.0.25BETA2 via the GUI, sam result:

2/7/2022, 12:44:04 PMyarn add v1.22.17
2/7/2022, 12:44:04 PM[1/4] Resolving packages...
2/7/2022, 12:44:08 PM[2/4] Fetching packages...
2/7/2022, 12:44:09 PM[3/4] Linking dependencies...
2/7/2022, 12:44:09 PMwarning "homebridge-vieramatic > @fortawesome/react-fontawesome@0.1.17" has unmet peer dependency "@fortawesome/fontawesome-svg-core@~1 || >=1.3.0-beta1".
2/7/2022, 12:44:12 PM[4/4] Building fresh packages...
2/7/2022, 12:44:12 PMsuccess Saved lockfile.
2/7/2022, 12:44:13 PMsuccess Saved 5 new dependencies.
2/7/2022, 12:44:13 PMinfo Direct dependencies
2/7/2022, 12:44:13 PM└─ homebridge-vieramatic@4.0.25-beta2
2/7/2022, 12:44:13 PMinfo All dependencies
2/7/2022, 12:44:13 PM├─ @preact/compat@17.0.3
2/7/2022, 12:44:13 PM├─ fast-xml-parser@4.0.2
2/7/2022, 12:44:13 PM├─ homebridge-vieramatic@4.0.25-beta2
2/7/2022, 12:44:13 PM├─ react-dom@17.0.3
2/7/2022, 12:44:13 PM└─ react@17.0.3
2/7/2022, 12:44:13 PMDone in 8.52s.
2/7/2022, 12:44:15 PMPanaBridgeConfiguration change
2/7/2022, 12:44:15 PMpanabridge stopping
2/7/2022, 12:44:20 PMPanaBridge starting
2/7/2022, 12:44:24 PMPanaBridgeERRORError loading plugin "homebridge-vieramatic"
2/7/2022, 12:44:24 PMPanaBridgeWARNINGNo plugins installed.
2/7/2022, 12:44:24 PMPanaBridgeLoading 1 platforms...
2/7/2022, 12:44:24 PMPanaBridgeBridge is running on port 51846.

**Comment by AntonioMeireles** [comment]
progress. thanks! new test version in a bit.

**Comment by AntonioMeireles** [comment]
try please `homebridge-vieramatic@4.0.25-beta3`

**Comment by jvhooijdonk** [comment]
As soon as it's available I will test it, it took about 40 minutes when you posted the former Beta version.

**Comment by jvhooijdonk** [comment]
Beta 3 installed, same result.

**2/7/2022, 1:40:11 PMyarn add v1.22.17
2/7/2022, 1:40:12 PM[1/4] Resolving packages...
2/7/2022, 1:40:15 PM[2/4] Fetching packages...
2/7/2022, 1:40:18 PM[3/4] Linking dependencies...
2/7/2022, 1:40:22 PM[4/4] Building fresh packages...
2/7/2022, 1:40:23 PMsuccess Saved lockfile.
2/7/2022, 1:40:23 PMsuccess Saved 6 new dependencies.
2/7/2022, 1:40:23 PMinfo Direct dependencies
2/7/2022, 1:40:23 PM└─ homebridge-vieramatic@4.0.25-beta3
2/7/2022, 1:40:23 PMinfo All dependencies
2/7/2022, 1:40:23 PM├─ @fortawesome/fontawesome-svg-core@1.2.36
2/7/2022, 1:40:23 PM├─ @preact/compat@17.0.3
2/7/2022, 1:40:23 PM├─ fast-xml-parser@4.0.2
2/7/2022, 1:40:23 PM├─ homebridge-vieramatic@4.0.25-beta3
2/7/2022, 1:40:23 PM├─ react-dom@17.0.3
2/7/2022, 1:40:23 PM└─ react@17.0.3
2/7/2022, 1:40:23 PMDone in 11.71s.
2/7/2022, 1:40:25 PMPanaBridgeConfiguration change
2/7/2022, 1:40:25 PMpanabridge stopping
2/7/2022, 1:40:30 PMPanaBridge starting
2/7/2022, 1:40:35 PMPanaBridgeERRORError loading plugin "homebridge-vieramatic"
2/7/2022, 1:40:35 PMPanaBridgeWARNINGNo plugins installed.
2/7/2022, 1:40:35 PMPanaBridgeLoading 1 platforms...
2/7/2022, 1:40:35 PMPanaBridgeBridge is running on port 51846**.

**Comment by jvhooijdonk** [comment]
To show you the difference, just installed the last working version (4.0.23):

**2/7/2022, 1:42:16 PMyarn add v1.22.17
2/7/2022, 1:42:16 PM[1/4] Resolving packages...
2/7/2022, 1:42:18 PM[2/4] Fetching packages...
2/7/2022, 1:42:18 PM[3/4] Linking dependencies...
2/7/2022, 1:42:18 PMwarning "homebridge-vieramatic > @fortawesome/react-fontawesome@0.1.17" has unmet peer dependency "@fortawesome/fontawesome-svg-core@~1 || >=1.3.0-beta1".
2/7/2022, 1:42:18 PMwarning "homebridge-vieramatic > @fortawesome/react-fontawesome@0.1.17" has unmet peer dependency "react@>=16.x".
2/7/2022, 1:42:18 PMwarning "homebridge-vieramatic > @hookstate/core@3.0.13" has unmet peer dependency "react@^16.8.6 || ^17.0.0".
2/7/2022, 1:42:18 PMwarning "homebridge-vieramatic > react-bootstrap@1.6.4" has unmet peer dependency "react@>=16.8.0".
2/7/2022, 1:42:18 PMwarning "homebridge-vieramatic > react-bootstrap@1.6.4" has unmet peer dependency "react-dom@>=16.8.0".
2/7/2022, 1:42:18 PMwarning "homebridge-vieramatic > react-bootstrap > @restart/context@2.1.4" has unmet peer dependency "react@>=16.3.2".
2/7/2022, 1:42:18 PMwarning "homebridge-vieramatic > react-bootstrap > @restart/hooks@0.3.27" has unmet peer dependency "react@>=16.8.0".
2/7/2022, 1:42:18 PMwarning "homebridge-vieramatic > react-bootstrap > prop-types-extra@1.1.1" has unmet peer dependency "react@>=0.14.0".
2/7/2022, 1:42:18 PMwarning "homebridge-vieramatic > react-bootstrap > react-overlays@5.1.1" has unmet peer dependency "react@>=16.3.0".
2/7/2022, 1:42:18 PMwarning "homebridge-vieramatic > react-bootstrap > react-overlays@5.1.1" has unmet peer dependency "react-dom@>=16.3.0".
2/7/2022, 1:42:18 PMwarning "homebridge-vieramatic > react-bootstrap > react-transition-group@4.4.2" has unmet peer dependency "react@>=16.6.0".
2/7/2022, 1:42:18 PMwarning "homebridge-vieramatic > react-bootstrap > react-transition-group@4.4.2" has unmet peer dependency "react-dom@>=16.6.0".
2/7/2022, 1:42:18 PMwarning "homebridge-vieramatic > react-bootstrap > uncontrollable@7.2.1" has unmet peer dependency "react@>=15.0.0".
2/7/2022, 1:42:22 PM[4/4] Building fresh packages...
2/7/2022, 1:42:22 PMsuccess Saved lockfile.
2/7/2022, 1:42:22 PMsuccess Saved 2 new dependencies.
2/7/2022, 1:42:22 PMinfo Direct dependencies
2/7/2022, 1:42:22 PM└─ homebridge-vieramatic@4.0.23
2/7/2022, 1:42:22 PMinfo All dependencies
2/7/2022, 1:42:22 PM├─ fast-xml-parser@4.0.2
2/7/2022, 1:42:22 PM└─ homebridge-vieramatic@4.0.23
2/7/2022, 1:42:22 PMDone in 6.29s.
2/7/2022, 1:42:24 PMPanaBridgeConfiguration change
2/7/2022, 1:42:24 PMpanabridge stopping
2/7/2022, 1:42:29 PMPanaBridge starting
2/7/2022, 1:42:35 PMPanaBridgeLoaded plugin 'homebridge-vieramatic'
2/7/2022, 1:42:35 PMPanaBridgeRegistering platform 'homebridge-vieramatic.PanasonicVieraTV'
2/7/2022, 1:42:35 PMPanaBridgeLoading 1 platforms...
2/7/2022, 1:42:35 PMPanaBridgePanasonicVieraTVhandling '192.168.178.39' from config.json
2/7/2022, 1:42:35 PMPanaBridgeBridge is running on port 51846.
2/7/2022, 1:42:35 PMPanaBridgePanasonicVieraTVfound a 'Panasonic VIErA' TV (TX-65HZ2000W) at '192.168.178.39' (requires crypto for communication).
2/7/2022, 1:42:35 PMPanaBridgePanasonicVieraTVWARNINGUsing previously cached App listing.
2/7/2022, 1:42:35 PMPanaBridgePanasonicVieraTVsuccessfully loaded Panasonic
2/7/2022, 1:42:35 PMPanaBridgePanasonic DB1B is running on port 35015.**

**Comment by AntonioMeireles** [comment]
Thanks yet again ... try please `homebridge-vieramatic@4.0.25-beta4`

**Comment by jvhooijdonk** [comment]
Beta 4 works!

**2/7/2022, 2:58:34 PMyarn add v1.22.17
2/7/2022, 2:58:34 PM[1/4] Resolving packages...
2/7/2022, 2:58:37 PM[2/4] Fetching packages...
2/7/2022, 2:58:39 PM[3/4] Linking dependencies...
2/7/2022, 2:58:42 PM[4/4] Building fresh packages...
2/7/2022, 2:58:43 PMsuccess Saved lockfile.
2/7/2022, 2:58:43 PMsuccess Saved 6 new dependencies.
2/7/2022, 2:58:43 PMinfo Direct dependencies
2/7/2022, 2:58:43 PM└─ homebridge-vieramatic@4.0.25-beta4
2/7/2022, 2:58:43 PMinfo All dependencies
2/7/2022, 2:58:43 PM├─ @fortawesome/fontawesome-svg-core@1.2.36
2/7/2022, 2:58:43 PM├─ @preact/compat@17.0.3
2/7/2022, 2:58:43 PM├─ fast-xml-parser@4.0.2
2/7/2022, 2:58:43 PM├─ homebridge-vieramatic@4.0.25-beta4
2/7/2022, 2:58:43 PM├─ react-dom@17.0.3
2/7/2022, 2:58:43 PM└─ react@17.0.3
2/7/2022, 2:58:43 PMDone in 8.91s.
2/7/2022, 2:58:45 PMPanaBridgeConfiguration change
2/7/2022, 2:58:45 PMpanabridge stopping
2/7/2022, 2:58:50 PMPanaBridge starting
2/7/2022, 2:58:56 PMPanaBridgeLoaded plugin 'homebridge-vieramatic'
2/7/2022, 2:58:56 PMPanaBridgeRegistering platform 'homebridge-vieramatic.PanasonicVieraTV'
2/7/2022, 2:58:56 PMPanaBridgeLoading 1 platforms...
2/7/2022, 2:58:56 PMPanaBridgePanasonicVieraTVhandling '192.168.178.39' from config.json
2/7/2022, 2:58:56 PMPanaBridgeBridge is running on port 51846.
2/7/2022, 2:58:56 PMPanaBridgePanasonicVieraTVfound a 'Panasonic VIErA' TV (TX-65HZ2000W) at '192.168.178.39' (requires crypto for communication).
2/7/2022, 2:58:56 PMPanaBridgePanasonicVieraTVWARNINGUsing previously cached App listing.
2/7/2022, 2:58:56 PMPanaBridgePanasonicVieraTVsuccessfully loaded Panasonic
2/7/2022, 2:58:56 PMPanaBridgePanasonic DB1B is running on port 37767.**

**Comment by AntonioMeireles** [comment]
OK! many thanks. - FWIW, we've hit https://github.com/evanw/esbuild/issues/1958. 

in 4.0.24 i've dropped workaround for https://github.com/evanw/esbuild/issues/619#issuecomment-751995294 as it was supposed to be fixed. sadly, _fix_ has undesired side effects... 

can you check please. that `homebridge-vieramatic@4.0.25-beta5` _also_ **still* works ? (and also please attach the logs)

Thanks again for your patience!

**Comment by jvhooijdonk** [comment]
Sure, when it's visible I will test it. Takes about 30 minutes after publishing.

**Comment by AntonioMeireles** [comment]
@jvhooijdonk 

^^ :-)

**Comment by jvhooijdonk** [comment]
I checked several times but beta 5 isn’t available yet, is that correct?

**Comment by jvhooijdonk** [comment]
Thank you for all your effort! I will try it first thing tomorrow morning.

**Comment by jvhooijdonk** [comment]
Good morning, Beta 5 installed just fine:

**2/8/2022, 7:38:26 AMyarn add v1.22.17
2/8/2022, 7:38:27 AM[1/4] Resolving packages...
2/8/2022, 7:38:28 AM[2/4] Fetching packages...
2/8/2022, 7:38:30 AM[3/4] Linking dependencies...
2/8/2022, 7:38:30 AMwarning "homebridge-vieramatic > @fortawesome/react-fontawesome@0.1.17" has unmet peer dependency "@fortawesome/fontawesome-svg-core@~1 || >=1.3.0-beta1".
2/8/2022, 7:38:30 AMwarning "homebridge-vieramatic > @fortawesome/react-fontawesome@0.1.17" has unmet peer dependency "react@>=16.x".
2/8/2022, 7:38:30 AMwarning "homebridge-vieramatic > @hookstate/core@3.0.13" has unmet peer dependency "react@^16.8.6 || ^17.0.0".
2/8/2022, 7:38:30 AMwarning "homebridge-vieramatic > react-bootstrap@1.6.4" has unmet peer dependency "react@>=16.8.0".
2/8/2022, 7:38:30 AMwarning "homebridge-vieramatic > react-bootstrap@1.6.4" has unmet peer dependency "react-dom@>=16.8.0".
2/8/2022, 7:38:30 AMwarning "homebridge-vieramatic > react-bootstrap > @restart/context@2.1.4" has unmet peer dependency "react@>=16.3.2".
2/8/2022, 7:38:30 AMwarning "homebridge-vieramatic > react-bootstrap > @restart/hooks@0.3.27" has unmet peer dependency "react@>=16.8.0".
2/8/2022, 7:38:30 AMwarning "homebridge-vieramatic > react-bootstrap > prop-types-extra@1.1.1" has unmet peer dependency "react@>=0.14.0".
2/8/2022, 7:38:30 AMwarning "homebridge-vieramatic > react-bootstrap > react-overlays@5.1.1" has unmet peer dependency "react@>=16.3.0".
2/8/2022, 7:38:30 AMwarning "homebridge-vieramatic > react-bootstrap > react-overlays@5.1.1" has unmet peer dependency "react-dom@>=16.3.0".
2/8/2022, 7:38:30 AMwarning "homebridge-vieramatic > react-bootstrap > react-transition-group@4.4.2" has unmet peer dependency "react@>=16.6.0".
2/8/2022, 7:38:30 AMwarning "homebridge-vieramatic > react-bootstrap > react-transition-group@4.4.2" has unmet peer dependency "react-dom@>=16.6.0".
2/8/2022, 7:38:30 AMwarning "homebridge-vieramatic > react-bootstrap > uncontrollable@7.2.1" has unmet peer dependency "react@>=15.0.0".
2/8/2022, 7:38:33 AM[4/4] Building fresh packages...
2/8/2022, 7:38:33 AMsuccess Saved lockfile.
2/8/2022, 7:38:33 AMsuccess Saved 1 new dependency.
2/8/2022, 7:38:33 AMinfo Direct dependencies
2/8/2022, 7:38:33 AM└─ homebridge-vieramatic@4.0.25-beta5
2/8/2022, 7:38:33 AMinfo All dependencies
2/8/2022, 7:38:33 AM└─ homebridge-vieramatic@4.0.25-beta5
2/8/2022, 7:38:33 AMDone in 7.27s.
2/8/2022, 7:38:36 AMPanaBridgeConfiguration change
2/8/2022, 7:38:36 AMpanabridge stopping
2/8/2022, 7:38:41 AMPanaBridge starting
2/8/2022, 7:38:46 AMPanaBridgeLoaded plugin 'homebridge-vieramatic'
2/8/2022, 7:38:46 AMPanaBridgeRegistering platform 'homebridge-vieramatic.PanasonicVieraTV'
2/8/2022, 7:38:46 AMPanaBridgeLoading 1 platforms...
2/8/2022, 7:38:46 AMPanaBridgePanasonicVieraTVhandling '192.168.178.39' from config.json
2/8/2022, 7:38:46 AMPanaBridgeBridge is running on port 51846.
2/8/2022, 7:38:46 AMPanaBridgePanasonicVieraTVfound a 'Panasonic VIErA' TV (TX-65HZ2000W) at '192.168.178.39' (requires crypto for communication).
2/8/2022, 7:38:46 AMPanaBridgePanasonicVieraTVWARNINGUsing previously cached App listing.
2/8/2022, 7:38:46 AMPanaBridgePanasonicVieraTVsuccessfully loaded Panasonic
2/8/2022, 7:38:46 AMPanaBridgePanasonic DB1B is running on port 35449.**


On top of that I installed version 4.0.25 and that installed with success:

**2/8/2022, 7:40:22 AMyarn add v1.22.17
2/8/2022, 7:40:22 AM[1/4] Resolving packages...
2/8/2022, 7:40:25 AM[2/4] Fetching packages...
2/8/2022, 7:40:26 AM[3/4] Linking dependencies...
2/8/2022, 7:40:29 AM[4/4] Building fresh packages...
2/8/2022, 7:40:30 AMsuccess Saved lockfile.
2/8/2022, 7:40:30 AMsuccess Saved 5 new dependencies.
2/8/2022, 7:40:30 AMinfo Direct dependencies
2/8/2022, 7:40:30 AM└─ homebridge-vieramatic@4.0.25
2/8/2022, 7:40:30 AMinfo All dependencies
2/8/2022, 7:40:30 AM├─ @fortawesome/fontawesome-svg-core@1.3.0
2/8/2022, 7:40:30 AM├─ @preact/compat@17.0.3
2/8/2022, 7:40:30 AM├─ homebridge-vieramatic@4.0.25
2/8/2022, 7:40:30 AM├─ react-dom@17.0.3
2/8/2022, 7:40:30 AM└─ react@17.0.3
2/8/2022, 7:40:30 AMDone in 8.48s.
2/8/2022, 7:40:30 AMPanaBridgeConfiguration change
2/8/2022, 7:40:30 AMpanabridge stopping
2/8/2022, 7:40:36 AMPanaBridge starting
2/8/2022, 7:40:41 AMPanaBridgeLoaded plugin 'homebridge-vieramatic'
2/8/2022, 7:40:41 AMPanaBridgeRegistering platform 'homebridge-vieramatic.PanasonicVieraTV'
2/8/2022, 7:40:41 AMPanaBridgeLoading 1 platforms...
2/8/2022, 7:40:41 AMPanaBridgePanasonicVieraTVhandling '192.168.178.39' from config.json
2/8/2022, 7:40:41 AMPanaBridgeBridge is running on port 51846.
2/8/2022, 7:40:41 AMPanaBridgePanasonicVieraTVfound a 'Panasonic VIErA' TV (TX-65HZ2000W) at '192.168.178.39' (requires crypto for communication).
2/8/2022, 7:40:41 AMPanaBridgePanasonicVieraTVWARNINGUsing previously cached App listing.
2/8/2022, 7:40:41 AMPanaBridgePanasonicVieraTVsuccessfully loaded Panasonic
2/8/2022, 7:40:41 AMPanaBridgePanasonic DB1B is running on port 46867.**

Thank you so much for all the time and effort!

**Comment by AntonioMeireles** [comment]
@jvhooijdonk 

closing, per your feedback. 

Thank you again for your patience, and just bug again if issues arise!

All the best, 

António
