### ISSUE TITLE
Needs Encryption 

### ISSUE THREAD

**Issue by craigton** [AntonioMeireles/homebridge-vieramatic#98]
I have installed the Vieramatic Plugin 4.0.29 in Hoobs running 4.1.22 which looks to be running fine I have entered the settings for my TV but it is telling me its encrypted but I can't find and encryption code to enter. 

```
27/02/2022, 17:21:31Vieramatic Bridge starting
27/02/2022, 17:21:37Vieramatic BridgeLoaded plugin 'homebridge-vieramatic'
27/02/2022, 17:21:37Vieramatic BridgeLoading 1 platforms...
27/02/2022, 17:21:37Vieramatic BridgePanasonicVieraTVhandling '192.***.***.***' from config.json
27/02/2022, 17:21:37Vieramatic BridgeBridge is running on port 51846.
27/02/2022, 17:21:37Vieramatic BridgePanasonicVieraTVfound a 'Panasonic VIErA' TV (TX-49FX600B) at '192.***.***.***' (requires crypto for communication).
27/02/2022, 17:21:37Vieramatic BridgePanasonicVieraTVError'192.***.***.*** ('Panasonic VIErA')' ignored, as it is from a Panasonic TV that requires encryption and no working credentials were supplied.
```

Kind Regards

Craig.

**Comment by AntonioMeireles** [comment]
@craigton 

hi. 

the plugin will work OK in hoobs but the web UI won't. so when in hoobs you need to run `viera-pair` locally on the command line (per step 3 [here](https://github.com/AntonioMeireles/homebridge-vieramatic#the-old-fashioned-way-you-shouldnt-need-to-do-this-anymore-really-except-if-using-hoobs-or-similar)) and the update the plugin config. 

all the best, and a great weekend!

**Comment by craigton** [comment]
Many thanks

all sorted.

**Comment by AntonioMeireles** [comment]
@craigton 

great to hear! feel free to bug again if you find something not behaving to your expectations!

all the best, 

António
